✨ Feat: 通过fullpath获取sheet或者文章
halo-dev/halo pull request #1044
Opened 2020-08-25 12:50 UTC by xzzai

解决前后端分离的框架中，无法通过fullpath来获取自定义页面和文章内容
新加两个接口，分别通过fullpath来获取自定义页面和文章页面

2020-08-25 14:25 UTC, ruibaby commented
能解释一下实际的场景吗？

2020-08-25 14:26 UTC, ruibaby commented
我不是太明白为什么要拿 fullPath 去反解析得到 slug，然后再根据 slug 去查询文章或者页面。文章的数据中应该有 slug 吧。

2020-08-25 14:27 UTC, xzzai commented
> 我不是太明白为什么要拿 fullPath 去反解析得到 slug，然后再根据 slug 去查询文章或者页面。文章的数据中应该有 slug 吧。

如果我是一个直接访问的连接呢？不是并不是通过内部调转的方式

2020-08-25 14:28 UTC, xzzai commented
等于说我直接给你一个链接： https://baozi.fun/2020/05/23/halo-blog-transfer 。这种在前后端分离的场景的中，就无法获取到正确的文章

2020-08-25 14:30 UTC, ruibaby commented
但是你这样做也只是拿到数据啊，并不是实际跳转页面。

2020-08-25 14:32 UTC, xzzai commented
> 但是你这样做也只是拿到数据啊，并不是实际跳转页面。

这个针对的是前后端分离的场景，不需要跳转页面，只用数据就好了。至少针对我目前的场景是这样子

2020-08-25 14:34 UTC, ruibaby commented
> > 但是你这样做也只是拿到数据啊，并不是实际跳转页面。
> 
> 这个针对的是前后端分离的场景，不需要跳转页面，只用数据就好了。至少针对我目前的场景是这样子

那么只需要数据，为什么不能通过 id 和 slug 去拿。目前的自定义路由本身只针对后端渲染，前端无法适配。纯前端实现应该有自己的路由。

2020-08-26 01:01 UTC, LIlGG commented
实际上我觉得如果真的要前后端分离。就最好自己写个完整的独立博客比较好。
对于前后端分离的博客来说，seo是最大的问题，而seo对于博客来说又是必要的。所以不建议前后端分离去做博客，最好使用服务端渲染方式。
目前的接口应该是用来提供做一种数据监控的后台管理用的，而不是独立的前后端分离项目，有点脱离初衷了。

2020-08-26 01:05 UTC, xzzai commented
这里的前后端分离，并不是要单独部署。安装和使用方式都是没有变化的，只是编写的方式有变化。对于SEO，目前虽然还在探索中，但是也有相对好点的解决方案。

2020-08-26 01:15 UTC, LIlGG commented
> 这里的前后端分离，并不是要单独部署。安装和使用方式都是没有变化的，只是编写的方式有变化。对于SEO，目前虽然还在探索中，但是也有相对好点的解决方案。

我知道你的意思。 接口使用后台的，但SEO总是前后端分离的最大问题，这个我当初也研究了很久，但查询了那么多资料，最终资料里都是选择了服务端渲染。 而且也确实由他所说，路由不一样，在/api, /content 后得再多一个路由方案，比如/result/，就等于让他们再多做了一些工作。内容托管系统目前我还没看到过有类似你说的那种。

还有一点就是，他的管理系统可能对你的主题不再生效，尤其是各种预览功能。他的所有配置属性你得通过接口获得，可能会有安全风险。

不过你的这种想法和我是挺相同的，哈哈，实际上我也想要这种能够通过api获取的方式

2020-08-26 01:25 UTC, xzzai commented
> > 这里的前后端分离，并不是要单独部署。安装和使用方式都是没有变化的，只是编写的方式有变化。对于SEO，目前虽然还在探索中，但是也有相对好点的解决方案。
> 
> 我知道你的意思。 接口使用后台的，但SEO总是前后端分离的最大问题，这个我当初也研究了很久，但查询了那么多资料，最终资料里都是选择了服务端渲染。 而且也确实由他所说，路由不一样，在/api, /content 后得再多一个路由方案，比如/result/，就等于让他们再多做了一些工作。内容托管系统目前我还没看到过有类似你说的那种。
> 
> 还有一点就是，他的管理系统可能对你的主题不再生效，尤其是各种预览功能。他的所有配置属性你得通过接口获得，可能会有安全风险。
> 
> 不过你的这种想法和我是挺相同的，哈哈，实际上我也想要这种能够通过api获取的方式

关于seo，其实我目前还没有深入研究，所以也不知道具体存在哪些问题。后面做到了再说。
管理系统是有效的啊，使用方式几乎和目前的方式是一样的。关于安全，我认为博客几乎都是公开的，且只存在获取数据，并没有更新数据，我认为并没有多大的安全风险。

2020-08-26 01:36 UTC, LIlGG commented
> > > 这里的前后端分离，并不是要单独部署。安装和使用方式都是没有变化的，只是编写的方式有变化。对于SEO，目前虽然还在探索中，但是也有相对好点的解决方案。
> > 
> > 
> > 我知道你的意思。 接口使用后台的，但SEO总是前后端分离的最大问题，这个我当初也研究了很久，但查询了那么多资料，最终资料里都是选择了服务端渲染。 而且也确实由他所说，路由不一样，在/api, /content 后得再多一个路由方案，比如/result/，就等于让他们再多做了一些工作。内容托管系统目前我还没看到过有类似你说的那种。
> > 还有一点就是，他的管理系统可能对你的主题不再生效，尤其是各种预览功能。他的所有配置属性你得通过接口获得，可能会有安全风险。
> > 不过你的这种想法和我是挺相同的，哈哈，实际上我也想要这种能够通过api获取的方式
> 
> 关于seo，其实我目前还没有深入研究，所以也不知道具体存在哪些问题。后面做到了再说。
> 管理系统是有效的啊，使用方式几乎和目前的方式是一样的。关于安全，我认为博客几乎都是公开的，且只存在获取数据，并没有更新数据，我认为并没有多大的安全风险。

前后端分离的SEO问题在于，所有数据是使用api请求，然后通过js加载。 而蜘蛛爬的时候会跳过js，所以导致所有通过接口获取的内容，比如文章、说说等，蜘蛛都爬不到，而且我们的一些关键词，也是通过后台填写的，蜘蛛也爬不到，等于蜘蛛爬你的网页，只能爬到一个空白的框架，然后会被当做无用内容抛弃。
如果仍旧是放在 /theme 目录下，那确实是没有问题的。

博客也会有一些私密信息的，比如加密的文章或者加密的说说，或者你要获取开发者工具中的静态变量，这些系统级的变量都属于敏感。

另外说个后话，如果以后有插件功能，如何处理？也许所有的插件都需要你再动手加上api类型的调用方式，而不是由插件作者。

就是想和你讨论一下这些其实已知的问题。如果能够解决，我也很赞成前后端分离，毕竟那样的话，对于前端的开发语言就可以随意了。

2020-08-26 02:07 UTC, JohnNiang requested changes

2020-08-26 02:10 UTC, ruibaby requested changes

2020-08-26 02:10 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/api/SheetController.java
> +    @GetMapping("/slug")
可以不要了。

2020-08-26 02:10 UTC, ruibaby commented on src/main/java/run/halo/app/service/SheetService.java
> +    Sheet getSheetByFullPath(@NotBlank String fullPath);
可以不要了

2020-08-26 02:10 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/api/PostController.java
> +    @GetMapping("{slug}/slug")
这里的路由形式有待商榷。

2020-08-26 02:11 UTC, ruibaby commented
@LIlGG 前后端分离的方式开发主题我认为是利大于弊的，SEO 和路由确实是个问题，但是也不是没有办法解决。当然，content api 还需要不断完善。

2020-08-26 02:14 UTC, xzzai commented on src/main/java/run/halo/app/service/SheetService.java
> +    Sheet getSheetByFullPath(@NotBlank String fullPath);
你觉得获取sheet内容只用通过 slug，不需要通过全路径吗？我个人认为，获取sheet使用全路径比较好，因为 prefix 我看在后台是可以配置的

2020-08-26 02:14 UTC, xzzai commented on src/main/java/run/halo/app/controller/content/api/PostController.java
> +    @GetMapping("{slug}/slug")
使用上面老哥说的 /slug/{slug}

2020-08-26 02:27 UTC, LIlGG commented
> @LIlGG 前后端分离的方式开发主题我认为是利大于弊的，SEO 和路由确实是个问题，但是也不是没有办法解决。当然，content api 还需要不断完善。

可以尝试前后端分离，对于主题的开发者来说有更多的选择，正好之前有用vue写过一部分主题，后面归档了。等接口完善我可以打开再试试。

2020-08-26 02:27 UTC, ruibaby commented
> > @LIlGG 前后端分离的方式开发主题我认为是利大于弊的，SEO 和路由确实是个问题，但是也不是没有办法解决。当然，content api 还需要不断完善。
> 
> 可以尝试前后端分离，对于主题的开发者来说有更多的选择，正好之前有用vue写过一部分主题，后面归档了。等接口完善我可以打开再试试。

小机灵鬼，就你知道的多。

2020-08-26 02:33 UTC, LIlGG commented
> > > @LIlGG 前后端分离的方式开发主题我认为是利大于弊的，SEO 和路由确实是个问题，但是也不是没有办法解决。当然，content api 还需要不断完善。
> > 
> > 
> > 可以尝试前后端分离，对于主题的开发者来说有更多的选择，正好之前有用vue写过一部分主题，后面归档了。等接口完善我可以打开再试试。
> 
> 小机灵鬼，就你知道的多。

**来打我呀** 坑不得你们先填吗，哈哈ヾ(￣▽￣)Bye~Bye~

2020-08-27 16:06 UTC, ruibaby approved these changes

2020-08-27 16:08 UTC, merged