fix bug #1085
halo-dev/halo pull request #1122
Opened 2020-10-23 13:39 UTC by johnwonder

我测试上传了6个多G的文件没问题 #1085

2020-10-23 14:56 UTC, JohnNiang commented
#1085 中出现的 OOM 错误主要是因为我在获取 `run.halo.app.security.filter.AbstractAuthenticationFilter.getTokenFromRequest(AbstractAuthenticationFilter.java:250)` 的时候，jetty 解析参数的时候将上传的文件流输出在了 `byte[]` 中，导致 `Requested array size exceeds VM limit`。

理论上这是 jetty 的问题，不过通过这样的方式修复我们还需要调试一下。

2020-10-23 16:14 UTC, JohnNiang commented on src/main/resources/application-dev.yaml
> +    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
exclude 配置需配置到 application.yml 配置文件中，保证所有配置文件生效。

2020-10-23 16:44 UTC, JohnNiang commented
测试通过。

2020-10-23 16:47 UTC, guqing commented
上传8g视频出现java heap space这块还是要搞一下  比如弄个断点续传什么之类的处理一下才是王道

2020-10-23 16:48 UTC, guqing commented
日志
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745) ~[na:na]
	at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120) ~[na:na]
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95) ~[na:na]
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:137) ~[na:na]
	at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:173) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:797) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:482) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.MultiParts$MultiPartsUtilParser.getParts(MultiParts.java:112) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Request.getParts(Request.java:2382) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:529) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Request.getParameters(Request.java:430) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1059) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.getTokenFromRequest(AbstractAuthenticationFilter.java:250) ~[main/:na]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.isSufficientOneTimeToken(AbstractAuthenticationFilter.java:206) ~[main/:na]
	at run.halo.app.security.filter.AbstractAuthenticationFilter.doFilterInternal(AbstractAuthenticationFilter.java:184) ~[main/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at run.halo.app.filter.CorsFilter.doFilter(CorsFilter.java:49) ~[main/:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at run.halo.app.filter.LogFilter.doFilterInternal(LogFilter.java:38) ~[main/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) ~[spring-boot-actuator-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]

```

2020-10-23 16:53 UTC, JohnNiang commented
我刚刚测试 10G 文件上传，没有出现问题。

```java
2020-10-24 00:51:59.381 DEBUG 156870 --- [tp1993153814-60] run.halo.app.core.ControllerLogAop       : Request URL: [http://localhost:8090/api/admin/attachments/upload], URI: [/api/admin/attachments/upload], Request Method: [POST], IP: [0:0:0:0:0:0:0:1]
2020-10-24 00:51:59.381 DEBUG 156870 --- [tp1993153814-60] r.h.a.s.impl.AttachmentServiceImpl       : Starting uploading... type: [LOCAL], file: [bigfile]
2020-10-24 00:51:59.382 DEBUG 156870 --- [tp1993153814-60] r.h.app.handler.file.LocalFileHandler    : Base name: [bigfile-328bccaf764b4161b89ba7bf4a096437], extension: [] of original filename: [bigfile]
2020-10-24 00:51:59.382  INFO 156870 --- [tp1993153814-60] r.h.app.handler.file.LocalFileHandler    : Uploading file: [bigfile]to directory: [/home/johnniang/halo-dev/upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437.]
2020-10-24 00:52:09.710  INFO 156870 --- [tp1993153814-60] r.h.app.handler.file.LocalFileHandler    : Uploaded file: [bigfile] to directory: [/home/johnniang/halo-dev/upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437.] successfully
2020-10-24 00:52:09.717 DEBUG 156870 --- [tp1993153814-60] r.h.a.s.impl.AttachmentServiceImpl       : Attachment type: [LOCAL]
2020-10-24 00:52:09.717 DEBUG 156870 --- [tp1993153814-60] r.h.a.s.impl.AttachmentServiceImpl       : Upload result: [UploadResult(filename=bigfile, filePath=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., key=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., thumbPath=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., suffix=, mediaType=application/octet-stream, size=10737418240, width=null, height=null)]
2020-10-24 00:52:09.717 DEBUG 156870 --- [tp1993153814-60] r.h.a.s.impl.AttachmentServiceImpl       : Creating attachment: [Attachment(id=null, name=bigfile, path=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., fileKey=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., thumbPath=upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437., mediaType=application/octet-stream, suffix=, width=null, height=null, size=10737418240, type=LOCAL)]
Hibernate: select count(attachment0_.id) as col_0_0_ from attachments attachment0_ where attachment0_.path=?
Hibernate: insert into attachments (id, create_time, update_time, file_key, height, media_type, name, path, size, suffix, thumb_path, type, width) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2020-10-24 00:52:09.720 DEBUG 156870 --- [tp1993153814-60] run.halo.app.core.ControllerLogAop       : AttachmentController.uploadAttachment Response: [{"id":10,"name":"bigfile","path":"http://localhost:8090/upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437.","fileKey":"upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437.","thumbPath":"http://localhost:8090/upload/2020/10/bigfile-328bccaf764b4161b89ba7bf4a096437.","mediaType":"application/octet-stream","suffix":"","width":0,"height":0,"size":10737418240,"type":"LOCAL","createTime":1603471929718}], usage: [10339]ms
2020-10-24 00:52:10.358 DEBUG 156870 --- [tp1993153814-60] run.halo.app.filter.LogFilter            : Ending   url: [http://localhost:8090/api/admin/attachments/upload], method: [POST], ip: [0:0:0:0:0:0:0:1], status: [200], usage: [57047] ms
```

2020-10-23 16:54 UTC, JohnNiang commented
@guqing 如果你使用的是非 application-dev.yml 配置文件，需要配置一下：

```yml
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguratio
```

2020-10-23 16:57 UTC, guqing commented
> @guqing 如果你使用的是非 application-dev.yml 配置文件，需要配置一下：
> 
> ```yaml
> spring:
>   autoconfigure:
>     exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguratio
> ```

sorry忘记看了 我刚刚发完日志才看了一下配置文件  重新试了一下 8g没问题

2020-10-23 17:01 UTC, ruibaby commented on src/main/resources/application-dev.yaml
> +    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
建议在 Application 类里面用注解 exclude。不想在配置文件有太多东西。

2020-10-23 17:01 UTC, ruibaby requested changes
建议在 Application 类里面用注解 exclude。不想在配置文件有太多东西。

2020-10-23 17:09 UTC, guqing commented
16g也测试通过

2020-10-23 23:39 UTC, johnwonder commented on src/main/resources/application-dev.yaml
> +    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
已去掉配置，改成在Application类添加exclude注解

2020-10-23 23:40 UTC, ruibaby approved these changes

2020-10-24 00:56 UTC, JohnNiang commented
@guqing 不应该啊，我记得设置的最大上传为 10G 啊😂

2020-10-24 01:18 UTC, JohnNiang commented
建议测试一下是否还起作用：

```properties
spring.servlet.multipart.max-file-size=128KB
spring.servlet.multipart.max-request-size=128KB
```

2020-10-24 03:31 UTC, johnwonder commented
@JohnNiang 因为在代码里手动定义了MultipartBean 把autoconfiguration排除了 所以在配置文件里定义的配置是失效的 除非再定义个confoguration class

2020-10-24 05:38 UTC, guqing commented
> @JohnNiang 因为在代码里手动定义了MultipartBean 把autoconfiguration排除了 所以在配置文件里定义的配置是失效的 可以在手动定义Bean的时候设置maxSize 要用外部配置的话可以定义个confoguration class导入外部配置

我觉得可以使用MultiPartProperties

2020-10-24 05:40 UTC, johnwonder commented
> > @JohnNiang 因为在代码里手动定义了MultipartBean 把autoconfiguration排除了 所以在配置文件里定义的配置是失效的 可以在手动定义Bean的时候设置maxSize 要用外部配置的话可以定义个confoguration class导入外部配置
> 
> 我觉得可以使用MultiPartProperties

加上了

2020-10-24 05:42 UTC, guqing commented
> > > @JohnNiang 因为在代码里手动定义了MultipartBean 把autoconfiguration排除了 所以在配置文件里定义的配置是失效的 可以在手动定义Bean的时候设置maxSize 要用外部配置的话可以定义个confoguration class导入外部配置
> > 
> > 我觉得可以使用MultiPartProperties
> 
> 加上了
ok看到了

2020-10-24 15:21 UTC, JohnNiang requested changes

2020-10-24 15:21 UTC, JohnNiang commented on src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
> +        resolver.setMaxUploadSize(multipartConfigElement.getMaxFileSize());
这里的配置似乎设置反了。

```java
resolver.setMaxUploadSize(multipartConfigElement.getMaxRequestSize());
resolver.setMaxUploadSizePerFile(multipartConfigElement.getMaxFileSize())
```

2020-10-24 15:34 UTC, JohnNiang commented
同时，也许要对 `org.apache.commons.fileupload.FileUploadBase$SizeLimitExceededException` 和 `org.apache.commons.fileupload.FileUploadBase$FileSizeLimitExceededException` 异常进行全局处理一下。

2020-10-24 15:36 UTC, JohnNiang commented on src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
> +        resolver.setMaxUploadSize(multipartConfigElement.getMaxFileSize());
也建议对 `org.springframework.web.multipart.MaxUploadSizeExceededException` 异常进行处理。

2020-10-25 02:15 UTC, johnwonder commented on src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
> +        resolver.setMaxUploadSize(multipartConfigElement.getMaxFileSize());
好的 改了

2020-10-25 03:31 UTC, johnwonder commented on src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
> +        resolver.setMaxUploadSize(multipartConfigElement.getMaxFileSize());
我本来觉得不要catch 这个异常的，因为已经有了multipart配置，可以手动使用
`boolean isMultiPart = MimeTypes.Type.MULTIPART_FORM_DATA.is(HttpFields.valueParameters(request.getContentType(), null));
 if(isMultiPart && request.getContentLength() > multipartProperties.getMaxFileSize().toBytes())
`
来判断上传大小，但是想想还是觉得交由框架层面去判断吧

2020-10-25 04:19 UTC, guqing approved these changes

2020-10-25 05:05 UTC, JohnNiang requested changes

2020-10-25 05:07 UTC, guqing commented on src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
> +        catch (NestedServletException nestedServletEx){
原来ResolveLazily是这个意思 我靠学到了🙊

2020-10-25 05:15 UTC, johnwonder commented on src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
> +        catch (NestedServletException nestedServletEx){
ok,忘了有全局异常处理。。。

2020-10-25 05:44 UTC, JohnNiang commented
需要去除未引用的 imports。

2020-10-25 05:51 UTC, guqing commented
> 需要去除未引用的 imports。

而且好像没有必要手动设置response.status了吧  会被注解处理

2020-10-25 05:54 UTC, JohnNiang commented
> 必要手动设置response.status了吧 会被注解处理

这里的 response 是返回给前端判断的，算是业务 status。

2020-10-25 05:56 UTC, merged

2020-10-25 05:56 UTC, guqing commented
> > 必要手动设置response.status了吧 会被注解处理
> 
> 这里的 response 是返回给前端判断的，算是业务 status。

我看错了 看到response以为是servlet的回复完才看到就删了😂

2022-05-16 11:09 UTC, XM2510136957 commented
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1375) ~[na:na]
	at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:494) ~[na:na]
	at java.base/java.lang.String.join(String.java:3264) ~[na:na]
	at java.base/java.lang.System$2.join(System.java:2438) ~[na:na]
	at java.base/java.util.StringJoiner.toString(StringJoiner.java:174) ~[na:na]
	at java.base/java.util.stream.Collectors$$Lambda$46/0x800000054.apply(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[na:na]
	at run.halo.app.utils.FileUtils.readString(FileUtils.java:575) ~[classes!/:1.5.3]
	at run.halo.app.service.impl.BackupServiceImpl.importMarkdown(BackupServiceImpl.java:235) ~[classes!/:1.5.3]
	at run.halo.app.controller.admin.api.BackupController.backupMarkdowns(BackupController.java:148) ~[classes!/:1.5.3]

2022-05-16 14:25 UTC, JohnNiang commented
> Caused by: java.lang.OutOfMemoryError: Java heap space at java.base/jdk.internal.misc.Unsafe.allocateUninitializedArray(Unsafe.java:1375) ~[na:na] at java.base/java.lang.StringConcatHelper.newArray(StringConcatHelper.java:494) ~[na:na] at java.base/java.lang.String.join(String.java:3264) ~[na:na] at java.base/java.lang.System$2.join(System.java:2438) ~[na:na] at java.base/java.util.StringJoiner.toString(StringJoiner.java:174) ~[na:na] at java.base/java.util.stream.Collectors$$Lambda$46/0x800000054.apply(Unknown Source) ~[na:na] at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:686) ~[na:na] at run.halo.app.utils.FileUtils.readString(FileUtils.java:575) ~[classes!/:1.5.3] at run.halo.app.service.impl.BackupServiceImpl.importMarkdown(BackupServiceImpl.java:235) ~[classes!/:1.5.3] at run.halo.app.controller.admin.api.BackupController.backupMarkdowns(BackupController.java:148) ~[classes!/:1.5.3]

See https://github.com/halo-dev/halo/issues/2088