将附件转换到当前handler并且更新post中的链接, Covert attachments to current Handler
halo-dev/halo pull request #1164
Opened 2020-11-24 02:07 UTC by XuCpeng

```java
@PutMapping("covert_attachment_handler")
    @ApiOperation("Covert all attachments to current Handler.")
    public Future<String> covertAttachmentHandler(
            @RequestParam(name = "sourceAttachmentTypeId", required = false, defaultValue = "-1") Integer sourceAttachmentTypeId,
            @RequestParam(name = "deleteOldAttachment", required = false, defaultValue = "false") Boolean deleteOldAttachment,
            @RequestParam(name = "uploadAllInAttachment", required = false, defaultValue = "false") Boolean uploadAllInAttachment,
            @RequestParam(name = "uploadAllInPost", required = false, defaultValue = "false") Boolean uploadAllInPost) {
        return attachmentHandlerCovertService.covertHandlerByPosts(
                sourceAttachmentTypeId,
                deleteOldAttachment,
                uploadAllInAttachment,
                uploadAllInPost);
    }
```

添加了一个接口，能够将附件库中的附件或者文章中的图片上传到“当前的图床”，并且更新post中的链接。基本原理是：正则提取post中markdown的的所有图片链接，用新的链接进行替换和更新。并且根据参数的设置，与附件中的链接进行比对，实现旧附件的删除或新附件的下载。

主要功能及参数如下：

- @param `sourceAttachmentTypeId`: 源图床ID (e.g. 0,1,2), 默认值为 -1 (所有图床).
- @param `deleteOldAttachment`:  是否从旧图床删除已经上传成功的附件，默认 false.
- @param `uploadAllInAttachment`:  是否上传源图床中所有附件，默认 false.
- @param `uploadAllInPost` : 是否抓取并上传post中的所有图片，默认 false.
- @return `AsyncResult<String>` 

1. `sourceAttachmentTypeId` 可以通过方法 `AttachmentType.getValue()` 获得, 特别的是，`-1`  表示使用所有图床作为源图床。
2. 若 `deleteOldAttachment = true`, 旧的附件在上传成功后将从源图床删除。
3. 若 `uploadAllInAttachment = true`, 将会上传源图床所有附件，即使没有被post使用；若为false则只上传被post使用的附件。
4. 若 `uploadAllInPost = true`, 将会自动抓取下载post中的所有图片，并且上传到当前hanlder，无论是否在附件库中。

TODO：自动更新图库中的链接。当前还不能自动更新图库中的链接，所以对图库有强烈需求的不要删除旧附件。

未写前端，测试方法：

1. 在网页端登录后台，获取headers中的tocken

![](https://user-images.githubusercontent.com/19551139/100032769-ab795f00-2e33-11eb-9457-0283d70906f9.png)

2. 在postman中创建一个PUT请求，请求地址为`<blog host>/api/admin/attachments/covert_attachment_handler`，并在Headers中加入该tocken，`admin-authorization: <tocken>`，参数按照上述添加即可。
![](https://user-images.githubusercontent.com/19551139/100033183-a49f1c00-2e34-11eb-8e41-be0fbb91b217.png)

3. 发送请求后将通过Async的方式执行，所以客户端会立即返回200，但实际的执行结果需要在`spring.log`中查看。方法完成后还会返回`AsyncResult<String>`，前端可以通过轮询获取结果。
---
Added an interface to upload the attachments in the attachment library or the pictures in the article to the "current handler" and update the md link in the post.

- @param `sourceAttachmentTypeId`: source attachment type id (e.g. 0,1,2), default = -1 (All AttachmentTypes).
- @param `deleteOldAttachment`:   Whether to delete old attachments, default = false.
- @param `uploadAllInAttachment`:  Whether to upload all attachments, default = false.
- @param `uploadAllInPost` :      Whether to download and upload all pictures in the all posts, default = false.
- @return `AsyncResult<String>` 

1. `sourceAttachmentTypeId` can be gotten by `AttachmentType.getValue()`, In particular, `-1` means to use all AttachmentTypes.
2. if `deleteOldAttachment = true`, Old attachments that have been successfully uploaded will be deleted from the specified Handler.
3. if `uploadAllInAttachment = true`, Will upload all attachments, even if they are not quoted by the post, default = false.
4. if `uploadAllInPost = true`, Will download and upload all pictures in the all posts, even if they are not in the attachment library.

No web, test method：

1. Log in to the admin on the web page and get the token in the headers.

![](https://user-images.githubusercontent.com/19551139/100032769-ab795f00-2e33-11eb-9457-0283d70906f9.png)

2. Create a PUT request in postman, the request address is `<blog host>/api/admin/attachments/covert_attachment_handler`，and add the token in Headers, `admin-authorization: <tocken>`，the parameters can be added as described above.
![](https://user-images.githubusercontent.com/19551139/100033183-a49f1c00-2e34-11eb-8e41-be0fbb91b217.png)

3. After sending the request, it will be executed by Async, so the client will immediately return 200，But the actual execution result needs to be checked in `spring.log`. After the method is completed, it will return `AsyncResult<String>`, and the web can get the result through polling.

TODO：Automatically update the links in the gallery.
Currently, the links in the gallery cannot be automatically updated, so do not delete old attachments if you have a strong demand for the gallery.

2020-11-30 12:58 UTC, ruibaby requested changes

2020-11-30 12:58 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
> +            @RequestParam(name = "sourceAttachmentTypeId", required = false, defaultValue = "-1") Integer sourceAttachmentTypeId,
应该直接使用 [AttachmentType](https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/model/enums/AttachmentType.java) 枚举作为参数。

2020-11-30 13:29 UTC, XuCpeng commented on src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
> +            @RequestParam(name = "sourceAttachmentTypeId", required = false, defaultValue = "-1") Integer sourceAttachmentTypeId,
ok，我将在近期更改为枚举类型参数，然后更新pull request。感谢您的代码审查。

2020-11-30 13:37 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
> +            @RequestParam(name = "sourceAttachmentTypeId", required = false, defaultValue = "-1") Integer sourceAttachmentTypeId,
晚点我们会对此 pr 做可行性测试，希望耐心等待。

2020-11-30 13:45 UTC, XuCpeng commented on src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
> +            @RequestParam(name = "sourceAttachmentTypeId", required = false, defaultValue = "-1") Integer sourceAttachmentTypeId,
明白。

2020-12-01 01:56 UTC, JohnNiang commented
如果能够提供对应的测试就更好了 ：P

2020-12-08 13:52 UTC, XuCpeng commented
> 如果能够提供对应的测试就更好了 ：P

AttachmentType已经更改为了枚举类型，并提供了一个简单的测试环境，希望有所帮助：

1. web监控后台日志 http://49.232.4.184:6688/#{%221607346748146%22:[%22halo|Tencent49%22]}
2. 登陆h2控制台 http://49.232.4.184:8090/h2-console/   (jdbc:h2:~/halo-dev/db/halo, admin/123456)
3. 登陆halo后台，查看两篇文章 http://49.232.4.184:8090/admin (服务器已关闭用户认证: admin@admin.com/12345678）
4. 在设置里找到存储位置，记下当前的存储位置(e.g. LOCAL)作为请求参数中的sourceAttachmentType。然后**更改存储位置**，其中QINIUOSS和SMMS已经设置好了参数，可以直接用来测试。
5. 发送PUT请求  http://49.232.4.184:8090/api/admin/attachments/covert_attachment_handler?sourceAttachmentType=LOCAL&deleteOldAttachment=true&uploadAllInAttachment=false&uploadAllInPost=false

- sourceAttachmentType，源handler(旧存储位置)，默认LOCAL （已测试LOCAL、QINIUOSS、SMMS）
- deleteOldAttachment，是否删除旧附件，默认false，建议true
- uploadAllInAttachment，是否上传源handler的所有附件，无论其是否被使用，默认false
- uploadAllInPost，是否上传post中的所有图片，无论其是否在附件库中，默认false，建议false

可任意组合四个参数，但是uploadAllInPost不建议多次测试，因为其不会删除旧附件导致产生很多重复的附件。

7. 查看文章md源码、附件库、数据库，检查效果。在后台日志中会看到[task - ] Start Cover ..., 转换完成后会输出stopwacth信息（因为文章图片较少执行时间约10～30s，若日志长时间未滚动，可能是堵塞，在博客中执行一下其他操作会刷出来）

重复4～7步，可在LOCAL、QINIUOSS、SMMS之间重复测试。

为了模拟极端情况，测试文章的内容可能看起来较乱。其中第一幅图不在附件库中，后面的图文件名中被加入了各种字符和空格，有的图片故意和其他内容挤在了一起。两篇文章中还有共用的图片。QINIUOSS设置了图片处理策略。	

所有操作仅支持以下文件类型：".jpg,.jpeg,.png,.gif,.bmp,.webp,.ico,.tiff,.tif,.svg,.emf"

2020-12-08 14:28 UTC, JohnNiang commented
感谢您的贡献，我马上再次 Review 一下。

2020-12-08 16:38 UTC, JohnNiang requested changes

2020-12-08 16:38 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +    public static byte[] readInputStream(InputStream inStream) throws IOException {
如果这里返回的是 byte[]，那么图片数据都会 load 到内存中，有可能会导致 OOM，特别是一些小型机器。

2020-12-08 16:38 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +        int i = md.indexOf("![");
如果单纯地这样判断链接的话，势必会造成误伤？比如代码块内的 `![xxx]` 格式的内容。

2020-12-08 16:38 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +    private static String searchSoundBrackets(int p, int nextI, String md) {
这些搜索方法，建议写一个单元测试保证其正确性。

2020-12-08 16:38 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/AttachmentHandlerCovertImpl.java
> +            e.printStackTrace();
不建议调用 e.pringStackTrace()。建议替换为：`log.warn("Download Failed: " + urlStr, e);`

2020-12-09 15:17 UTC, XuCpeng commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +    public static byte[] readInputStream(InputStream inStream) throws IOException {
学习了。已经重写了downloadFile方法。

2020-12-09 15:17 UTC, XuCpeng commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +        int i = md.indexOf("![");
这个方法还是比较严格的只会匹配完整的`![a](b)`结构，但之前的版本的确会匹配代码块中的内容。已添加删除代码块的操作，在搜索链接之前会先删除md中的` ```xxx``` `和` `xxx` `。具体可以看一下测试用例。

需要注意的是，在替换文章内容时，如果代码块中的链接在代码块之外出现过，代码块中的链接也会被替换。

2020-12-09 15:18 UTC, XuCpeng commented on src/main/java/run/halo/app/utils/AttachmentHandlerCovertUtils.java
> +    private static String searchSoundBrackets(int p, int nextI, String md) {
已经添加了单元测试文件，测试服务器也会一直开着，可随意测试。

2020-12-09 15:18 UTC, XuCpeng commented on src/main/java/run/halo/app/service/impl/AttachmentHandlerCovertImpl.java
> +            e.printStackTrace();
已删除所有的e.pringStackTrace()，并将异常插入到log里。感谢审阅 :D

2021-09-30 01:50 UTC, EzequielYa requested changes
Cambios

2022-01-06 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1164) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1164) it.</sub>

2022-04-18 03:58 UTC, ruibaby commented
感谢你的参与，但由于我们没有对此 PR 进行后续响应，1.5.x 也已经暂无新特性打算，如果后续对此特性有兴趣可以在 2.0 的时候参与。这个 PR 就先关闭了。

2022-04-18 03:58 UTC, ruibaby commented
/close

2022-04-18 03:58 UTC, closed without merging