add API for markdown-export
halo-dev/halo pull request #1199
Opened 2020-12-15 02:17 UTC by Raremaa

已经提交`Issue#1198`，
添加了一键以Markdown格式导出Halo所有的文章(打包ZIP)的API：
- /api/admin/backups/markdown-export [GET] 获取文件列表
- /api/admin/backups/markdown-export [POST] 导出为ZIP
- /api/admin/backups/markdown-export [DELETE] 删除文件
- /api/admin/backups/markdown-export/{filename=} [GET] 下载

前端页面后续再修改Halo-admin项目

2020-12-16 01:21 UTC, JohnNiang approved these changes

2020-12-16 02:15 UTC, ruibaby requested changes

2020-12-16 02:15 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/BackupController.java
> +    @PostMapping("markdown-export")
建议直接 `markdown`

2020-12-16 02:15 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +    public BackupDTO exportMarkdowns() throws IOException {
是否考虑在 Markdown 中生成额外的信息（Front-matter）

2020-12-16 02:16 UTC, ruibaby commented
另外提一点：

Markdown 中的图片怎么处理。

2020-12-16 02:29 UTC, Raremaa commented on src/main/java/run/halo/app/controller/admin/api/BackupController.java
> +    @PostMapping("markdown-export")
我注意到Halo的导入接口是/api/admin/backups/markdown[POST]，
如果都用markdown会不会语义上有歧义呢，因为添加的接口主要是用来导出

2020-12-16 02:37 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/BackupController.java
> +    @PostMapping("markdown-export")
好的，那你改成 /markdown/export 吧，顺便把 import 的加上 /import

2020-12-16 02:38 UTC, Raremaa commented on src/main/java/run/halo/app/controller/admin/api/BackupController.java
> +    @PostMapping("markdown-export")
好的

2020-12-16 02:40 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +    public BackupDTO exportMarkdowns() throws IOException {
可以 不过这东西目前我不是太清楚大家的需求(我个人不是太经常用到)，不太清楚要哪些内容，需要后续讨论一下

可以目前先简单加几个：
---
title: Hello World
date: 2013/7/13 20:46:25
url: http://xxxx
---

2020-12-16 02:41 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +    public BackupDTO exportMarkdowns() throws IOException {
可以参考一下 Hexo。

2020-12-16 02:42 UTC, Raremaa commented
> 另外提一点：
> 
> Markdown 中的图片怎么处理。

我个人单独使用第三方的OSS服务，文章内容本身就是外链地址所以不存在这个问题😂
我试一下如果用halo内置的图床是如何处理的

2020-12-16 02:59 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +    public BackupDTO exportMarkdowns() throws IOException {
看了以下，结合Halo的话，计划做成这样
```
---
title: Hello World
url: http://xxxxxx
date: 2013/7/13 20:46:25
updated: 2013/7/13 20:46:25
tags: 标签1 | 标签2
categories: 分类1 | 分类2 | 分类3
---
```

在导出的时候，api会有个参数，判断是否需要Front-matter决定是不是要带这个信息

最终的话，可以做成一个模板让作者去定制Front-matter样式，可以加一些表达式自定义时间的样式之类的功能，这个定制比较复杂了，后面再添加。

2020-12-24 13:23 UTC, ruibaby commented
这个 pr 还在继续吗？

2020-12-25 02:51 UTC, Raremaa commented
> 这个 pr 还在继续吗？

今晚推上来！

2020-12-25 14:19 UTC, ruibaby requested changes

2020-12-25 14:19 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                content.append(postMarkdownVO.getFrontMatter());
建议在  FrontMatter 和正文之间加个换行符。

2020-12-25 14:19 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                String markdownFileName = postMarkdownVO.getTitle() + "-" + IdUtil.simpleUUID().hashCode() + ".md";
文件名后面加上一串 hashCode 的作用是？

2020-12-25 14:59 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                String markdownFileName = postMarkdownVO.getTitle() + "-" + IdUtil.simpleUUID().hashCode() + ".md";
文件名只用标题的话，我认为可能不够唯一，没有标志性
但是我也在纠结，加了hashCode的话可读性又没有那么好了

2020-12-25 15:03 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                String markdownFileName = postMarkdownVO.getTitle() + "-" + IdUtil.simpleUUID().hashCode() + ".md";
> 文件名只用标题的话，我认为可能不够唯一，没有标志性
> 但是我也在纠结，加了hashCode的话可读性又没有那么好了

在 halo 重新导入的话，如果没有 FrontMatter 中的 title，会将文件名作为文章标题。而且导入到 Hexo 这样的平台，会将文件名作为链接的 slug，也不太友好。

是否可以将 slug 字段作为文件名？

2020-12-25 15:03 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                String markdownFileName = postMarkdownVO.getTitle() + "-" + IdUtil.simpleUUID().hashCode() + ".md";
如果光 slug 作为文件名不够直观的话，把 hashCode 改成文章的 slug 把。

2020-12-25 15:06 UTC, Raremaa commented
@ruibaby  不知道点了什么貌似不小心删了review的部分 我理解你意思，我用slug代替hashCode吧

2020-12-25 15:07 UTC, ruibaby commented
> @ruibaby 不知道点了什么貌似不小心删了review的部分 我理解你意思，我用slug代替hashCode吧

你点了 Resolve conversation 按钮，等这个问题解决之后你可以再点。

2020-12-25 15:19 UTC, Raremaa reviewed
> > @ruibaby 不知道点了什么貌似不小心删了review的部分 我理解你意思，我用slug代替hashCode吧
> 
> 你点了 Resolve conversation 按钮，等这个问题解决之后你可以再点。

搞定

2020-12-25 15:19 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                content.append(postMarkdownVO.getFrontMatter());
src/main/java/run/halo/app/service/impl/PostServiceImpl.java#868
有加换行符，这里得到的PostMarkdownVO其实封装了3部分内容：
- 标题
- front-matter
- 正文
其中，front-matter在postService中结尾已经带了换行符

2020-12-25 15:21 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                content.append(postMarkdownVO.getFrontMatter());
我导出之后好像没有哦。

![image](https://user-images.githubusercontent.com/21301288/103137863-e2c77e00-4707-11eb-81e7-56f88a4e674b.png)

2020-12-25 15:23 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +                content.append(postMarkdownVO.getFrontMatter());
哦哦😂 我加一下 应该是需要那个
```
--- 
```
下面加一个换行符

2020-12-26 02:30 UTC, ruibaby approved these changes

2020-12-27 15:58 UTC, merged

2020-12-27 15:59 UTC, ruibaby commented
感谢贡献🙌。