feat:#1225
halo-dev/halo pull request #1235
Opened 2021-01-23 06:46 UTC by zhixiangyuan

2021-01-23 06:50 UTC, JohnNiang commented
JDK 最低标准：https://github.com/halo-dev/halo/blob/7cb4f3464a268d0973f8ce278d8171529959012c/build.gradle#L14

2021-01-23 06:57 UTC, zhixiangyuan commented
> JDK 最低标准：
> 
> https://github.com/halo-dev/halo/blob/7cb4f3464a268d0973f8ce278d8171529959012c/build.gradle#L14

虽然 gradle 上指定了最低 jdk11，但是我看之前发布的版本都能在 jdk1.8 下面运行，所以我将我这次改动的代码中用到的非 jdk1.8 的代码用等价代码进行了替换，否则下次发布的时候用 1.8 编译会报错

2021-01-23 06:58 UTC, ruibaby commented
> > JDK 最低标准：
> > https://github.com/halo-dev/halo/blob/7cb4f3464a268d0973f8ce278d8171529959012c/build.gradle#L14
> 
> 虽然 gradle 上指定了最低 jdk11，但是我看之前发布的版本都能在 jdk1.8 下面运行，所以我将我这次改动的代码中用到的非 jdk1.8 的代码用等价代码进行了替换，否则下次发布的时候用 1.8 编译会报错

我们已经决定在 1.4.3 的时候包含这次 JDK 版本变化的破坏更新。也就是用户必须升级。

2021-01-23 06:58 UTC, ruibaby commented
你这次 PR 应该不会包含在 1.4.3 版本中，所以无需担心过。

2021-01-23 06:59 UTC, zhixiangyuan commented
> JDK 最低标准：
> 
> https://github.com/halo-dev/halo/blob/7cb4f3464a268d0973f8ce278d8171529959012c/build.gradle#L14

我这次提交中代码缩进和你们的标准不太一样，请问你们格式化是用的什么标准，有的话我去配置一下，然后把格式不对的代码格式化一下。

2021-01-23 07:00 UTC, zhixiangyuan commented
> 你这次 PR 应该不会包含在 1.4.3 版本中，所以无需担心。

了解了

2021-01-23 07:01 UTC, JohnNiang commented
> > JDK 最低标准：
> > https://github.com/halo-dev/halo/blob/7cb4f3464a268d0973f8ce278d8171529959012c/build.gradle#L14
> 
> 我这次提交中代码缩进和你们的标准不太一样，请问你们格式化是用的什么标准，有的话我去配置一下，然后把格式不对的代码格式化一下。

可以先尝试把 checkstyle 文件：<https://github.com/halo-dev/halo/blob/master/config/checkstyle/checkstyle.xml> 导入到 IDEA 中试试。如果格式还是会出问题，我晚上将重新整理并上传 .editorconfig。

2021-01-23 11:24 UTC, cetr commented
刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进，是不是遗漏了

2021-01-23 14:10 UTC, zhixiangyuan commented
> 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进，是代码没写完，还是遗漏了

你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。

你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。

2021-01-23 15:00 UTC, guqing commented
经测试没有发现功能问题

2021-01-23 16:27 UTC, guqing requested changes

2021-01-23 16:27 UTC, guqing commented on src/main/java/run/halo/app/controller/admin/api/CategoryController.java
> +            @PathVariable("categoryId") Integer categoryId,
这些格式化的更改属于无效提交 与原有格式风格不符

2021-01-23 16:27 UTC, guqing commented on src/main/java/run/halo/app/controller/admin/api/PostController.java
> +            OptionService optionService,
同上

2021-01-23 16:27 UTC, guqing commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        if ("post".equals(type)) {
魔法值 这里出现多个同一类值建议定义为枚举 (post，category)

2021-01-24 02:40 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/admin/api/PostController.java
> +            OptionService optionService,
如果第一行不换行我这边按照 checkstyle 格式化出来是下面这个样子，所以是不是 checkstyle 文件没有更新，是的话麻烦更新一下 checkstyle。

![image](https://user-images.githubusercontent.com/25138766/105619695-23620680-5e30-11eb-97a3-fbec039c709b.png)

2021-01-24 02:53 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        if ("post".equals(type)) {
这个问题改了

2021-01-24 03:01 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/admin/api/CategoryController.java
> +            @PathVariable("categoryId") Integer categoryId,
类似的地方都改了

2021-01-24 03:05 UTC, guqing commented on src/main/java/run/halo/app/controller/admin/api/CategoryController.java
> +            @PathVariable("categoryId") Integer categoryId,
> 类似的地方都改了

这个格式化问题可以稍微等一下  一会儿John上传一下.editorconfig文件 应该格式化就不会这样了  idea的配置和checkstyle不匹配

2021-01-24 03:06 UTC, guqing commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        if ("post".equals(type)) {
> 这个问题改了

好的  辛苦了🙃

2021-01-24 03:32 UTC, zhixiangyuan commented
@guqing 同学，你这边发起的 requested changes 我修复掉之后这个 requested changes 还是在，这个是你这边关掉还是我这边关掉，还是不用管？

![image](https://user-images.githubusercontent.com/25138766/105620413-d3873d80-5e37-11eb-9ef0-7aab9633c9a0.png)

2021-01-24 03:33 UTC, JohnNiang commented
@zhixiangyuan 你只需要持续 commit 就好了。

2021-01-24 03:34 UTC, zhixiangyuan commented
> @zhixiangyuan 你只需要持续 commit 就好了。

👌

2021-01-24 03:35 UTC, guqing commented
> @guqing 同学，你这边发起的 requested changes 我修复掉之后这个 requested changes 还是在，这个是你这边关掉还是我这边关掉，还是不用管？
> 
> ![image](https://user-images.githubusercontent.com/25138766/105620413-d3873d80-5e37-11eb-9ef0-7aab9633c9a0.png)
> 

不用管  等最终审批后就可以 每个人只有审批通过最终才能合并

2021-01-24 04:04 UTC, zhixiangyuan commented
> > @guqing 同学，你这边发起的 requested changes 我修复掉之后这个 requested changes 还是在，这个是你这边关掉还是我这边关掉，还是不用管？
> > ![image](https://user-images.githubusercontent.com/25138766/105620413-d3873d80-5e37-11eb-9ef0-7aab9633c9a0.png)
> 
> 不用管 等最终审批后就可以 每个人只有审批通过最终才能合并 一会儿我重新审核一下

👌

2021-01-24 04:07 UTC, cetr commented
> > 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进去，是代码没写完，还是遗漏了
> 
> 你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。
> 
> 你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。

![QQ截图20210124115610](https://user-images.githubusercontent.com/49756728/105620806-78efe080-5e3b-11eb-813a-0bd8b009b554.png)
![QQ截图20210124115304](https://user-images.githubusercontent.com/49756728/105620807-7bead100-5e3b-11eb-9d88-0231ce90e7b1.png)

下面两视屏下载到本地可以播放

https://user-images.githubusercontent.com/49756728/105620808-7f7e5800-5e3b-11eb-91ca-b84c9471fccb.mp4

https://user-images.githubusercontent.com/49756728/105620810-84dba280-5e3b-11eb-8330-8b88392febee.mp4

2021-01-24 04:17 UTC, zhixiangyuan commented
> > > 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进去，是代码没写完，还是遗漏了
> > 
> > 
> > 你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。
> > 你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。
> 
> ![QQ截图20210124115610](https://user-images.githubusercontent.com/49756728/105620806-78efe080-5e3b-11eb-813a-0bd8b009b554.png)
> ![QQ截图20210124115304](https://user-images.githubusercontent.com/49756728/105620807-7bead100-5e3b-11eb-9d88-0231ce90e7b1.png)
> 
> 下面两视屏下载到本地可以播放
> 
>  QQ.20210124115330.mp4 
>  QQ.20210124115441.mp4

同学，方便加一下微信沟通一下这个问题么，这是我的微信 id: anduin_jm

2021-01-24 04:20 UTC, cetr commented
> > > > 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进去，是代码没写完，还是遗漏了
> > > 
> > > 
> > > 你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。
> > > 你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。
> > 
> > 
> > ![QQ截图20210124115610](https://user-images.githubusercontent.com/49756728/105620806-78efe080-5e3b-11eb-813a-0bd8b009b554.png)
> > ![QQ截图20210124115304](https://user-images.githubusercontent.com/49756728/105620807-7bead100-5e3b-11eb-9d88-0231ce90e7b1.png)
> > 下面两视屏下载到本地可以播放
> > QQ.20210124115330.mp4 
> > QQ.20210124115441.mp4
> 
> 同学，方便加一下微信沟通一下这个问题么，这是我的微信id：anduin_jm

有TG吗

2021-01-24 04:25 UTC, zhixiangyuan commented
> > > > > 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进去，是代码没写完，还是遗漏了
> > > > 
> > > > 
> > > > 你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。
> > > > 你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。
> > > 
> > > 
> > > ![QQ截图20210124115610](https://user-images.githubusercontent.com/49756728/105620806-78efe080-5e3b-11eb-813a-0bd8b009b554.png)
> > > ![QQ截图20210124115304](https://user-images.githubusercontent.com/49756728/105620807-7bead100-5e3b-11eb-9d88-0231ce90e7b1.png)
> > > 下面两视屏下载到本地可以播放
> > > QQ.20210124115330.mp4
> > > QQ.20210124115441.mp4
> > 
> > 
> > 同学，方便加一下微信沟通一下这个问题么，这是我的微信id：anduin_jm
> 
> 有TG吗

有，username: xiangbeii

2021-01-24 04:30 UTC, guqing approved these changes

2021-01-24 04:53 UTC, zhixiangyuan commented
> > > > > > 刚才我试了下，从首页展示的文章进分类被加密的文章可以直接进去，是代码没写完，还是遗漏了
> > > > > 
> > > > > 
> > > > > 你说的这个问题我没有复现出来，正常来说直接拉取文章列表是不会展示加密文章的。你可以先建一个分类，然后给分类设置上密码，再将文章归到该分类下，然后进博客访问该分类，访问的时候会找你要密码，输入正确密码后即可看到分类下的文章。
> > > > > 你说的这个问题后续如果复现出来了麻烦详细说一下复现的流程，我这边会跟进处理掉。
> > > > 
> > > > 
> > > > 下面两视屏下载到本地可以播放
> > > > QQ.20210124115330.mp4
> > > > QQ.20210124115441.mp4
> > > 
> > > 
> > > 同学，方便加一下微信沟通一下这个问题么，这是我的微信id：anduin_jm
> > 
> > 
> > 有TG吗
> 
> 有，username: xiangbeii

目前代码无法复现这个问题

2021-01-24 04:55 UTC, guqing requested changes

2021-01-24 04:55 UTC, guqing commented on src/main/java/run/halo/app/service/impl/AuthenticationServiceImpl.java
> +            Set<String> accessPermissionStore,
这些格式化等.editorconfig提交以后处理以下

2021-01-24 04:55 UTC, guqing commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +        if (!bySlug.isPresent()) {
建议改为 bySlug.isEmpty()

2021-01-24 04:55 UTC, guqing commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException("查询不到该分类的信息").setErrorData(slug);
建议改为： Category category = bySlug.orElseThrow(() -> new NotFoundException("查询不到该分类的信息").setErrorData(slug));

2021-01-24 04:55 UTC, guqing commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +            return null;
isEmpty()

2021-01-24 04:55 UTC, guqing commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +                for (Integer categoryId : categoryIdList) {
我认为可以替换为： 
```
postCategoryService.listByPostId(postId)
                        .stream().map(PostCategory::getCategoryId)
                        .filter(this::categoryHasEncrypt)
                        .findAny()
                        .ifPresent(id -> {
                            post.setStatus(PostStatus.INTIMATE);
                        });
```

2021-01-24 05:23 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +        if (!bySlug.isPresent()) {
已改

2021-01-24 05:23 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +            throw new NotFoundException("查询不到该分类的信息").setErrorData(slug);
已改

2021-01-24 05:23 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +            return null;
已改

2021-01-24 05:24 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +                for (Integer categoryId : categoryIdList) {
已改，👍 这个写法确实优雅很多

2021-01-24 05:24 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/impl/AuthenticationServiceImpl.java
> +            Set<String> accessPermissionStore,
已改

2021-01-24 05:27 UTC, guqing commented on src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
> +                for (Integer categoryId : categoryIdList) {
我觉得这样看上去语意更明确  一眼看上去就知道目的是啥😂

2021-01-24 09:16 UTC, JohnNiang requested changes
新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。

2021-01-24 11:18 UTC, zhixiangyuan commented
> 新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。

合并了 master，`./gradlew check` 报出了一堆代码格式问题，这个应该是 master 上就要修复的吧，是不是等你们修复了这些问题之后我再合并一次？

以下是部分报错

![Uploading image.png…]()

2021-01-24 11:43 UTC, JohnNiang commented
> > 新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。
> 
> 合并了 master，`./gradlew check` 报出了一堆代码格式问题，这个应该是 master 上就要修复的吧，是不是等你们修复了这些问题之后我再合并一次？
> 
> 以下是部分报错
> 
> ![image](https://user-images.githubusercontent.com/25138766/105628636-fdad1f80-5e78-11eb-907f-35ff61e1e64f.png)

master 分支的代码已经是格式化之后的结果了，没有问题的。建议配合 checkstyle 插件（IDEA 插件）和格式化修正代码。

2021-01-24 12:10 UTC, zhixiangyuan commented
> > > 新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。
> > 
> > 
> > 合并了 master，`./gradlew check` 报出了一堆代码格式问题，这个应该是 master 上就要修复的吧，是不是等你们修复了这些问题之后我再合并一次？
> > 以下是部分报错
> 
> master 分支的代码已经是格式化之后的结果了，没有问题的。建议配合 checkstyle 插件（IDEA 插件）和格式化修正代码。

我看着上面报的错是缺少 javadoc 文档，不只是代码格式问题

2021-01-24 12:19 UTC, JohnNiang commented
> > > > 新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。
> > > 
> > > 
> > > 合并了 master，`./gradlew check` 报出了一堆代码格式问题，这个应该是 master 上就要修复的吧，是不是等你们修复了这些问题之后我再合并一次？
> > > 以下是部分报错
> > 
> > 
> > master 分支的代码已经是格式化之后的结果了，没有问题的。建议配合 checkstyle 插件（IDEA 插件）和格式化修正代码。
> 
> 我看着上面报的错是缺少 javadoc 文档，不只是代码格式问题

确实 javadoc 只会输出 warning 日志，不会认为是 error。

2021-01-24 12:32 UTC, zhixiangyuan commented
> > > > > 新的 checkstyle 和 .editorconfig 已合并。请重新导入 checkstyle 再格式化代码。
> > > > 
> > > > 
> > > > 合并了 master，`./gradlew check` 报出了一堆代码格式问题，这个应该是 master 上就要修复的吧，是不是等你们修复了这些问题之后我再合并一次？
> > > > 以下是部分报错
> > > 
> > > 
> > > master 分支的代码已经是格式化之后的结果了，没有问题的。建议配合 checkstyle 插件（IDEA 插件）和格式化修正代码。
> > 
> > 
> > 我看着上面报的错是缺少 javadoc 文档，不只是代码格式问题
> 
> 确实 javadoc 只会输出 warning 日志，不会认为是 error。

但我看这上面报出来的确实是 error 而且很多都是我没改动的文件，是不是 checkstyle 配置的有问题？

![image](https://user-images.githubusercontent.com/25138766/105630263-17536480-5e83-11eb-99b9-59c5b4588d34.png)

![image](https://user-images.githubusercontent.com/25138766/105630281-36ea8d00-5e83-11eb-8415-741b31593d93.png)

2021-01-24 12:33 UTC, JohnNiang commented
你当前 IDEA 的版本和 checkstyle 版本是多少？

2021-01-24 12:34 UTC, JohnNiang commented
我的配置：

![image](https://user-images.githubusercontent.com/16865714/105630335-83ce6380-5e83-11eb-87cb-184f32411d76.png)

2021-01-24 13:03 UTC, zhixiangyuan commented
> 我的配置：
> 

处理完了

2021-01-25 07:05 UTC, guqing approved these changes

2021-01-28 02:55 UTC, JohnNiang requested changes

2021-01-28 12:46 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/CategoryService.java
> +    List<Category> listAllNotEncrypt(Sort sort);
这里抽象父类 CrudService 里面有一个 `List<Category> listAll(Sort sort);` 的方法，这个方法加参数会引响到别的类，所以这里加了一个额外的方法，即 listAllNotEncrypt。

2021-01-28 13:26 UTC, zhixiangyuan commented on config/checkstyle/checkstyle.xml
> -
已撤销

2021-01-28 13:27 UTC, ruibaby requested changes

2021-01-28 13:27 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        redirectUrl.append("/categories/").append(slug);
现在 categories 不是一个固定的值了。OptionService#getCategoriesPrefix

2021-01-28 13:27 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/model/CategoryModel.java
> +            return "common/template/post_password";
现在可以支持主题开发者自定义了。参考 https://github.com/halo-dev/halo/pull/1236

2021-01-28 13:27 UTC, ruibaby commented on src/main/resources/templates/common/template/post_password.ftl
> +    <form method="post" action="${blog_url!}/archives/${type!}/${slug!}/password">
这个用一个专门的路由吧。前面还放着 archives 感觉怪怪的。

2021-01-28 13:33 UTC, zhixiangyuan commented on src/main/resources/templates/common/template/post_password.ftl
> +    <form method="post" action="${blog_url!}/archives/${type!}/${slug!}/password">
那这里感觉放什么比较好一点

2021-01-28 13:39 UTC, ruibaby commented on src/main/resources/templates/common/template/post_password.ftl
> +    <form method="post" action="${blog_url!}/archives/${type!}/${slug!}/password">
想不到，先留着吧，只是一个路径而已。

2021-01-28 14:43 UTC, JohnNiang commented on src/main/java/run/halo/app/service/CategoryService.java
> +    List<Category> listAllNotEncrypt(Sort sort);
你可以考虑重载： List<Category> listAll(Sort sort, boolean encrypted); 这样应该不会有冲突。你可以考虑 override `List<Category> listAll(Sort sort)` 方法，直接调用 listAll(sort, true | false)。

2021-01-29 02:32 UTC, zhixiangyuan commented on src/main/java/run/halo/app/service/CategoryService.java
> +    List<Category> listAllNotEncrypt(Sort sort);
改好了

2021-01-29 12:56 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        redirectUrl.append("/categories/").append(slug);
@zhixiangyuan 这里为什么要改回来呢？

2021-01-30 03:56 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/ContentContentController.java
> +        redirectUrl.append("/categories/").append(slug);
动 git 的时候不小心把代码回退了，已经改回来了

2021-01-31 06:48 UTC, zhixiangyuan commented
@ruibaby 同学，啥时候这个特性可以合到主干？

2021-01-31 06:48 UTC, merged

2021-01-31 06:49 UTC, ruibaby commented
@zhixiangyuan 已合并，感谢贡献。

2021-01-31 07:01 UTC, zhixiangyuan commented
> @zhixiangyuan 已合并，感谢贡献。

还有一个 https://github.com/halo-dev/halo-admin/pull/283，这个 admin 的 pull request

2021-01-31 07:05 UTC, zhixiangyuan commented
> > @zhixiangyuan 已合并，感谢贡献。
> 
> 还有一个 [halo-dev/halo-admin#283](https://github.com/halo-dev/halo-admin/pull/283)，这个 admin 的 pull request，用于给用户输入分类密码