About RSS/Atom
halo-dev/halo pull request #1339
Opened 2021-04-03 05:51 UTC by guanlei1996

1.Add the "lastBuildDate" in RSS.
2.Change the date format in RSS and Atom
3.Add the lastModified in the response header.

2021-04-07 08:23 UTC, ruibaby commented
你需要处理一下 checkstyle 的问题。https://github.com/halo-dev/halo/blob/master/config/checkstyle/checkstyle.xml

2021-04-07 08:58 UTC, JohnNiang commented
@guanlei1996 请参考：https://halo.run/archives/code-style 。

2021-04-07 09:23 UTC, ruibaby requested changes

2021-04-07 09:23 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/ContentFeedController.java
> +        if (!lastModifiedTimestamp.isPresent()) {
是不是应该这样判断 `lastModifiedTimestamp.isEmpty()`

2021-04-07 09:24 UTC, guanlei1996 commented on src/main/java/run/halo/app/controller/content/ContentFeedController.java
> +        if (!lastModifiedTimestamp.isPresent()) {
OK，今晚找时间一起处理

2021-04-08 01:30 UTC, guanlei1996 commented
我之前的仓库搞错了给删了，需要重新开一个 pull request，这个就先关了

2021-04-08 01:30 UTC, closed without merging