Add OptionFilter for bulk option api
halo-dev/halo pull request #1345
Opened 2021-04-08 15:19 UTC by JohnNiang

Close #1280

2021-04-08 15:22 UTC, ruibaby requested changes
`list_view` `map_view` 应该都是需要过滤的。

2021-04-08 15:23 UTC, ruibaby requested changes

2021-04-08 15:23 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/api/OptionController.java
> +    public Map<String, Object> listByNames(@RequestParam("names") String names) {
names 建议使用 keys，保证所有地方意义一致。

2021-04-08 16:10 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/content/api/OptionController.java
> +    public Map<String, Object> listByNames(@RequestParam("names") String names) {
Alright.

2021-04-09 02:22 UTC, ruibaby approved these changes

2021-04-09 02:33 UTC, guqing approved these changes

2021-04-09 02:52 UTC, JohnNiang reviewed
至于其他字段是否需要被禁用，用户自己本身可设置 private_options。

2021-04-09 02:52 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/OptionFilter.java
> +            EmailProperties.PASSWORD.getValue(),
我认为这里只需要禁用 password 就好。

2021-04-09 03:45 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/OptionFilter.java
> +            EmailProperties.PASSWORD.getValue(),
邮箱也能随便让人知道吗

2021-04-09 04:25 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/OptionFilter.java
> +            EmailProperties.PASSWORD.getValue(),
> 邮箱也能随便让人知道吗

我建议，默认仅屏蔽重要字段。邮箱可以屏蔽，也可以不屏蔽掉。

2021-04-09 04:28 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/OptionFilter.java
> +            EmailProperties.PASSWORD.getValue(),
done

2021-04-09 05:18 UTC, JohnNiang commented
/approve

2021-04-09 05:19 UTC, merged

2021-04-14 14:21 UTC, fuzui commented
想询问下在博客设置中是否有`private_options`的设置选项(我在基础选项/高级选项中没找到)。还是只能通过开发者选项中的系统变量去新增？

2021-04-14 14:25 UTC, ruibaby commented
这个 private_options 仅仅是用作于内部变量的设置，暂不支持自定义，自定义变量不受影响。

2021-04-14 14:26 UTC, JohnNiang commented
> 您好，想询问下在博客设置中是否有`private_options`的设置选项(我在基础选项/高级选项中没找到)。还是只能通过开发者选项中的系统变量去新增？

理论上这个 option 可以随意设置，不过我们还没有来得及添加这个功能到 halo-admin 中。

2021-04-14 14:35 UTC, JohnNiang commented
@fuzui 不过你可以打开开发者选项，手动添加 private_options。

2021-04-14 14:46 UTC, fuzui commented
了解了，感谢！
目前还有一个疑问，是否应该设置的为`public options`而非`private options`。因为当我在1.4.8版本中设置`private_options`后，假如在后面的某一个版本中新增了一个重要且不可暴露的参数`xxx_key`，这时我的`private_options`依然是我在1.4.8中设置的那些，此刻因为版本升级而我又未曾仔细留意，是否会造成参数`xxx_key`的暴露。

2021-04-14 14:55 UTC, JohnNiang commented
@fuzui 我们默认会对极其敏感的 option 进行过滤，不用担心后续版本中会暴露敏感的 option。后面我们会在文档中提及我们已经过滤了哪些 option(s)。

2021-04-14 14:58 UTC, fuzui commented
@JohnNiang 收到，感谢您的回复！