Word count for markdown updated with test
halo-dev/halo pull request #1354
Opened 2021-04-18 08:28 UTC by MasterWanna

Word count algorithm for markdown updated ignoring what should be removed.

2021-04-19 15:19 UTC, JohnNiang requested changes

2021-04-19 15:19 UTC, JohnNiang commented on src/test/java/run/halo/app/service/impl/BasePostServiceImplTest.java
> +    @Transactional
这里不需要 @Transactional 注解，这里并没有任何数据库操作。

2021-04-19 15:19 UTC, JohnNiang commented on src/test/java/run/halo/app/service/impl/BasePostServiceImplTest.java
> +    String markdownWithPicture = "字数测试，测试这篇文章加上图片有没有问题\n" +
希望能够增加更多的测试用例。

2021-04-19 15:19 UTC, JohnNiang commented on src/test/java/run/halo/app/service/impl/BasePostServiceImplTest.java
> +    String markdownWithPicture = "字数测试，测试这篇文章加上图片有没有问题\n" +
真是 markdown 有很多种格式，希望能够考虑完全。建议先把测试用例写好，再写代码。

2021-04-19 16:07 UTC, MasterWanna commented on src/test/java/run/halo/app/service/impl/BasePostServiceImplTest.java
> +    String markdownWithPicture = "字数测试，测试这篇文章加上图片有没有问题\n" +
好的，我会增加一些测试来完善

2021-04-20 01:24 UTC, LIlGG commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        return originalContent.length() - countChar(originalContent, '\n')
这里不是很明白为什么要遍历 originalContent 三次。如果文章过大会不会造成性能损耗？
建议使用正则表达式 \s 来处理空白符，我能想到的有两种方式
1. 你可以使用 replaceAll 删除所有空白符后再进行 length 计算
2. 如果觉得替换字符串浪费空间的话，可以使用 matcher.find 获取空白符出现次数，然后减去即可。

总之不是很建议循环多次 originalContent，而且这个操作正常来说循环一次即可，你可以在循环的时候判断多个类型的空白符，而不仅仅只局限于一个

2021-04-20 13:16 UTC, ruibaby requested changes

2021-04-20 13:16 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        originalContent = MarkdownUtils.renderHtml(originalContent);
不太明白你这里为什么要再渲染一次 Markdown，在上面已经渲染过了。

https://github.com/halo-dev/halo/pull/1354/files#diff-f9ad8998cd130957a3f023e24fdba020245e51c8fe132be355dc02200800fba9R285

2021-04-20 13:16 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        originalContent = MarkdownUtils.renderHtml(originalContent);
而且这应该处理的是 html 内容，而不是 Markdown，使用 Markdown 作为主线是不是有点问题？直接改为处理 HTML 就好了。

2021-04-20 15:14 UTC, MasterWanna commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        return originalContent.length() - countChar(originalContent, '\n')
好的，这个会去修改一下

2021-04-20 15:20 UTC, MasterWanna commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        originalContent = MarkdownUtils.renderHtml(originalContent);
这里markdown都可以转为html，html直接去掉标签，再去掉一些特殊字符就可以直接取length了，这边的测试样例应该怎么写呢？是以markdown为基础测试还是以html为基础做测试呢？

2021-04-23 14:18 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        originalContent = MarkdownUtils.renderHtml(originalContent);
> 这里markdown都可以转为html，html直接去掉标签，再去掉一些特殊字符就可以直接取length了，这边的测试样例应该怎么写呢？是以markdown为基础测试还是以html为基础做测试呢？

以 html

2021-04-23 14:33 UTC, MasterWanna commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        originalContent = MarkdownUtils.renderHtml(originalContent);
可以先写成markdown的形式再进行渲染，将渲染完的结果进行测试吗？

2021-04-23 15:27 UTC, LIlGG requested changes

2021-04-23 15:27 UTC, LIlGG commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        Matcher matcher = Pattern.compile("\\s").matcher(htmlContent);
Pattern 最好设置为常量或者属性，例如 private static Pattern p = Pattern.compile("\\s");

2021-04-23 15:29 UTC, MasterWanna commented on src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
> +        Matcher matcher = Pattern.compile("\\s").matcher(htmlContent);
好的，确实这样好一些

2021-04-24 01:05 UTC, JohnNiang requested changes

2021-04-24 01:05 UTC, JohnNiang commented on src/test/java/run/halo/app/service/impl/HTMLWordCountTest.java
> +public class HTMLWordCountTest {
需要增加一个复杂的测试用例（比如将以下所有测试用例合并）、空字符串、null 以及纯文本格式。

2021-05-01 09:43 UTC, JohnNiang requested changes
非常感谢你的 PR。如果能够再添加一个纯 html 文本的测试就更好了。

2021-05-02 05:10 UTC, merged