Modefy the content api to support list posts with new class PostQueryContent.
halo-dev/halo pull request #1373
Opened 2021-05-15 14:20 UTC by Cui-Yusong

相比之前的版本，把remove去掉了，另外在model/params里新建了一个PostQueryContent类，这样文档上就不会显示status了。

2021-05-16 03:11 UTC, ruibaby commented
感觉这样做不太好，还不如直接把 keyword 和 categoryId 当做参数。

你要修改的话，直接在这个分支 push commit 就行了，不用重新开 pr。

2021-05-16 03:37 UTC, Cui-Yusong commented
好的，我再尝试下，谢谢！

2021-05-16 09:15 UTC, ruibaby requested changes

2021-05-16 09:15 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/api/PostController.java
> +        @RequestParam(value = "keyword") String keyword) {
好像没有 categoryId

2021-05-16 09:15 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/api/PostController.java
> +        postQuery.setStatus(status);
直接 postQuery.setStatue(PostStatus.PUBLISHED) 就好了。

2021-05-16 09:24 UTC, Cui-Yusong commented
修改好了，添加了categoryid，简化了代码。

2021-05-16 09:25 UTC, ruibaby approved these changes

2021-05-17 06:35 UTC, ruibaby commented
需要处理一下 checkstyle 异常。

https://github.com/halo-dev/halo/pull/1373/checks?check_run_id=2596554135

2021-05-17 08:54 UTC, 1171-jpg commented
收到，我修改下！

2021-05-17 09:26 UTC, 1171-jpg commented
修改了checkstyle，然后那个title我最后其实放弃了用新的类的思路，直接通过requestparams去获取参数了。

2021-05-17 12:20 UTC, ruibaby approved these changes

2021-05-17 12:20 UTC, ruibaby commented
> 修改了checkstyle，然后那个title我最后其实放弃了用新的类的思路，直接通过requestparams去获取参数了。

什么 title

2021-05-17 13:36 UTC, 1171-jpg commented
哦哦，就是我怕这个pr的名字有误导性--Modify the content api to support list posts with new class PostQueryContent. 因为我后来没有采用这个引入新类的方法了

2021-05-17 13:38 UTC, merged

2021-05-17 13:39 UTC, ruibaby commented
@Cui-Yusong @1171-jpg 同一个人？

2021-05-17 13:55 UTC, 1171-jpg commented
啊不是，代码是我写的，提交时用的@Cui-Yusong 的账号，造成困扰了，不好意思哈