🐛: 修复回收站文章可访问的BUG
halo-dev/halo pull request #1382
Opened 2021-05-21 03:52 UTC by mimajiushi

#1381

2021-05-21 03:55 UTC, ruibaby commented
https://github.com/halo-dev/halo/issues/1381#issuecomment-845634598

可能需要考虑从 admin 访问的问题。

2021-05-21 03:56 UTC, JohnNiang reviewed
非常感谢您的 PR，如果能够加上对应的测试代码可能会更好。

测试步骤：

1. 创建一篇文章
2. 将文章的状态设置为 RECYCLE
3. 查询该文章详情
4. 检查是否出现 404 错误

2021-05-21 04:26 UTC, mimajiushi commented
> [#1381 (comment)](https://github.com/halo-dev/halo/issues/1381#issuecomment-845634598)
> 
> 可能需要考虑从 admin 访问的问题。

我看原来的逻辑admin也访问不到回收站的详情页吧

2021-05-21 04:27 UTC, mimajiushi commented
> 非常感谢您的 PR，如果能够加上对应的测试代码可能会更好。
> 
> 测试步骤：
> 
> 1. 创建一篇文章
> 2. 将文章的状态设置为 RECYCLE
> 3. 查询该文章详情
> 4. 检查是否出现 404 错误

晚点加下

2021-05-21 04:39 UTC, mimajiushi commented
> [#1381 (comment)](https://github.com/halo-dev/halo/issues/1381#issuecomment-845634598)
> 
> 可能需要考虑从 admin 访问的问题。

懂了，是草稿有问题

2021-05-21 08:20 UTC, mimajiushi commented
> 非常感谢您的 PR，如果能够加上对应的测试代码可能会更好。
> 
> 测试步骤：
> 
> 1. 创建一篇文章
> 2. 将文章的状态设置为 RECYCLE
> 3. 查询该文章详情
> 4. 检查是否出现 404 错误

加上测试代码了

2021-05-23 03:06 UTC, mimajiushi commented
@JohnNiang 有点不太明白现在的错误，我在本地不知道怎么复现😂

2021-05-23 03:06 UTC, mimajiushi commented
@JohnNiang 有点不太明白现在的错误，我在本地不知道怎么复现😂

2021-05-23 03:38 UTC, JohnNiang reviewed
> @JohnNiang 有点不太明白现在的错误，我在本地不知道怎么复现

问题已经找到。待会儿会提交一个 PR。

2021-05-23 03:38 UTC, JohnNiang commented on src/test/java/run/halo/app/it/BaseApiTest.java
> +        } catch (HttpClientErrorException.BadRequest e) {
这里应该不会报这个错误的。

2021-05-23 03:43 UTC, mimajiushi commented on src/test/java/run/halo/app/it/BaseApiTest.java
> +        } catch (HttpClientErrorException.BadRequest e) {
我在本地跑的时候IndexPageRequestTest也会安装博客，因此会爆出重复安装的错误，其异常类型就是这个

2021-05-23 03:43 UTC, mimajiushi commented on src/test/java/run/halo/app/it/BaseApiTest.java
> +        } catch (HttpClientErrorException.BadRequest e) {
> 这里应该不会报这个错误的。

我在本地跑test的时候IndexPageRequestTest也会安装博客，因此会爆出重复安装的错误，其异常类型就是这个

2021-05-23 07:13 UTC, JohnNiang commented on src/test/java/run/halo/app/it/BaseApiTest.java
> +        } catch (HttpClientErrorException.BadRequest e) {
在 BaseApiTest 类上加上  `@org.springframework.test.annotation.DirtiesContext` 注解即可。

2021-05-23 07:16 UTC, JohnNiang requested changes

2021-05-23 07:16 UTC, JohnNiang commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        MockitoAnnotations.initMocks(this);
MockitoAnnotations.initMocks -> MockitoAnnotations.open

2021-05-23 07:16 UTC, JohnNiang commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +            put(ADMIN_POST_URI + String.format("/%d/status/%s", postId, postStatus))
可以用 urlTemplate 来填充路径变量。

2021-05-23 07:16 UTC, JohnNiang commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        ).andDo(print())
```diff
-).andDo(print())
+)
+.andDo(print())
```

2021-05-23 07:16 UTC, JohnNiang commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        post.setTitle("回收站文章");
尽量用英文，下同。

2021-05-23 07:16 UTC, JohnNiang commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        String response = mvcResult.getResponse().getContentAsString(StandardCharsets.UTF_8);
可以用  .andExpect(jsonPath()...) 替代下面的逻辑。

2021-05-23 07:52 UTC, mimajiushi commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        MockitoAnnotations.initMocks(this);
done

2021-05-23 07:54 UTC, mimajiushi commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +            put(ADMIN_POST_URI + String.format("/%d/status/%s", postId, postStatus))
> 可以用 urlTemplate 来填充路径变量。

用了`org.springframework.web.util.UriTemplate`填充，不确定对没对

2021-05-23 07:54 UTC, mimajiushi commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        post.setTitle("回收站文章");
> 尽量用英文，下同。

done

2021-05-23 07:57 UTC, mimajiushi commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        String response = mvcResult.getResponse().getContentAsString(StandardCharsets.UTF_8);
> 可以用 .andExpect(jsonPath()...) 替代下面的逻辑。

这个貌似只能校验？我没找到直接根据`jsonPath`获取返回值的方法。目前是用这种方式加了段校验

2021-05-23 07:58 UTC, mimajiushi commented on src/test/java/run/halo/app/it/RequestRecycledPostTest.java
> +        MockitoAnnotations.initMocks(this);
> MockitoAnnotations.initMocks -> MockitoAnnotations.open

done

2021-05-26 07:06 UTC, mimajiushi commented
@JohnNiang 出现了奇怪的错误，在本地没复现，日志如下：
```
SheetRepositoryTest > listAllTest() STANDARD_OUT
    Hibernate: select sheet0_.id as id2_14_, sheet0_.create_time as create_t3_14_, sheet0_.update_time as update_t4_14_, sheet0_.disallow_comment as disallow5_14_, sheet0_.edit_time as edit_tim6_14_, sheet0_.editor_type as editor_t7_14_, sheet0_.format_content as format_c8_14_, sheet0_.likes as likes9_14_, sheet0_.meta_description as meta_de10_14_, sheet0_.meta_keywords as meta_ke11_14_, sheet0_.original_content as origina12_14_, sheet0_.password as passwor13_14_, sheet0_.slug as slug14_14_, sheet0_.status as status15_14_, sheet0_.summary as summary16_14_, sheet0_.template as templat17_14_, sheet0_.thumbnail as thumbna18_14_, sheet0_.title as title19_14_, sheet0_.top_priority as top_pri20_14_, sheet0_.url as url21_14_, sheet0_.visits as visits22_14_, sheet0_.word_count as word_co23_14_ from posts sheet0_ where sheet0_.type=1
    2021-05-26 06:51:44.282 ERROR 1932 --- [    Test worker] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "POSTS" not found; SQL statement:
    select sheet0_.id as id2_14_, sheet0_.create_time as create_t3_14_, sheet0_.update_time as update_t4_14_, sheet0_.disallow_comment as disallow5_14_, sheet0_.edit_time as edit_tim6_14_, sheet0_.editor_type as editor_t7_14_, sheet0_.format_content as format_c8_14_, sheet0_.likes as likes9_14_, sheet0_.meta_description as meta_de10_14_, sheet0_.meta_keywords as meta_ke11_14_, sheet0_.original_content as origina12_14_, sheet0_.password as passwor13_14_, sheet0_.slug as slug14_14_, sheet0_.status as status15_14_, sheet0_.summary as summary16_14_, sheet0_.template as templat17_14_, sheet0_.thumbnail as thumbna18_14_, sheet0_.title as title19_14_, sheet0_.top_priority as top_pri20_14_, sheet0_.url as url21_14_, sheet0_.visits as visits22_14_, sheet0_.word_count as word_co23_14_ from posts sheet0_ where sheet0_.type=1 [42102-197]

SheetRepositoryTest > listAllTest() FAILED
    org.springframework.dao.InvalidDataAccessResourceUsageException at SheetRepositoryTest.java:27
        Caused by: org.hibernate.exception.SQLGrammarException at SheetRepositoryTest.java:27
            Caused by: org.h2.jdbc.JdbcSQLException at SheetRepositoryTest.java:27
```

2021-05-26 13:44 UTC, JohnNiang commented
> @JohnNiang 出现了奇怪的错误，在本地没复现，CI错误日志如下：
> 
> ```
> SheetRepositoryTest > listAllTest() STANDARD_OUT
>     Hibernate: select sheet0_.id as id2_14_, sheet0_.create_time as create_t3_14_, sheet0_.update_time as update_t4_14_, sheet0_.disallow_comment as disallow5_14_, sheet0_.edit_time as edit_tim6_14_, sheet0_.editor_type as editor_t7_14_, sheet0_.format_content as format_c8_14_, sheet0_.likes as likes9_14_, sheet0_.meta_description as meta_de10_14_, sheet0_.meta_keywords as meta_ke11_14_, sheet0_.original_content as origina12_14_, sheet0_.password as passwor13_14_, sheet0_.slug as slug14_14_, sheet0_.status as status15_14_, sheet0_.summary as summary16_14_, sheet0_.template as templat17_14_, sheet0_.thumbnail as thumbna18_14_, sheet0_.title as title19_14_, sheet0_.top_priority as top_pri20_14_, sheet0_.url as url21_14_, sheet0_.visits as visits22_14_, sheet0_.word_count as word_co23_14_ from posts sheet0_ where sheet0_.type=1
>     2021-05-26 06:51:44.282 ERROR 1932 --- [    Test worker] o.h.engine.jdbc.spi.SqlExceptionHelper   : Table "POSTS" not found; SQL statement:
>     select sheet0_.id as id2_14_, sheet0_.create_time as create_t3_14_, sheet0_.update_time as update_t4_14_, sheet0_.disallow_comment as disallow5_14_, sheet0_.edit_time as edit_tim6_14_, sheet0_.editor_type as editor_t7_14_, sheet0_.format_content as format_c8_14_, sheet0_.likes as likes9_14_, sheet0_.meta_description as meta_de10_14_, sheet0_.meta_keywords as meta_ke11_14_, sheet0_.original_content as origina12_14_, sheet0_.password as passwor13_14_, sheet0_.slug as slug14_14_, sheet0_.status as status15_14_, sheet0_.summary as summary16_14_, sheet0_.template as templat17_14_, sheet0_.thumbnail as thumbna18_14_, sheet0_.title as title19_14_, sheet0_.top_priority as top_pri20_14_, sheet0_.url as url21_14_, sheet0_.visits as visits22_14_, sheet0_.word_count as word_co23_14_ from posts sheet0_ where sheet0_.type=1 [42102-197]
> 
> SheetRepositoryTest > listAllTest() FAILED
>     org.springframework.dao.InvalidDataAccessResourceUsageException at SheetRepositoryTest.java:27
>         Caused by: org.hibernate.exception.SQLGrammarException at SheetRepositoryTest.java:27
>             Caused by: org.h2.jdbc.JdbcSQLException at SheetRepositoryTest.java:27
> ```
> 
> 本地`test`成功截图（与master合并后）：
> ![image](https://user-images.githubusercontent.com/33995610/119618699-c43fed00-be35-11eb-801f-b455cf299670.png)

感谢您的报告！后续我会尽快解决测试的问题。

2021-06-08 03:14 UTC, JohnNiang commented
I'm going to approve and run the workflows.

2021-06-08 03:17 UTC, JohnNiang commented
@mimajiushi Thanks for your solution about DirtyContext. Please fix checkstyle conflict before we review the codes again.

2021-06-08 04:21 UTC, mimajiushi commented
> @mimajiushi Thanks for your solution about DirtyContext. Please fix checkstyle conflict before we review the codes again.

其实并没有修好，我先关掉吧

2021-06-10 06:24 UTC, mimajiushi commented
之前流水线失败感觉是`@DirtiesContext`引入的问题，去掉`@DirtiesContext`，改为原来的`catch (HttpClientErrorException.BadRequest e) {...}`

2021-06-10 11:30 UTC, JohnNiang commented
> 之前流水线失败感觉是`@DirtiesContext`引入的问题，去掉`@DirtiesContext`，改为原来的`catch (HttpClientErrorException.BadRequest e) {...}`

这可能没有解决实质性问题。理论上每一次测试后数据应该清理干净的。

2021-06-10 11:36 UTC, mimajiushi commented
> > 之前流水线失败感觉是`@DirtiesContext`引入的问题，去掉`@DirtiesContext`，改为原来的`catch (HttpClientErrorException.BadRequest e) {...}`
> 
> 这可能没有解决实质性问题。理论上每一次测试后数据应该清理干净的。

是的，但我在本地用`@DirtiesContext`无论如何都复现不了，可能是环境问题，这个或许可以留到以后再修复？目前用`try catch`应该不会造成历史债的风险

2021-06-20 03:15 UTC, closed without merging