feat: MarkDown supports footnote rendering
halo-dev/halo pull request #1406
Opened 2021-06-25 10:42 UTC by guqing

Creates footnote references in the document. Footnotes are placed at the bottom of the rendered document with links from footnote references to footnote

2021-06-25 10:45 UTC, JohnNiang commented
Please fix ci check first.

2021-06-25 10:51 UTC, guqing commented
> Please fix ci check first.

ok, later on

2021-06-26 16:53 UTC, guqing commented
可以审查了  适配markdown-it-footnote已解决

2021-06-27 01:21 UTC, JohnNiang requested changes
这是一个新的功能，建议在文档中加入相关的说明。

2021-06-27 01:21 UTC, JohnNiang commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
这里建议不要间接调用 FootnoteNodeRendererInterceptor 的方法，单元测试应该是直接调用需要测试的方法来进行验证。否则这些测试完全是对 MarkdownUtils 的测试。

2021-06-27 01:21 UTC, JohnNiang commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +    public void test() {
测试用例的名称需要细化，不建议使用 test、test1 之类的用例名。

2021-06-27 03:47 UTC, guqing commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
好的

2021-06-27 03:48 UTC, guqing commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +    public void test() {
好

2021-06-27 03:56 UTC, guqing commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
> 这里建议不要间接调用 FootnoteNodeRendererInterceptor 的方法，单元测试应该是直接调用需要测试的方法来进行验证。否则这些测试完全是对 MarkdownUtils 的测试。

好像没法能直接测试FootnoteNodeRenderIntercepter，它是对脚注渲染方法的委派，只有通过flexmark的render方法才能调用但它得到markdown的渲染结果

2021-06-27 04:00 UTC, guqing commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
或者我把测试类命名为MarkdownUtilsFootNoteTest？

2021-06-27 04:02 UTC, JohnNiang commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
你可以在 `FootnoteNodeRendererInterceptorTest` 中创造环境。

2021-06-27 04:03 UTC, guqing commented on src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
> +        String s = MarkdownUtils.renderHtml(markdown);
好的

2021-06-27 05:35 UTC, ruibaby commented
https://github.com/halo-dev/halo-editor

编辑器已经支持，你可以用来对比一下渲染后的效果。

2021-06-27 05:37 UTC, ruibaby requested changes

2021-06-27 05:37 UTC, ruibaby commented on src/main/java/run/halo/app/utils/MarkdownUtils.java
>              .set(TablesExtension.WITH_CAPTION, false)
你可能还得加上 `.set(FootnoteExtension.FOOTNOTE_BACK_REF_STRING,"↩️")` 配置。

参考：https://www.markdownguide.org/extended-syntax/#footnotes

2021-06-27 05:38 UTC, ruibaby commented on src/main/java/run/halo/app/utils/MarkdownUtils.java
>              .set(TablesExtension.WITH_CAPTION, false)
![image](https://user-images.githubusercontent.com/21301288/123534070-ec7c7d80-d74c-11eb-948d-90d1dfc8aa38.png)

2021-06-27 05:42 UTC, guqing commented on src/main/java/run/halo/app/utils/MarkdownUtils.java
>              .set(TablesExtension.WITH_CAPTION, false)
好

2021-06-27 07:19 UTC, ruibaby approved these changes

2021-06-27 07:19 UTC, ruibaby commented
LGTM

2021-06-27 07:44 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
> +public class FootnoteNodeRendererInterceptor {
请问这里除了使用 ByteBuddy 进行 hack，没有别的扩展的方法了么？

2021-06-27 07:49 UTC, guqing commented on src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
> +public class FootnoteNodeRendererInterceptor {
除了这种方式暂时没有好的办法 只有对flexmark的脚注扩展render规则进行改写才能匹配markdown-it的渲染结果 除此之外暂时只有复制这个扩展的代码到项目中改写 只是这样类文件会比较多

2021-06-29 03:48 UTC, ruibaby commented on src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
> +public class FootnoteNodeRendererInterceptor {
后续？

2021-06-29 04:11 UTC, guqing commented on src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
> +public class FootnoteNodeRendererInterceptor {
@JohnNiang

2021-06-29 04:28 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
> +public class FootnoteNodeRendererInterceptor {
LGTM

2021-06-29 05:27 UTC, merged