fix: fix visit bug #1381
halo-dev/halo pull request #1414
Opened 2021-07-07 11:13 UTC by zhixiangyuan

2021-07-07 11:46 UTC, guqing commented
你好 请先修复一下代码格式确保ci的code style能够检查通过

2021-07-07 13:35 UTC, JohnNiang commented
建议在 PR 的描述中关联 issue，例如：

```github
Fix #1381
Fix #1414
```

2021-07-08 01:58 UTC, zhixiangyuan commented
> 你好 请先修复一下代码格式确保ci的code style能够检查通过

好的， 我今天看下

2021-07-08 01:58 UTC, zhixiangyuan commented
> 建议在 PR 的描述中关联 issue，例如：
> 
> ```
> Fix #1381
> Fix #1414
> ```

好的

2021-07-09 06:27 UTC, mimajiushi commented
好奇测试代码要怎么解决

2021-07-09 08:00 UTC, guqing commented
对于回收站的文章访问时现在返回的是403页面`您没有该文章的访问权限` 我认为回收站的文章应该是404，文章不存在, @JohnNiang @ruibaby 你们怎么看

2021-07-11 03:47 UTC, ruibaby commented
> 对于回收站的文章访问时现在返回的是403页面`您没有该文章的访问权限` 我认为回收站的文章应该是404，文章不存在, @JohnNiang @ruibaby 你们怎么看

我认为应该是404

2021-07-11 03:59 UTC, guqing commented
> > 对于回收站的文章访问时现在返回的是403页面`您没有该文章的访问权限` 我认为回收站的文章应该是404，文章不存在, @JohnNiang @ruibaby 你们怎么看
> 
> 我认为应该是404，只要不是公开的，都应该是 404。
@zhixiangyuan 感谢你的贡献 经过讨论 我们认为对于访问不到的文章应该返回404页面目前返回的是403  需要对此做出一些修改

2021-07-11 06:48 UTC, zhixiangyuan commented
> > > 对于回收站的文章访问时现在返回的是403页面`您没有该文章的访问权限` 我认为回收站的文章应该是404，文章不存在, @JohnNiang @ruibaby 你们怎么看
> > 
> > 
> > 我认为应该是404，只要不是公开的，都应该是 404。
> > @zhixiangyuan 感谢你的贡献 经过讨论 我们认为对于访问不到的文章应该返回404页面目前返回的是403  需要对此做出一些修改

再看下，改过了

2021-07-11 06:54 UTC, guqing commented
> > > > 对于回收站的文章访问时现在返回的是403页面`您没有该文章的访问权限` 我认为回收站的文章应该是404，文章不存在, @JohnNiang @ruibaby 你们怎么看
> > > 
> > > 
> > > 我认为应该是404，只要不是公开的，都应该是 404。
> > > @zhixiangyuan 感谢你的贡献 经过讨论 我们认为对于访问不到的文章应该返回404页面目前返回的是403  需要对此做出一些修改
> 
> 再看下，改过了

好的 我们会尽快review

2021-07-11 08:34 UTC, JohnNiang requested changes

2021-07-11 08:34 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
推荐用以下方式重写：

```java
        if (PostStatus.RECYCLE.equals(post.getStatus())
            || PostStatus.DRAFT.equals(post.getStatus())) {
            throw new NotFoundException("查询不到该文章的信息");
        }

        if (PostStatus.INTIMATE.equals(post.getStatus())
            && !authenticationService.postAuthentication(post, null)
        ) {
            // Encrypted articles must has the correct password before they can be accessed.
            model.addAttribute("slug", post.getSlug());
            model.addAttribute("type", EncryptTypeEnum.POST.getName());
            if (themeService.templateExists(POST_PASSWORD_TEMPLATE + SUFFIX_FTL)) {
                return themeService.render(POST_PASSWORD_TEMPLATE);
            }
            return "common/template/" + POST_PASSWORD_TEMPLATE;
        }

        if (StrUtil.isNotEmpty(token)) {
            // If the token is not empty, it means it is an admin request,
            // then verify the token.

            // verify token
            String cachedToken = cacheStore.getAny(token, String.class)
                .orElseThrow(() -> new ForbiddenException("您没有该文章的访问权限"));
            if (!cachedToken.equals(token)) {
                throw new ForbiddenException("您没有该文章的访问权限");
            }
        }
```

2021-07-12 02:02 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
这样写的好处是什么？

2021-07-12 02:30 UTC, guqing commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
逻辑更清晰 嵌套少可读性更强 当写为 if(RECYCLE||DRAFT) 的情况下只有RECYCLE判断为false才会继续判断DRAFT否则直接执行if，因此不存在多次判断

2021-07-12 04:16 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
先说下多次判断的地方，博客大部分访问都是公开类型的文章，所以按照目前的写法判断是公开类型的文章则走 empty body 直接就到后面获取文章内容去了，如果改成多个 if，那么对于访问公开文章的请求首先判断类型是不是 RECYCLE，然后再判断类型是不是 DRAFT，接下来再判断类型是不是 INTIMATE，然后再验证有没有 token，按照我的理解一个公开文章的访问没必要判断这么多次。
另外这里 RECYCLE 和 DRAFT 分开判断是有含义的，如果你把这两个文章类型合在一起判断，那么当你点击文章预览的时候，草稿文章依然会给你报 NotFoundException，所以这里对  DRAFT 的类型判断需要放到 token 验证后面。

2021-07-12 04:40 UTC, guqing commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
我们认为empty body是不应该出现的操作，即使它会有意义我们也不推荐，它会让人觉得困惑和难以理解，为此可以牺牲一一点点的性能，后续我们会在check style中增加对emtpy body的检查

2021-07-12 05:39 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
A1. 在这里，代码的可读性比所谓的性能可能更重要；

A2. 这里我可能没有理解到这么深刻，不过你完全可以拆开；

A3. 前两个 if 确实可以用if else 来替代，没必要判断两次 status。

2021-07-12 08:14 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
既然觉得性能不重要那我就把 PUBLISH 的校验删掉，但是后面的 if else 我认为是没有问题的，你们可以把代码拉下去改成现在贴的建议代码试试，你会发现如果拆成几个单独的 if，草稿文章的预览功能会始终是 404

2021-07-12 08:28 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
Hi @zhixiangyuan ，我们并不是觉得性能不重要，几个 if 影响微乎其微，甚至可以忽略。非常欣慰你能够对该建议进行验证，提出质疑并提供理由。这无伤大雅，我们接受这样的 style。

2021-07-12 08:29 UTC, JohnNiang commented
LGTM

2021-07-12 08:48 UTC, guqing approved these changes

2021-07-12 09:11 UTC, zhixiangyuan commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
👌改完了

2021-07-12 09:13 UTC, guqing approved these changes

2021-07-12 09:14 UTC, guqing commented
LGTM

2021-07-12 09:14 UTC, guqing commented on src/main/java/run/halo/app/controller/content/model/PostModel.java
> +        if (PostStatus.PUBLISHED.equals(post.getStatus())) {
感谢你的贡献 我们会尽快合并

2021-07-12 09:20 UTC, ruibaby approved these changes

2021-07-12 10:55 UTC, merged