feat: support thymeleaf template
halo-dev/halo pull request #1442
Opened 2021-07-29 09:59 UTC by chuntungho

Available theme in thymeleaf: 
https://github.com/chuntungho/casper-halo

2021-07-29 13:21 UTC, JohnNiang commented
hi @chuntungho ，首先非常改写你 PR。

这个功能我们确实很早之前就想支持了，不过一直在等插件机制完成后才开始动作。后续我们会对这个功能进行详细的考量，并给出意见和建议。

2021-08-01 14:38 UTC, JohnNiang commented
hi, @ruibaby @guqing @LIlGG, please take some moment to have a test.

2021-08-02 05:56 UTC, LIlGG requested changes
非常感谢您的 PR，目前经过我审阅，发现存在如下的问题，希望能够共同更正。

2021-08-02 05:56 UTC, LIlGG commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +                String imagePath = imgUrl(requestPath, size);
这里拼接图片 size 参数是有什么具体含义吗？看起来前端也应该可以做到，我认为不应该让后端来处理这个。且按照上下文理解，这样做会导致所有模板都执行这样的操作

2021-08-02 05:56 UTC, LIlGG commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +    FreeMarkerConfigurer freeMarkerConfigurer(ApplicationContext context,
freemarker 的配置应当与 thymeleaf 写到不同的文件，如果未来需要支持其他的模板。
例如 https://github.com/halo-dev/halo/blob/6a84483b156032b47dc6eba4be4972aaf01b4cee/src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java#L80

2021-08-02 05:56 UTC, LIlGG commented on src/main/java/run/halo/app/service/impl/MenuServiceImpl.java
> +        publishUpdateEvent();
是否有更好的做法？例如使用 AOP？否则目前的事件监听对原有代码的侵入性过大

2021-08-02 05:56 UTC, LIlGG commented on src/main/resources/application.yaml
> +    suffix: .html
后缀最好固定不允许用户随意修改，另外如果确定使用 html 后缀，则应该在 https://github.com/halo-dev/halo/blob/6a84483b156032b47dc6eba4be4972aaf01b4cee/src/main/java/run/halo/app/service/ThemeService.java#L29
内加入 .html，使其可编辑

2021-08-02 05:56 UTC, LIlGG commented on src/main/java/run/halo/app/theme/ThemeManager.java
> +        viewResolver.addStaticVariable("options", optionService.listOptions());
还需要一些其他的静态变量，可以参考一下 https://github.com/halo-dev/halo/blob/6a84483b156032b47dc6eba4be4972aaf01b4cee/src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java#L135

2021-08-02 10:51 UTC, chuntungho commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +                String imagePath = imgUrl(requestPath, size);
用于加载自适应图片，当静态文件后添加size参数，如abc.jpg?size=m，将路径改写为abc-m.jpg
https://medium.freecodecamp.org/a-guide-to-responsive-images-with-ready-to-use-templates-c400bd65c433

2021-08-02 10:56 UTC, chuntungho commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +    FreeMarkerConfigurer freeMarkerConfigurer(ApplicationContext context,
这个主意很好，我将thymeleaf配置文件抽离出来了，freemarker配置了解不深，尚未合并原来的配置

2021-08-02 11:00 UTC, chuntungho commented on src/main/java/run/halo/app/service/impl/MenuServiceImpl.java
> +        publishUpdateEvent();
可以考虑 JPA Auditing，@EnableJpaAuditing, @EntityListeners

2021-08-02 11:56 UTC, chuntungho commented on src/main/resources/application.yaml
> +    suffix: .html
已添加html至可编辑列表，文件编辑后需清理缓存

2021-08-02 14:36 UTC, ruibaby commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +                String imagePath = imgUrl(requestPath, size);
我们现在有支持这样的特性吗？

2021-08-02 15:16 UTC, LIlGG commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +                String imagePath = imgUrl(requestPath, size);
> 我们现在有支持这样的特性吗？

目前来说应该没有这样实现的，基本都是前端实现，例如如果我的主题开启了随机图，就支持自适应图，所以应该是可以前端实现的。

2021-08-03 01:17 UTC, chuntungho commented on src/main/java/run/halo/app/config/ThemeConfiguration.java
> +                String imagePath = imgUrl(requestPath, size);
这个功能比较特例，还是移除吧

2021-08-14 06:56 UTC, ruibaby commented on src/main/java/run/halo/app/config/theme/ThemeConfiguration.java
> +                registry.addResourceHandler("/assets/**", "/source/**")
这里需要讨论一下，如何兼容目前的情况。

方向是没有问题的，确实需要限制可映射的目录。

2022-01-06 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1442) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1442) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1442) it.</sub>

2022-04-18 03:58 UTC, ruibaby commented
感谢你的参与，但由于我们没有对此 PR 进行后续响应，1.5.x 也已经暂无新特性打算，如果后续对此特性有兴趣可以在 2.0 的时候参与。这个 PR 就先关闭了。

/close

2022-04-18 03:58 UTC, closed without merging