fix: 1547
halo-dev/halo pull request #1549
Opened 2021-11-29 08:39 UTC by guqing

## What this PR does?
修复 Halo 启动时拷贝默认主题没有使用themeId作为主题文件夹名称的问题

## Why we need it?
启动时拷贝默认主题应使用themeId以避免主题在线更新后文件夹名称不一致导致部分文件无法获取

## How to test it?
删除`halo work dir`下的默认主题`anatole`,然后启动`halo`查看默认主题文件夹名称是否为`caicai_anatole`
点击在线更新或上传该主题的更新包查看主题文件夹名称是否一致，同为`caicai_anatole`

2021-11-30 11:30 UTC, ruibaby requested changes

2021-11-30 11:30 UTC, ruibaby commented on src/main/java/run/halo/app/listener/StartedListener.java
> +                FileUtils.copyFolder(source.resolve("anatole"), themePath);
建议定义成常量。

2021-11-30 12:13 UTC, guqing commented on src/main/java/run/halo/app/listener/StartedListener.java
> +                FileUtils.copyFolder(source.resolve("anatole"), themePath);
ok

2021-12-03 02:20 UTC, ruibaby approved these changes

2021-12-03 02:21 UTC, merged