Tag support color options
halo-dev/halo pull request #1566
Opened 2021-12-03 06:15 UTC by guqing

## What this PR does?
标签支持设置颜色，颜色字段为非必填 默认值为 `#52c41a`, 为了返回值客户端统一默认颜色所以`TagDTO`的color字段默认值也为`#52c41a`

## Why we need it?
#1559

2021-12-04 07:58 UTC, ruibaby approved these changes

2021-12-04 10:38 UTC, JohnNiang requested changes

2021-12-04 10:38 UTC, JohnNiang commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
建议加上注释：颜色的命名规则，可以给出几个 example。

2021-12-04 10:43 UTC, JohnNiang commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
如果颜色仅支持 `#11111`的话，建议自定义 Constraint（类似于 `@Size`），并应用到该字段。

2021-12-04 11:03 UTC, guqing commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
颜色应该是16进制和rgba都支持吧 @ruibaby @johnniang

2021-12-04 11:03 UTC, guqing commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
> 建议加上注释：颜色的命名规则，可以给出几个 example。

好的

2021-12-04 16:39 UTC, JohnNiang commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
我看到颜色字段最大长度为 20，可以提供一下理由么？

可以参考 color 定义：
- https://en.wikipedia.org/wiki/Web_colors#CSS_colors
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

2021-12-04 17:08 UTC, guqing commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
对于RGBA 255,255,255,0.5是15位 如果逗号后允许跟空格最大18位 如果允许加（）是20位 所以给了最大的20

2021-12-04 17:10 UTC, guqing commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    private String color;
hi @johnniang, 对于RGBA 255,255,255,0.5是15位 如果逗号后允许跟空格最大18位 如果允许加（）是20字符位 所以给了最大的20

2021-12-05 01:55 UTC, JohnNiang commented on src/main/java/run/halo/app/model/entity/Tag.java
> +    @Column(name = "color", length = 20)
I found a color, the name is `lightgoldenrodyellow`, and the length is exactly 20
我在[这里](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)找到一个颜色，名为`lightgoldenrodyellow`，长度为 20，数据库字段的长度最少得 21 才能容纳这个值。

2021-12-05 03:48 UTC, guqing commented on src/main/java/run/halo/app/model/entity/Tag.java
> +    @Column(name = "color", length = 20)
> 我在[这里](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)找到一个颜色，名为`lightgoldenrodyellow`，长度为 20，数据库字段的长度最少得 21 才能容纳这个值。

那我改为25吧  考虑到rgba 允许小数时24的长度

2021-12-05 08:12 UTC, JohnNiang commented on src/main/java/run/halo/app/model/entity/Tag.java
> +    @Column(name = "color", length = 20)
Make sense to me.

2021-12-05 10:08 UTC, JohnNiang requested changes

2021-12-05 10:08 UTC, JohnNiang commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    @Size(max = 20, message = "颜色值字符长度不能超过 {max}")
Please update the max size to 24.

2021-12-05 12:49 UTC, guqing commented on src/main/java/run/halo/app/model/params/TagParam.java
> +    @Size(max = 20, message = "颜色值字符长度不能超过 {max}")
oh sorry I  I forgot

2021-12-06 04:37 UTC, JohnNiang approved these changes
LGTM

2021-12-06 04:38 UTC, merged