Fix security warning of log4j 0-day
halo-dev/halo pull request #1588
Opened 2021-12-10 16:52 UTC by guqing

### What this PR does?
对齐 gradle 中 log4j 的依赖版本 到 2.15.0 以解决 log4j 0-day 安全漏洞
参考 [gradle文档](https://docs.gradle.org/7.0/userguide/dependency_version_alignment.html)

最终对其后的依赖效果如下：

```shell
$ ./gradlew dependencies | grep log4j                                                                        
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- org.apache.logging.log4j:log4j-api:2.8.2 -> 2.15.0 (*)
+--- org.apache.logging.log4j:log4j-core:2.15.0 (n)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (n)
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- org.apache.logging.log4j:log4j-api:2.8.2 -> 2.15.0 (*)
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- org.apache.logging.log4j:log4j-api:2.8.2 -> 2.15.0 (*)
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- org.apache.logging.log4j:log4j-api:2.8.2 -> 2.15.0 (*)
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- org.apache.logging.log4j:log4j-api:2.8.2 -> 2.15.0 (*)

```
### Whay we need it?
在广泛使用的 Java 日志库 Apache Log4j 中新发现的 0-day 漏洞很容易被利用，并使攻击者能够完全控制受影响的服务器。
该漏洞被跟踪为[CVE-2021-44228](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228)，被归类为严重漏洞，允许未经身份验证的远程代码执行。

### How to test it?
拉取该PR到本地运行后都点击一下看是否有功能不可用

2021-12-11 01:58 UTC, JohnNiang reviewed
目前这些都是临时方案，不过我建议先找出依赖 log4j-core 的依赖，方便后续升级对应的依赖并去掉该临时方案。

参考：
- https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot

2021-12-11 02:00 UTC, JohnNiang commented
```bash
╰─⠠⠵ ./gradlew dependencyInsight --dependency log4j-core
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :dependencyInsight
org.apache.logging.log4j:log4j-core:2.14.1 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.environment     = standard-jvm
         org.gradle.jvm.version         = 11
   ]

org.apache.logging.log4j:log4j-core:2.8.2 -> 2.14.1
\--- com.huaweicloud:esdk-obs-java:3.19.7
     \--- compileClasspath
```

2021-12-11 02:10 UTC, guqing commented
> ```shell
> ╰─⠠⠵ ./gradlew dependencyInsight --dependency log4j-core
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Task :dependencyInsight
> org.apache.logging.log4j:log4j-core:2.14.1 (selected by rule)
>    variant "compile" [
>       org.gradle.status              = release (not requested)
>       org.gradle.usage               = java-api
>       org.gradle.libraryelements     = jar (compatible with: classes)
>       org.gradle.category            = library
> 
>       Requested attributes not found in the selected variant:
>          org.gradle.dependency.bundling = external
>          org.gradle.jvm.environment     = standard-jvm
>          org.gradle.jvm.version         = 11
>    ]
> 
> org.apache.logging.log4j:log4j-core:2.8.2 -> 2.14.1
> \--- com.huaweicloud:esdk-obs-java:3.19.7
>      \--- compileClasspath
> ```

huaweioss这个包是没有覆盖掉的吗

2021-12-11 02:17 UTC, guqing commented
> 

这些方法昨晚都试了没生效  然后用了gradle的这个

2021-12-11 02:33 UTC, JohnNiang commented
> > 
> 
> 这些方法昨晚都试了没生效 然后用了gradle的这个

你提供的方法可以正常工作。我的意思是，找出依赖 log4j-core 的依赖，方便后续升级对应的依赖，并移除这种临时方案。

参考：
- https://github.com/huaweicloud/huaweicloud-sdk-java-obs/pull/67#issuecomment-991411910
- https://github.com/huaweicloud/huaweicloud-sdk-java-obs/pull/65#issuecomment-991415660

2021-12-11 02:34 UTC, JohnNiang requested changes

2021-12-11 02:34 UTC, JohnNiang commented on build.gradle
> +    implementation enforcedPlatform("org.apache.logging.log4j:log4j-api:2.15.0")
```suggestion
    implementation enforcedPlatform("org.apache.logging.log4j:log4j-api:$log4jVersion")
```

2021-12-11 02:35 UTC, guqing commented
> > > 
> > 
> > 
> > 这些方法昨晚都试了没生效 然后用了gradle的这个
> 
> 你提供的方法可以正常工作。我的意思是，找出依赖 log4j-core 的依赖，方便后续升级对应的依赖，并移除这种临时方案。
> 
> 参考：
> 
> * [Bump log4j-core from 2.13.3 to 2.15.0 in /app huaweicloud/huaweicloud-sdk-java-obs#67 (comment)](https://github.com/huaweicloud/huaweicloud-sdk-java-obs/pull/67#issuecomment-991411910)
> * [Bump log4j-core from 2.13.2 to 2.15.0 huaweicloud/huaweicloud-sdk-java-obs#65 (comment)](https://github.com/huaweicloud/huaweicloud-sdk-java-obs/pull/65#issuecomment-991415660)

好的

2021-12-11 03:14 UTC, ruibaby approved these changes
LGTM

2021-12-12 01:50 UTC, JohnNiang approved these changes

2021-12-12 01:50 UTC, merged