[WIP] Split post content to new table and support content version control
halo-dev/halo pull request #1617
Opened 2022-01-08 10:19 UTC by guqing

### What this PR does?
- 将文章内容从文章表中拆分出去
- 增加文章内容版本表用来存储内容版本增量记录
- 修改原有文章编辑逻辑后台编辑时不影响前台预览，只有发布后才能再前台展示最新内容

### Why we need it?
#1587

2022-02-17 08:48 UTC, ruibaby requested changes

2022-02-17 08:48 UTC, ruibaby commented on src/main/resources/migration/V6__migrate_split_content_to_content_table.sql
> +-- Migrate post content to contents table
文件名可以直接叫 `V6_migrate_create_contents_table`

2022-02-17 08:48 UTC, ruibaby commented on src/main/java/run/halo/app/model/dto/post/BasePostSimpleDTO.java
> +    private Boolean isInProcess;
`inProcess` 应该就可以表达状态

2022-02-17 08:48 UTC, ruibaby commented on src/main/java/run/halo/app/service/base/BaseContentPatchLogService.java
> +    void save(ContentPatchLog contentPatchLog);
doc 注释

2022-02-17 08:49 UTC, ruibaby commented
cc @JohnNiang

2022-02-17 09:00 UTC, ruibaby commented
<img width="787" alt="image" src="https://user-images.githubusercontent.com/21301288/154441275-d4ce59d3-fe2b-448e-9ee5-d9aefb4791a0.png">

RSS 没有输出内容。

2022-02-17 10:07 UTC, guqing commented
> <img alt="image" width="787" src="https://user-images.githubusercontent.com/21301288/154441275-d4ce59d3-fe2b-448e-9ee5-d9aefb4791a0.png">
> 
> RSS 没有输出内容。

ok got it

2022-02-19 10:17 UTC, guqing commented
测试索引时发现 contents 表中的type字段没有用到，于是发现不需要这个字段，因为contents表的主键id设计为使用posts表的主键id，所以不需要像 post 和 sheet 共用表那样写，直接用一个 Content entity + ContentRespoitory + ContentService即可存储post和sheet的内容，于是 [commit#351d5c](https://github.com/halo-dev/halo/pull/1617/commits/351d5c8de84adb11a4812806f98006fe201103b5) 用来优化此项发现，简化了300多行代码

2022-02-19 10:18 UTC, guqing commented
@ruibaby @JohnNiang ready for review

2022-02-19 12:09 UTC, JohnNiang requested changes

2022-02-19 12:09 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/ContentServiceImpl.java
> +    public void createOrUpdateDraftBy(Integer postId, String content,
这里是不是需要用事务来保证服务的原子性呢？

2022-02-19 12:10 UTC, JohnNiang reviewed
缺乏一些必要的单元测试，尤其是新增的 Content 部分。

2022-02-19 13:16 UTC, guqing commented on src/main/java/run/halo/app/model/entity/Content.java
> +    public boolean equals(Object o) {
没有特殊用途 我记得好像是因为用了lombok的 idea提示让我手动重写😂

2022-02-19 13:17 UTC, guqing commented on src/main/java/run/halo/app/service/impl/ContentServiceImpl.java
> +    public void createOrUpdateDraftBy(Integer postId, String content,
是的  忘记加了👍

2022-02-20 01:11 UTC, JohnNiang commented on src/test/java/run/halo/app/repository/ContentPatchLogRepositoryTest.java
> +@Sql("classpath:content-patch-logs.sql")
不是特别推荐用大量的 SQL 来作为测试数据的准备，可维护性较差。尤其是未来表结构可能变更，或者添加新的测试用例。

推荐使用 EntityManager （通过 Autowired 注解注入）来创建需要的数据。

> 这个建议不会阻止这个 PR 的合并。

2022-02-20 02:46 UTC, JohnNiang commented
@guqing 文章的描述似乎丢失了，请看图片：
![image](https://user-images.githubusercontent.com/16865714/154826349-e7e8c1c1-0896-4cec-b79e-40d19623072a.png)

2022-02-20 04:06 UTC, guqing commented
> @guqing 文章的描述似乎丢失了，请看图片：
> ![image](https://user-images.githubusercontent.com/16865714/154826349-e7e8c1c1-0896-4cec-b79e-40d19623072a.png)
> 

@JohnNiang 如何操作的呢

2022-02-20 06:52 UTC, JohnNiang commented
> @guqing 文章的描述似乎丢失了，请看图片： ![image](https://user-images.githubusercontent.com/16865714/154826349-e7e8c1c1-0896-4cec-b79e-40d19623072a.png)

Hi @guqing ，左侧是基于 master 分支初始化博客，右侧则是基于当前 PR 初始化博客的结果。

2022-02-20 08:57 UTC, guqing commented
> Hi @guqing ，左侧是基于 master 分支初始化博客，右侧则是基于当前 PR 初始化博客的结果。

<img width="306" alt="image" src="https://user-images.githubusercontent.com/38999863/154835463-5cf9dc68-eb99-4b3d-9fdf-8e7042a50887.png">

2022-02-20 10:28 UTC, ruibaby approved these changes

2022-02-20 12:32 UTC, JohnNiang approved these changes

2022-02-20 12:34 UTC, merged