perf: add password reset field verification
halo-dev/halo pull request #1636
Opened 2022-01-24 05:15 UTC by ruibaby

添加重置密码接口的字段验证。

Close #1608 

Signed-off-by: Ryan Wang <i@ryanc.cc>

2022-01-24 06:06 UTC, guqing approved these changes

2022-01-24 06:13 UTC, JohnNiang requested changes
Hold on. I'm going to add a controller test against this change.

2022-01-24 06:14 UTC, JohnNiang requested changes
Hold on. I'm going to add a controller test against this change.

2022-02-11 09:44 UTC, guqing approved these changes

2022-02-16 12:31 UTC, JohnNiang commented
Sorry for the delay. I'm going to review those changes.

2022-02-16 12:35 UTC, JohnNiang requested changes

2022-02-16 12:35 UTC, JohnNiang commented on src/test/java/run/halo/app/controller/AdminControllerTest.java
> +@ExtendWith(MockitoExtension.class)
If we just test controller only, please refer to https://docs.spring.io/spring-boot/docs/2.5.9/reference/html/features.html#features.testing.spring-boot-applications.spring-mvc-tests

2022-02-16 12:35 UTC, JohnNiang commented on src/test/java/run/halo/app/controller/AdminControllerTest.java
> +    public static class MockAdminService implements AdminService {
No need to create a blank AdminService.

2022-02-16 13:37 UTC, JohnNiang commented on src/test/java/run/halo/app/controller/AdminControllerTest.java
> +    public static class MockAdminService implements AdminService {
Please be aware of that this is a test for AdminController, not only for parameter verification.

2022-02-18 02:48 UTC, ruibaby commented
/cc @JohnNiang

2022-02-20 02:30 UTC, JohnNiang commented on src/test/java/run/halo/app/controller/AdminControllerTest.java
> +    public static class MockAdminService implements AdminService {
This issue won't block this PR from merging. Anyway, we are supposed to consider optimizing unit-test experience later.

2022-02-20 02:30 UTC, JohnNiang approved these changes

2022-02-20 02:30 UTC, merged