feat: 分类增加排序字段
halo-dev/halo pull request #1650
Opened 2022-02-14 10:11 UTC by lan-yonghui

2022-02-14 10:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1650) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1650) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1650) it.</sub>

2022-02-14 13:04 UTC, JohnNiang commented
Hi @lan-yonghui , Thanks for your contribution!

Please repair all failed tests before we review.

2022-02-15 02:29 UTC, ruibaby requested changes

2022-02-15 02:29 UTC, ruibaby commented on src/main/java/run/halo/app/model/entity/Category.java
> +    private Integer sort;
建议使用和 Menu 一致的字段名。`priority`

https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/model/entity/Menu.java#L52

2022-02-15 02:29 UTC, ruibaby commented on src/main/resources/migration/V6__migrate_alter_sort_in_categries_table.sql
> +ALTER TABLE `categories` modify `sort` int NULL COMMENT '排序';
增加字段似乎不需要数据库脚本。

2022-02-15 02:29 UTC, ruibaby commented on src/main/java/run/halo/app/model/params/CategoryParam.java
> +    private Integer sort = 100;
默认为 0 即可。

2022-02-15 04:40 UTC, lan-yonghui commented on src/main/java/run/halo/app/model/params/CategoryParam.java
> +    private Integer sort = 100;
默认为0不便于后面增加分类的调整

2022-02-15 04:44 UTC, ruibaby commented on src/main/java/run/halo/app/model/params/CategoryParam.java
> +    private Integer sort = 100;
增加分类在后台保存分类的时会自动从 0 开始排序，就和目前的菜单一样。

2022-02-15 06:53 UTC, ruibaby approved these changes
LGTM

2022-02-15 07:04 UTC, guqing approved these changes

2022-02-15 09:02 UTC, JohnNiang reviewed
@ruibaby @guqing 麻烦测试一下从旧版本升级上来是否正常。

2022-02-15 09:50 UTC, ruibaby commented
> @ruibaby @guqing 麻烦测试一下从旧版本升级上来是否正常。

没有问题。

2022-02-15 09:50 UTC, merged