fix: minio 依赖中 okhttp 版本过低
halo-dev/halo pull request #1666
Opened 2022-02-20 05:04 UTC by JarvisPongSky

2022-02-20 05:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1666) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1666) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1666) it.</sub>

2022-02-20 06:38 UTC, JohnNiang requested changes
Hi @JarvisPongSky ,我们推荐回退 minio-java 依赖版本，毕竟我们还没有使用 minio-java 高版本特性的场景，这里贸然升级 okhttp3，可能会对 Spring Boot 依赖造成潜在的影响。等后续 Spring Boot 官方升级了 okhttp3 的版本后，我们再考虑升级 minio-java。

请参考：
- https://github.com/halo-dev/halo/pull/1602
- https://docs.spring.io/spring-boot/docs/2.5.9/reference/html/dependency-versions.html

2022-02-23 03:14 UTC, ruibaby commented
@JarvisPongSky 你好，请问此 PR 还在继续吗？

2022-02-23 03:16 UTC, JarvisPongSky commented
结束了，就提交了一次。

2022-02-23 03:27 UTC, JohnNiang commented
> 结束了，就提交了一次。

Hi @JarvisPongSky , 没必要关闭这个 PR，你可以继续在当前分支上修改代码，然后执行代码推送操作。前提是你采纳我的观点：https://github.com/halo-dev/halo/pull/1666#pullrequestreview-887995079

2022-02-23 03:30 UTC, JarvisPongSky commented
啊哈，GitHub 多人协助不是很熟练，见谅，[#1666 review](https://github.com/halo-dev/halo/pull/1666#pullrequestreview-887995079) 我觉得这个观点是对的，后续更改 minio 版本进行测试，再进行提交。

2022-02-23 03:34 UTC, JohnNiang commented
> 啊哈，GitHub 多人协助不是很熟练，见谅，[#1666 review](https://github.com/halo-dev/halo/pull/1666#pullrequestreview-887995079) 我觉得这个观点是对的，后续更改 minio 版本进行测试，再进行提交。

期待进一步的 commit。

2022-02-23 05:49 UTC, ruibaby commented
@JarvisPongSky 你好，我们需要 sign 一下 CLA，否则我们无法合并此 PR。

https://github.com/halo-dev/halo/pull/1666#issuecomment-1046163996

2022-02-25 12:44 UTC, JarvisPongSky commented
@ruibaby 你好，我已签署 Google CIA，要怎么配合你 sign 呢？

2022-02-25 12:46 UTC, JohnNiang commented
Hi @JarvisPongSky , 

1. 你可以点击这里：

    ![image](https://user-images.githubusercontent.com/16865714/155717337-6c127aec-323b-40a1-a13b-3690a8ebd331.png)

2. 或者直接访问：<https://cla-assistant.io/halo-dev/halo?pullRequest=1666>

签署 License CLA。

2022-02-25 12:48 UTC, JarvisPongSky commented
@ruibaby 感谢您的引导，我已完成，现在我将测试 minio 低版本兼容的情况。

2022-02-25 13:13 UTC, JarvisPongSky commented
@ruibaby 您好，我查阅了 [minio-java](https://github.com/minio/minio-java)  build.gradle ，获悉自从 `7.1.4` version 以后，`okhttp` 依赖已升级至  `4.8.1` version，所以将 minio version 回滚至 `7.1.4` 是一个安全的版本。

代码已提交，后续我将 close 该 PR 吗？还是等待您的指示？（我是小白，见谅😖）

2022-02-25 13:24 UTC, JohnNiang approved these changes
LGTM

2022-02-25 13:24 UTC, merged

2022-02-25 13:26 UTC, guqing commented
> @ruibaby 您好，我查阅了 [minio-java](https://github.com/minio/minio-java)  build.gradle ，获悉自从 `7.1.4` version 以后，`okhttp` 依赖已升级至  `4.8.1` version，所以将 minio version 回滚至 `7.1.4` 是一个安全的版本。
> 
> 代码已提交，后续我将 close 该 PR 吗？还是等待您的指示？（我是小白，见谅😖）

等待我们测试后会处理 不需要你关闭👍

2022-02-25 13:27 UTC, JarvisPongSky commented
@guqing 好的，谢谢您 😃

2022-02-25 13:29 UTC, guqing commented
该 PR 已经完成 感谢你的贡献👏👏 期待你的下次贡献🎉🎉