Refactor post and cateogry authentication
halo-dev/halo pull request #1678
Opened 2022-02-25 06:37 UTC by guqing

### What this PR does?
- 重构文章和分类的加密认证逻辑
- 不在CategoryServcice做过滤和认证逻辑，有需要也应该使用Facade
- 增加AuthenticationManager做认证
- 增加Category和Post的Authentication做认证状态管理

业务规则：
- 对于没有加密但父分类为加密状态的分类也为加密状态，访问密码为第一个父分类密码
- 文章关联了加密分类则文章也为加密状态默认密码为空
- 文章同时关联了多个加密分类，通过输入密码访问了文章详情后可以看到所有加密分类的名称但点击访问加密分类依然需要输入密码
- 通过content api根据分类获取分类文章列表时,如果该分类不是私密分类则所属该分类的私密文章不会出现在列表，如果该分类是加密分类且认证过则会查询出私密文章，如果分类是私密分类且该请求携带分类密码请求（查询时认证），认证通过也会查询私密分类，否则私密文章不会出现在列表

### Why we need it?
#1673

2022-02-25 08:56 UTC, ruibaby requested changes
测试发现，子分类的父分类如果有密码的情况下，子分类虽然会被拦截需要输入密码，但可以随意输入密码进入。

2022-02-25 11:38 UTC, guqing commented
> 测试发现，子分类的父分类如果有密码的情况下，子分类虽然会被拦截需要输入密码，但可以随意输入密码进入。

done

2022-02-25 12:44 UTC, JohnNiang commented
> 测试发现，子分类的父分类如果有密码的情况下，子分类虽然会被拦截需要输入密码，但可以随意输入密码进入。

@guqing 建议添加一个测试用例保证以上问题不会再出现。

2022-02-25 12:53 UTC, guqing commented
> > 测试发现，子分类的父分类如果有密码的情况下，子分类虽然会被拦截需要输入密码，但可以随意输入密码进入。
> 
> @guqing 建议添加一个测试用例保证以上问题不会再出现。

好的

2022-03-01 02:45 UTC, ruibaby commented
@halo-dev/sig-halo

2022-03-01 03:14 UTC, JohnNiang approved these changes
LGTM

2022-03-01 05:32 UTC, ruibaby approved these changes
LGTM

2022-03-01 05:32 UTC, merged