Create project infrastructure for halo-next
halo-dev/halo pull request #1699
Opened 2022-03-03 10:18 UTC by guqing

### What this PR does?
1. 创建halo-next的基础结构，提供了包括gradle配置和application.yaml配置在内的一些信息
2. flyway提供了对在h2、mysql、postgresql之前切换的migrate目录并经过了可行性验证
3. checkstyle升级到最新版

将在下一个PR创建包结构和提供测试示例

参考文档：
 - postgresql连接配置文档：https://jdbc.postgresql.org/documentation/80/connect.html
 - 使用docker创建postgresql
```shell
docker run -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=123456 postgres
```
- SpringBoot: https://docs.spring.io/spring-boot/docs/2.6.4/reference/htmlsingle/#features.spring-application
- SpringBoot 3.0.0-m1迁移文档: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes
- SpringBoot 3.0.0-m1 configuration properties变更文档: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Configuration-Changelog

### Why we need it?
配置基础结构以方便开发halo-next

2022-03-03 11:21 UTC, ruibaby approved these changes
LGTM

2022-03-03 14:11 UTC, JohnNiang requested changes

2022-03-03 14:12 UTC, JohnNiang commented on build.gradle
> +sourceCompatibility = JavaVersion.VERSION_11
Java 版本得提升至 17。

2022-03-04 05:12 UTC, ruibaby approved these changes

2022-03-04 06:11 UTC, JohnNiang requested changes

2022-03-04 06:11 UTC, JohnNiang commented on build.gradle
> +        h2: '2.1.210',
看看能否通过覆盖 `h2.version` 来覆盖 h2 依赖。

可参考：https://docs.spring.io/spring-boot/docs/3.0.0-M1/reference/html/dependency-versions.html#dependency-versions.properties

2022-03-04 06:11 UTC, JohnNiang commented on build.gradle
> +        springDoc: '1.6.6',
这个配置似乎没有被用到，建议移除。

2022-03-04 06:11 UTC, JohnNiang commented on build.gradle
> +        flyway: '8.5.1'
这里为什么需要用到 flyway 8.5.1 呢，Spring Boot 3.0.0-M1 似乎用的是 8.4.2。确定要使用 8.5.1，也可通过覆盖 `flyway.version` 的方式来修改版本。

可参考：
- https://docs.spring.io/spring-boot/docs/3.0.0-M1/reference/html/dependency-versions.html#dependency-versions.coordinates
- https://docs.spring.io/spring-boot/docs/3.0.0-M1/reference/html/dependency-versions.html#dependency-versions.properties

2022-03-04 07:03 UTC, JohnNiang approved these changes
LGTM

2022-03-04 07:03 UTC, JohnNiang commented on build.gradle
> +ext['h2.version'] = '2.1.210'
I can confirm this works very well, please see:

```bash
 ? ? ? ~/workspaces/halo-dev/halo ? ? ? feature/skafford *1 ? ./gradlew dependencies | grep h2                                                                                                                                           ? ? 
+--- com.h2database:h2 -> 2.1.210
+--- com.h2database:h2 -> 2.1.210
+--- com.h2database:h2 (n)
+--- com.h2database:h2 -> 2.1.210
```

2022-03-04 07:04 UTC, merged