add new cache way - redis
halo-dev/halo pull request #1751
Opened 2022-03-15 07:40 UTC by luoxmc

增加新的缓存处理方式 - redis缓存
以解决分布式部署halo时后台经常需要重新登陆的问题

关联issue地址 [https://github.com/halo-dev/halo/issues/1505](1505)

2022-03-15 07:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1751) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1751) before we can accept your contribution.<br/><hr/>**luozc-wb** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1751) it.</sub>

2022-03-15 07:56 UTC, luoxmc commented
相关介绍见我的这篇博客  [https://luoxx.top/archives/halo-distributed-deploy](地址)

2022-03-15 08:28 UTC, guqing requested changes

2022-03-15 08:28 UTC, guqing commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +        if (cacheWrapper.getExpireAt() != null) {
@luoxmc 我认为这里并不需要将CacheWrapper作为redis的value，CacheWrapper只是为了方便其他缓存而共同抽象出来的一个放数据的容器。
1. redis 的 value 只需要取出CacheWrapper中的`data`充当即可
2. key的过期时间由CacheWrapper的expireAt充当

这样做的好处是，可以将`RedisTemplate<String, CacheWrapper<String>>`简化为`RedisTemplate<String, String>`
- 不仅省去了`StringRedisSerializer`、`ObjectMapper`、`Jackson2JsonRedisSerializer`这些序列化对象的创建（特别是`ObjectMapper`的创建是很耗性能的）
- 而且 redis 中每条缓存的大小因为节省了不必要的字段而变小了（节省了内存）。

综上所述，CacheWrapper 不需要改为 public，RedisTemplate应该使用 `RedisTemplate<String, String>`类型

2022-03-15 08:44 UTC, luoxmc commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +        if (cacheWrapper.getExpireAt() != null) {
是的，很有道理，确实是可以优化一下的

2022-03-15 08:56 UTC, luoxmc commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +        if (cacheWrapper.getExpireAt() != null) {
但是貌似不好改啊，`CacheWrapper` 对象的过期时间和时间单位都不好从redis获取

2022-03-15 09:25 UTC, guqing commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +        if (cacheWrapper.getExpireAt() != null) {
你需要 Override AbstractCacheStore 中的get方法来去掉其中对过期的判断，然后从redis取值时就不在需要填充过期时间和单位到CacheWrapper了
```java
@Override
 public Optional<V> get(K key) {}
```

2022-03-16 02:30 UTC, ruibaby approved these changes
LGTM

2022-03-16 02:32 UTC, JohnNiang reviewed
Hi @luoxmc ，可以提供一个详细的测试流程么？

2022-03-16 03:03 UTC, guqing requested changes

2022-03-16 03:03 UTC, guqing commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +    public LinkedHashMap<String, String> toMap() {
这里建议改为
```java
@Override
    public LinkedHashMap<String, String> toMap() {
        LinkedHashMap<String, String> map = new LinkedHashMap<>();
        Set<String> keys = redisTemplate.keys(REDIS_PREFIX + "*");
        if (CollectionUtils.isEmpty(keys)) {
            return map;
        }
        keys.forEach(key -> map.put(key, redisTemplate.opsForValue().get(key)));
        return map;
    }
```
以减少嵌套层数，阅读更直观，当然该问题不影响此PR的合并

2022-03-16 03:10 UTC, guqing commented
你可以引入一个 embedded-redis 并且scope为设置为 testOnly，然后编写一个 RedisCacheStoreTest 单元测试以帮助我们更好的验证其正确性，并作为以后代码改动的基准线

2022-03-16 03:47 UTC, luoxmc commented on src/main/java/run/halo/app/cache/RedisCacheStore.java
> +        Assert.hasText(REDIS_PREFIX + key, "Cache key must not be blank");
手动捂脸， 一顿狂ctrl+v ，没注意看

2022-03-16 03:55 UTC, luoxmc commented
> Hi @luoxmc ，可以提供一个详细的测试流程么？

1、备份原博客
2、更新jar包，更新配置文件切换为redis缓存，配置好redis地址。mount，重启（两台或以上的机器）
3、重新登陆博客，redis客户端登陆redis观察redis里面的值，检查是否正常。
4、进入halo后台-系统-小工具-开发者选项-查看机器配置信息
5、五分钟或十分钟或更久之后刷新页面，检查是否弹窗提示需要重新登陆，若未提示则查看开发者选项里面的机器配置是否变更，若未变更，继续过一段时间后再来刷新。
6、机器信息变更代表访问的服务已经变了，而且不需要重新登陆代表缓存能共享了
7、其他功能测试（访问博客前端，各个地方点一点。访问博客后台各个地方点一点，看有啥问题）

2022-03-16 08:04 UTC, luoxmc commented
> 你可以引入一个 embedded-redis 并且scope设置为 testOnly，然后编写一个 RedisCacheStoreTest 单元测试以帮助我们更好的验证其正确性，并作为以后代码改动的基准线

@guqing  加上了，有啥不对的地方你们那边应该可以直接改吧

2022-03-18 03:05 UTC, guqing approved these changes
LGTM

2022-03-18 03:06 UTC, JohnNiang approved these changes
Thanks for your first contribution!

LGTM

2022-03-18 03:07 UTC, merged

2022-03-18 03:10 UTC, guqing commented
hi @luoxmc, Congrats on merging your first pull request! 🎉🎉🎉

2022-03-18 03:14 UTC, luoxmc commented
@guqing  刚刚仔细看了下代码，可能还是有点错误，`RedisCacheStore` 的 `toMap` 方法里面，转map时应该不能直接使用带 `REDIS_PREFIX` 前缀的key，而是应该把前缀去掉。不然其他地方获取的时候key值会对应不上。
这个前缀只是为了防止在redis数据库中与其他应用的数据冲突而设置的。

2022-03-18 03:22 UTC, guqing commented
> @guqing 刚刚仔细看了下代码，可能还是有点错误，`RedisCacheStore` 的 `toMap` 方法里面，转map时应该不能直接使用带 `REDIS_PREFIX` 前缀的key，而是应该把前缀去掉。不然其他地方获取的时候key值会对应不上。 这个前缀只是为了防止在redis数据库中与其他应用的数据冲突而设置的。
> 
> 所以对应的单元测试类也需要修改

是的 你提醒的很对，如果redis是和其他系统共享的toMap就不正确，不过目前 toMap只用来遍历数据过滤到想要的，所以目前不会出错，run.halo.app.controller.content.auth.ContentAuthentication 在该类中有一个`CACHE_PREFIX`,由于之前没有考虑redis，所以缓存key没有统一管理，目前1.5.x不会再考虑该问题，如果想共享redis可以使用不同的db index
2.0正在进行中，会使用策略来管理缓存key，所以目前在1.5不再考虑该问题