fix: posts in the recycle are not excluded when calculating posts under category
halo-dev/halo pull request #1822
Opened 2022-04-06 08:11 UTC by guqing

### What this PR does?
修复根据分类统计文章数量的方法没有排除回收站文章的问题

/kind bug
/cc @halo-dev/sig-halo

2022-04-06 08:14 UTC, guqing commented on src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
> +                Post post = postRepository.findById(postCategory.getPostId()).orElseThrow();
findById().orElseThrow()的原因是 jpa 的 getById是lazy的 基于目前的配置会导致在此时使用getById时无法生成代理对象，而 orElseThrow 只是为了获取到值，该 else 永远不会被触发

2022-04-06 11:22 UTC, ruibaby requested changes

2022-04-06 11:22 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
> +                Post post = postRepository.findById(postCategory.getPostId()).orElseThrow();
这样排除的话，会不会造成大量查询，是否有更好的方式？

2022-04-07 07:00 UTC, guqing commented
/hold

2022-04-07 07:08 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
> +                Post post = postRepository.findById(postCategory.getPostId()).orElseThrow();
先收集所有的 post id，批量查询并转换成 Map，最后在 filter 中查询 map 即可。

2022-04-07 08:26 UTC, ruibaby approved these changes
/lgtm
/approve

2022-04-07 11:33 UTC, merged