feat: Add security config for halo
halo-dev/halo pull request #1838
Opened 2022-04-12 08:48 UTC by guqing

### What this PR does?
为 2.0 版本增加 spring securiy 安全相关配置

/cc @halo-dev/sig-halo
/area core

2022-04-12 09:38 UTC, JohnNiang reviewed
1. 尝试添加一些必要的测试
2. 尝试在 PR 描述中添加 Reviewer 需要了解的文档链接

/kind feature
/hold

2022-04-13 03:55 UTC, guqing commented
/cc @halo-dev/sig-halo

2022-04-13 08:33 UTC, JohnNiang requested changes

2022-04-13 08:33 UTC, JohnNiang commented on src/main/java/run/halo/app/config/WebMvcConfig.java
> +            c -> c.isAnnotationPresent(RestController.class));
建议使用 HandlerTypePredicate 工具，请参考：

```java
HandlerTypePredicate.forAnnotation(RestController.class)
  				.and(HandlerTypePredicate.forBasePackage("org.example"))
```

2022-04-13 08:33 UTC, JohnNiang commented on src/test/java/run/halo/app/integration/security/AuthenticationTest.java
> +    public void scuredApiTest() throws Exception {
```suggestion
    public void securedApiTest() throws Exception {
```

2022-04-13 08:57 UTC, JohnNiang approved these changes
/lgtm
/approve

2022-04-13 08:58 UTC, ruibaby approved these changes
/lgtm
/approve

2022-04-13 08:59 UTC, guqing commented
/unhold

2022-04-13 09:01 UTC, JohnNiang commented
/approve

2022-04-13 09:07 UTC, ruibaby commented
/approve

2022-04-13 09:08 UTC, merged