feat: Add InMemoryOAuth2AuthorizationService for development or testing
halo-dev/halo pull request #1854
Opened 2022-04-18 09:47 UTC by guqing

### What this PR does?
添加 OAuth2AuthorizationService 的内存级实现 InMemoryOAuth2AuthorizationService，在没有持久化功能之前可用于 开发或测试使用

### Why we need it?
是 `认证请求 -> 验证密钥 -> 颁发 token -> 持久化 token` 中的一环

### What is the main attention
它是一个 stacked pull request, 合并该 PR 前先合并它的祖先 #1853

/kind feature
/area core
/milestone 2.0
/cc @halo-dev/sig-halo

2022-04-18 09:47 UTC, guqing commented
/hold

2022-04-19 03:21 UTC, JohnNiang requested changes
尝试解决一下冲突。

2022-04-19 07:45 UTC, guqing commented
/unhold

2022-04-19 07:48 UTC, guqing commented
/cc @halo-dev/sig-halo

2022-04-19 07:49 UTC, ruibaby reviewed
/lgtm

2022-04-19 08:04 UTC, JohnNiang reviewed
/lgtm

2022-04-19 08:04 UTC, JohnNiang reviewed
/approve

2022-04-19 08:06 UTC, merged