Handle exception while sending test email
halo-dev/halo pull request #1860
Opened 2022-04-19 09:29 UTC by ntdgy

Fix #1858
**What this PR does?**
1. 在发送测试邮件之前进行相关检测，并对返回的报错信息进行处理

2022-04-19 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=1860) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=1860) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=1860) it.</sub>

2022-04-19 09:37 UTC, JohnNiang commented
/cc @halo-dev/sig-halo

2022-04-19 09:54 UTC, JohnNiang requested changes

2022-04-19 09:55 UTC, JohnNiang commented
/kind bug
/area core
/milestone 1.5.x

2022-04-19 10:08 UTC, ntdgy commented on src/main/java/run/halo/app/controller/admin/api/MailController.java
> +        }
已完成修改

2022-04-19 10:08 UTC, JohnNiang requested changes

2022-04-19 10:15 UTC, ntdgy commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                //throw new EmailException("无法连接到邮箱服务器，请检查邮箱配置.[" + e.getMessage() + "]", e);
谢谢，已经修改~

2022-04-19 10:20 UTC, JohnNiang reviewed
Hi @ntdgy ，我还剩下最后一个问题，请关注一下。

2022-04-19 10:20 UTC, JohnNiang commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                if (message.contains("No provider for")) {
方便提供这样判断的依据么？或者方便提供一下对应的错误栈么？

如果能够知道具体的 Exception，用 instanceof 判断可能会更好。直接判断 message 可能不是最佳实践。

2022-04-19 10:21 UTC, JohnNiang commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                if (message.contains("No provider for")) {
比如 "No provider for" 对应的 Exception 可能是：`javax.mail.NoSuchProviderException`.

2022-04-19 10:32 UTC, ntdgy commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                if (message.contains("No provider for")) {
呃，我确实没有考虑到通过instanceof判断这件事，我晚上重新测试一下。

2022-04-19 11:14 UTC, ntdgy commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                if (message.contains("No provider for")) {
已经通过instanceof进行了修改，感谢指导~

2022-04-19 11:21 UTC, JohnNiang requested changes

2022-04-19 11:21 UTC, JohnNiang commented on src/main/java/run/halo/app/mail/AbstractMailService.java
>              } catch (MessagingException e) {
这行代码似乎被还原了。请检查以下。不建议在 controller 做错误逻辑处理，因为我们已经有统一错误逻辑处理了。请参考：https://github.com/halo-dev/halo/blob/master/src/main/java/run/halo/app/core/ControllerExceptionHandler.java

2022-04-19 14:22 UTC, JohnNiang reviewed
Hi @ntdgy ，已经趋于完美了。不过还有两个小问题，有时间请看一下。

2022-04-19 14:22 UTC, JohnNiang commented on src/main/java/run/halo/app/mail/AbstractMailService.java
>              } catch (MessagingException e) {
依然别忘记了捕捉以下 Throwable，否则非 MessagingException 会被忽略掉。:smile:

2022-04-19 14:22 UTC, JohnNiang commented on src/main/java/run/halo/app/core/ControllerExceptionHandler.java
> +        System.out.println(1);
请删除调试产生的输出。

2022-04-19 14:25 UTC, ruibaby requested changes

2022-04-19 14:25 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/MailController.java
>          return BaseResponse.ok("已发送，请查收。若确认没有收到邮件，请检查服务器日志");
@JohnNiang 是否就是这里导致了邮件还没发送，接口就已经返回成功的问题？

2022-04-19 14:45 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/admin/api/MailController.java
>          return BaseResponse.ok("已发送，请查收。若确认没有收到邮件，请检查服务器日志");
不是的。是因为之前没有捕捉 Throwable 异常，而是捕捉的 MessagingException。所以一旦 sendTextMail 发生非 MessagingException，就被忽略了，所以看不到错误信息。

2022-04-19 14:49 UTC, JohnNiang commented
/retitle Handle exception while sending test email

2022-04-19 17:09 UTC, ntdgy commented on src/main/java/run/halo/app/core/ControllerExceptionHandler.java
> +                message = "smtp服务器解析错误，请检查smtp服务器地址";
已经修改了，感谢~

2022-04-19 17:10 UTC, ntdgy commented on src/main/java/run/halo/app/core/ControllerExceptionHandler.java
> +        System.out.println(1);
已经删除了，感谢耐心的指导~

2022-04-20 01:10 UTC, JohnNiang reviewed
Thanks for your first contribution!

/lgtm

2022-04-20 01:47 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/admin/api/MailController.java
>          return BaseResponse.ok("已发送，请查收。若确认没有收到邮件，请检查服务器日志");
我纠正一下我的错误。

之前是因为 sendTextMail 方法是异步的，导致没办法知道是否发送成功。并不是因为没有捕捉到 Throwable 异常。

2022-04-20 01:49 UTC, JohnNiang commented on src/main/java/run/halo/app/mail/AbstractMailService.java
>              } catch (MessagingException e) {
Hi @ntdgy ，我纠正一下我的错误。

实际上这里捕捉 MessagingException 即可。不用捕捉 Throwable 异常。

不过当前代码可以不用修改。: P

2022-04-20 02:09 UTC, guqing reviewed
/approve

2022-04-20 02:12 UTC, JohnNiang approved these changes

2022-04-20 02:16 UTC, ruibaby approved these changes

2022-04-20 02:18 UTC, merged