feat: SMTP support configuration starttls
halo-dev/halo pull request #1861
Opened 2022-04-19 10:04 UTC by ntdgy

Fix #1848
**What this PR does?**

- 为office365,icloud等增添starttls支持

**本地测试**

- office365和outlook成功，iCloud等暂未测试
- 切换回其他邮箱后不影响正常的使用

2022-04-19 10:11 UTC, ruibaby requested changes

2022-04-19 10:11 UTC, ruibaby commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                starttls.put("mail.smtp.starttls.enable", "true");
这两个参数是否可以通过配置的方式让使用者自行设置，而不是通过判断 host 来决定。

2022-04-19 10:14 UTC, ntdgy commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                starttls.put("mail.smtp.starttls.enable", "true");
starttls的加密开启需要在前端添加额外参数，这里的相关host为只支持starttls的smtp服务，也就是在此处应该必须开启。其余为强制starttls的不需要进行该项判定。

2022-04-19 10:55 UTC, wangzhen-fit2cloud commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                starttls.put("mail.smtp.starttls.enable", "true");
> starttls的加密开启需要在前端添加额外参数，这里的相关host为只支持starttls的smtp服务，也就是在此处应该必须开启。其余为强制starttls的不需要进行该项判定。

如果存在一个不在判断条件中的邮箱服务器，也需要使用 starttls 的话，用户还是无法进行配置。所以同样建议在前端增加配置项让用户自行设置。

2022-04-19 11:23 UTC, ntdgy commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                starttls.put("mail.smtp.starttls.enable", "true");
好的，我以前没怎么接触过vue，可能需要一段时间修改。

2022-04-19 14:26 UTC, ruibaby commented on src/main/java/run/halo/app/mail/AbstractMailService.java
> +                starttls.put("mail.smtp.starttls.enable", "true");
> 好的，我以前没怎么接触过vue，可能需要一段时间修改。

目前你在后端提供这样的配置即可，此 PR 的合并不需要前端的修改。

2022-04-19 14:38 UTC, ruibaby commented
/kind feature
/milestone 1.5.x

2022-04-19 14:41 UTC, ntdgy commented
前端修改的对应的pr为： https://github.com/halo-dev/halo-admin/pull/552

2022-04-20 06:08 UTC, JohnNiang reviewed
/lgtm
/cc @halo-dev/sig-halo

2022-04-20 06:12 UTC, ruibaby reviewed
/approve

2022-04-20 06:14 UTC, JohnNiang commented
@ruibaby 别忘记 approve changes。

> Merging is blocked
Merging can be performed automatically once the requested changes are addressed.

2022-04-20 06:15 UTC, guqing reviewed
/lgtm
/approve

2022-04-20 06:15 UTC, ruibaby approved these changes

2022-04-20 06:16 UTC, merged

2022-09-30 02:17 UTC, JohnNiang commented
/milestone 1.6.x