feat: uri encode processing for attachment paths when querying attachments
halo-dev/halo pull request #1874
Opened 2022-04-21 16:00 UTC by FanZeros

#### What this PR does?

在上传文件名带有特殊字符（#%）的文件时，在生成链接的过程中，会使用相近的符号代替它们
避免之后在使用或者查看的时候因为转码问题而找不到对应资源

#### Which issue(s) this PR fixes:

Fixes #1205

#### Does this PR introduce a user-facing change?

```release-note
修复附件名包含特殊字符无法访问的问题
```

2022-04-21 16:02 UTC, FanZeros commented
PS：该改动仅对新上传的内容有效，之前的错误数据并不会被修正

2022-04-22 01:55 UTC, wangzhen-fit2cloud commented
将生成链接中的文件名进行 urlencode 似乎更合理一些。

2022-04-22 03:58 UTC, FanZeros commented
> 将生成链接中的文件名进行 urlencode 似乎更合理一些。

对文件名#% 进行 urlencode 之后，在文章引用的过程中，%会被二次urlencode，导致引用的错误
以至于需要更改更多内容
并且考虑到文件名中的#%并不是那么重要（比起urlencode成%23%25也更好分辨）

2022-04-22 06:15 UTC, ruibaby commented
个人认为这样改可能会有点粗暴，如果说再有另外的字符也会导致此问题怎么办呢。

/cc @halo-dev/sig-halo

2022-04-22 12:53 UTC, FanZeros commented
> 个人认为这样改可能会有点粗暴，如果说再有另外的字符也会导致此问题怎么办呢。
> 
> /cc @halo-dev/sig-halo

根据本人测试以及之前的issue中提到，暂时只发现这两个字符的问题
我觉得可以作为暂定的修复策略

2022-04-28 01:38 UTC, JohnNiang reviewed
Hi @FanZeros ，如果能够解决这个问题：https://github.com/halo-dev/halo/issues/1899 ，是不是就可以解决当前 PR 所想要解决的问题了呢。

2022-04-28 03:24 UTC, guqing reviewed
考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码
https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177
可以如下操作
```
// 将 local 存储的链接中的文件名替换为编码后的文件名
String path = attachmentDTO.getPath()
                .replace(attachmentDTO.getName(), encodeValue(attachmentDTO.getName()));
// ....
// 附件缩略图亦如是
 String basename = FilenameUtils.getBasename(attachmentDTO.getName());
 String extension = FilenameUtils.getExtension(attachmentDTO.getName());
// 得到 thumbail name
 String thumbnailName = String.format("%s-thumbnail%s", basename, extension);
 String thumbnailPath = attachmentDTO.getThumbPath()
      .replace(thumbnailName, encodeValue(thumbnailName));

// ...
 private String encodeValue(String value) {
    return UriUtils.encode(value, StandardCharsets.UTF_8);
}
```
以上代码中关于缩略图文件名获取的方式需要考虑：后续如果缩略图规则改变不应该影响到此处功能，所以要确保本地上传策略生存缩略图和此处规则一致

2022-04-28 03:25 UTC, guqing requested changes
考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码
https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180
可以如下操作
```
// 将 local 存储的链接中的文件名替换为编码后的文件名
String path = attachmentDTO.getPath()
                .replace(attachmentDTO.getName(), encodeValue(attachmentDTO.getName()));
// ....
// 附件缩略图亦如是
 String basename = FilenameUtils.getBasename(attachmentDTO.getName());
 String extension = FilenameUtils.getExtension(attachmentDTO.getName());
// 得到 thumbail name
 String thumbnailName = String.format("%s-thumbnail%s", basename, extension);
 String thumbnailPath = attachmentDTO.getThumbPath()
      .replace(thumbnailName, encodeValue(thumbnailName));

// ...
 private String encodeValue(String value) {
    return UriUtils.encode(value, StandardCharsets.UTF_8);
}
```
以上代码中关于缩略图文件名获取的方式需要考虑：后续如果缩略图规则改变不应该影响到此处功能，所以要确保本地上传策略生存缩略图和此处规则一致

2022-04-28 03:26 UTC, ruibaby commented
> 考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码

如果后端对此做了修改，那么前端所有编码的位置都需要移除。

2022-04-29 02:26 UTC, FanZeros commented
> Hi @FanZeros ，如果能够解决这个问题：#1899 ，是不是就可以解决当前 PR 所想要解决的问题了呢。

对，这应该也是个解决方法

2022-04-29 04:56 UTC, FanZeros commented
> Hi @FanZeros 有兴趣尝试一下这种方法么：[#1874 (review)](https://github.com/halo-dev/halo/pull/1874#pullrequestreview-955803501)

好的，我研究研究

2022-05-12 14:43 UTC, FanZeros commented
> 考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码
> 
> https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180
> 
> 
> 可以如下操作
> ```
> // 将 local 存储的链接中的文件名替换为编码后的文件名
> String path = attachmentDTO.getPath()
>                 .replace(attachmentDTO.getName(), encodeValue(attachmentDTO.getName()));
> // ....
> // 附件缩略图亦如是
>  String basename = FilenameUtils.getBasename(attachmentDTO.getName());
>  String extension = FilenameUtils.getExtension(attachmentDTO.getName());
> // 得到 thumbail name
>  String thumbnailName = String.format("%s-thumbnail%s", basename, extension);
>  String thumbnailPath = attachmentDTO.getThumbPath()
>       .replace(thumbnailName, encodeValue(thumbnailName));
> 
> // ...
>  private String encodeValue(String value) {
>     return UriUtils.encode(value, StandardCharsets.UTF_8);
> }
> ```
> 
> 以上代码中关于缩略图文件名获取的方式需要考虑：后续如果缩略图规则改变不应该影响到此处功能，所以要确保本地上传策略生存缩略图和此处规则一致
-----------------------------
暂时改动是对fullPath进行url encoding 处理，但thumbnailPath 不处理

前端部分进行如下修改：

https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentSelectModal.vue#L262
选择的时候不能二次编码
https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentDetailModal.vue#L66
https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentDetailModal.vue#L80 
不能二次编码，不然用户复制的时候会二次编码出错



不过发现一个问题：encodeURI() 不会对#进行编码，但是java的UriUtils.encode() 会对#进行编码
该问题仅会影响带#的预览图
（目前只发现#，不清楚是否会对其他符号生效）

2022-05-13 01:49 UTC, guqing commented
> > 考虑到兼容性问题，应该在此行对文件名进行 url encoding 处理，即只对返回结果编码
> > 
> > https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180
> > 
> > 
> > 可以如下操作
> > ```
> > // 将 local 存储的链接中的文件名替换为编码后的文件名
> > String path = attachmentDTO.getPath()
> >                 .replace(attachmentDTO.getName(), encodeValue(attachmentDTO.getName()));
> > // ....
> > // 附件缩略图亦如是
> >  String basename = FilenameUtils.getBasename(attachmentDTO.getName());
> >  String extension = FilenameUtils.getExtension(attachmentDTO.getName());
> > // 得到 thumbail name
> >  String thumbnailName = String.format("%s-thumbnail%s", basename, extension);
> >  String thumbnailPath = attachmentDTO.getThumbPath()
> >       .replace(thumbnailName, encodeValue(thumbnailName));
> > 
> > // ...
> >  private String encodeValue(String value) {
> >     return UriUtils.encode(value, StandardCharsets.UTF_8);
> > }
> > ```
> > 
> > 以上代码中关于缩略图文件名获取的方式需要考虑：后续如果缩略图规则改变不应该影响到此处功能，所以要确保本地上传策略生存缩略图和此处规则一致
> -----------------------------
> 暂时改动是对fullPath进行url encoding 处理，但thumbnailPath 不处理
> 
> 前端部分进行如下修改：
> 
> https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentSelectModal.vue#L262
> 选择的时候不能二次编码
> https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentDetailModal.vue#L66
> https://github.com/halo-dev/halo-admin/blob/master/src/components/Attachment/AttachmentDetailModal.vue#L80 
> 不能二次编码，不然用户复制的时候会二次编码出错
> 
> 
> 
> 不过发现一个问题：encodeURI() 不会对#进行编码，但是java的UriUtils.encode() 会对#进行编码
> 该问题仅会影响带#的预览图
> （目前只发现#，不清楚是否会对其他符号生效）
> 
> 

只需要后端通过 UriUtils.encode() 对文件名部分进行编码即可 然后把前端编码的部分删除统一由后端处理应该就可以解决问题了

2022-05-13 02:41 UTC, JohnNiang reviewed
Hi @FanZeros ，我的建议也是在构建完整连接的时候，仅对 `path` 和 `thumbnailPath` 进行 encode。所有在 halo-admin encodeURL 的地方都需要移除，否则会造成多次 encode，无法正常访问。

https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180

2022-05-13 06:14 UTC, FanZeros commented
> Hi @FanZeros ，我的建议也是在构建完整连接的时候，仅对 `path` 和 `thumbnailPath` 进行 encode。所有在 halo-admin encodeURL 的地方都需要移除，否则会造成多次 encode，无法正常访问。
> 
> https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180


嗯，我昨晚在尝试你们说的方法，在得到的缩略图链接处，去除encodeURI之后会在年月的“/”出现奇怪的%
https://github.com/halo-dev/halo-admin/blob/master/src/views\attachment\AttachmentList.vue#L88
如：

理论值 upload/2022\05\2%23%252甘雨-1652370784582-thumbnail.png
去除后 upload/2022%05%02%23%252甘雨-1652370784582-thumbnail.png
去除前 upload/2022%5C05%5C2%2523%25252%25E7%2594%2598%25E9%259B%25A8-1652370784582-thumbnail.png

以及123.png
去除后 upload/2022%05%C4%A3-thumbnail.png
去除前 upload/2022%5C05%5C123-thumbnail.png 

暂不清楚该情况是怎么发生的，还在进一步研究中

2022-05-13 07:00 UTC, FanZeros commented
"upload/2022\05\2"
![image](https://user-images.githubusercontent.com/71616828/168228744-bf714fd6-44dc-4682-a93f-a48af2aab0ef.png)
thumbPath 貌似有点问题

Windows下生成路径中的“\”感觉需要替换成“/”
如果对fullThumbPath进行replace("\\", "/")是可以正常运行的

2022-05-13 09:42 UTC, guqing commented
> halo/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
如下图所示，将https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L125 这块attachment.setThumbPath的值和125行这样写为即可
```
attachment.setThumbPath(HaloUtils.changeFileSeparatorToUrlSeparator(uploadResult.getThumbPath()));
```
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/38999863/168256779-34e9da2d-eb5c-47af-b543-bdabdc3c6cd0.png">
然后根据上面的描述https://github.com/halo-dev/halo/blob/913002d56d64b7dbd20b169921754a12790fcf80/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L177-L180处理这里

2022-05-15 13:42 UTC, FanZeros commented
已对后端对链接进行encodeURI
前端部分已删除encodeURI 

https://github.com/halo-dev/halo-admin/pull/568

2022-05-16 01:50 UTC, JohnNiang requested changes

2022-05-16 01:50 UTC, JohnNiang commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
Hi @FanZeros ，采用讨论后的方案后，这个测试应该不需要了，请确认一下呢？

2022-05-16 02:34 UTC, FanZeros commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
哦是的，我现在删掉了

2022-05-16 02:44 UTC, ruibaby commented
/retitle feat: uri encode processing for attachment paths when querying attachments

2022-05-16 02:47 UTC, ruibaby commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
你好，@FanZeros。可能还需要对讨论后的方案编写一定的测试。

2022-05-16 03:03 UTC, guqing reviewed
/lgtm

2022-05-16 06:10 UTC, JohnNiang requested changes

2022-05-16 06:10 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            fullThumbPath = HaloUtils.changeFileSeparatorToUrlSeparator(fullThumbPath);
建议删除 thumbnail path 的转换，因为在上传文件的时候已经转换过一次了。

https://github.com/halo-dev/halo/blob/ac672f721836781957a82c4816759f203f80a263/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L130-L131

2022-05-16 06:10 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            String thumbnailPath = attachmentDTO.getThumbPath()
建议只 replace basename 即可，无需拼接 thumbnail name。

2022-05-16 06:11 UTC, JohnNiang commented
/kind bug
/area core

2022-05-16 08:50 UTC, FanZeros commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            fullThumbPath = HaloUtils.changeFileSeparatorToUrlSeparator(fullThumbPath);
这里是适配之前上传（前面版本）的内容，上面貌似只对新上传的进行处理

2022-05-16 08:52 UTC, FanZeros commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
你好，@ruibaby 。我看之前AttachmentServiceInpl貌似是没有相关test的，所以没加，不知道是否需要弄一个AttachmentServiceInplTest？

2022-05-16 14:30 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            fullThumbPath = HaloUtils.changeFileSeparatorToUrlSeparator(fullThumbPath);
Hi @FanZeros ，为了不被二次 encode，建议不要在上传的时候处理 thumbPath 了，你觉得呢？

2022-05-16 15:23 UTC, FanZeros commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            fullThumbPath = HaloUtils.changeFileSeparatorToUrlSeparator(fullThumbPath);
Hi @JohnNiang 
之前是只处理Path，没处理thumbPath，我不太理解为啥只处理了一个而不是一起处理或者一起不处理？
并且处理的字符“/”貌似不会被encode？

![image](https://user-images.githubusercontent.com/71616828/168627708-d360170d-df47-4409-b0a4-029fda76a4a1.png)

2022-05-17 00:05 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
> +            fullThumbPath = HaloUtils.changeFileSeparatorToUrlSeparator(fullThumbPath);
不好意思，之前那样处理确实是我忽略了。你是对的 👍

2022-05-17 00:08 UTC, JohnNiang commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
如果可以的话，建议加上对应的测试。需要有任何帮助，我们都非常乐意提供。

2022-05-17 08:17 UTC, JohnNiang approved these changes

2022-05-17 09:51 UTC, guqing approved these changes

2022-05-17 09:52 UTC, FanZeros commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
Hi @JohnNiang ,上传文件部分的测试 你觉得要怎么测试比较好呢？直接制造一个 MultipartFile 貌似不太现实？
不像FilePathDescriptorTest，我现在有点没有想法。

2022-05-17 12:00 UTC, FanZeros commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
好的，谢谢！
那么对于upload那个方法是否就不需要测试了？

2022-05-17 12:01 UTC, ruibaby commented on src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
> +    public void nameWithIllegalChar() {
> 好的，谢谢！ 那么对于upload那个方法是否就不需要测试了？

不需要，这里主要测试编码的问题即可。

2022-05-17 12:54 UTC, ruibaby commented
@FanZeros 好像有 checkstyle 的错误哦 https://github.com/halo-dev/halo/pull/1874/checks

设置方法可以看这个 https://docs.halo.run/developer-guide/core/code-style

2022-05-17 14:27 UTC, JohnNiang requested changes

2022-05-17 14:55 UTC, JohnNiang commented
Hi @FanZeros ，非常感谢花时间修复此功能。在最后，请点击 `Details` 签署一下 `Contributor License Agreenment` 吧。

![image](https://user-images.githubusercontent.com/16865714/168841906-5752cd3a-c57c-42ad-94cb-409cf9a204ea.png)

签署成功后，PR 会自动合并。

2022-05-17 15:22 UTC, merged