feat: Add remove EXIF option when uploading images
halo-dev/halo pull request #1889
Opened 2022-04-24 09:18 UTC by SladeGranger

**What this PR does？**

fix https://github.com/halo-dev/halo/issues/1720

在附件设置中添加去除图片EXIF信息选项。

修复本地存储时自动生成的Thumbnail有时方向不对的问题。

2022-04-24 09:49 UTC, JohnNiang commented
/area core
/kind feature
/milestone 1.6.x

2022-04-24 12:42 UTC, ruibaby requested changes

2022-04-24 12:42 UTC, ruibaby commented on src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
> +            optionService.getByPropertyOrDefault(AliOssProperties.OSS_DOMAIN, String.class, "")
此改动与本 PR 无关。针对这个修改建议另外提交 PR。

2022-04-24 12:42 UTC, ruibaby commented on src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
> +        File withoutEXIF = null;
是否可以统一处理，避免在每个 file handler 都写一遍。

2022-04-24 12:42 UTC, ruibaby commented on src/main/java/run/halo/app/model/properties/AttachmentProperties.java
> +    IMAGE_EXIF_REMOVE_ENABLE("attachment_EXIF_remove_enable", Boolean.class, "true"),
建议默认为 false。

2022-04-24 12:42 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +                    .where(criteriaBuilder.like(criteriaBuilder.lower(root.get("originalContent")), likeCondition.toLowerCase()));
同上，此改动与此 PR 主题无关。

2022-04-24 12:42 UTC, ruibaby commented on src/main/resources/admin/css/13.828845cf.css
> +.comment_select_gravatar[data-v-5cb11a90]{border:1px solid #c8c8ca;margin:0 5px 3px 0}
无需提交编译后的 admin 资源。

2022-04-24 13:30 UTC, SladeGranger commented on src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
> +            optionService.getByPropertyOrDefault(AliOssProperties.OSS_DOMAIN, String.class, "")
已经修改

2022-04-24 13:31 UTC, SladeGranger commented on src/main/java/run/halo/app/model/properties/AttachmentProperties.java
> +    IMAGE_EXIF_REMOVE_ENABLE("attachment_EXIF_remove_enable", Boolean.class, "true"),
默认已改为false

2022-04-24 13:31 UTC, SladeGranger commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +                    .where(criteriaBuilder.like(criteriaBuilder.lower(root.get("originalContent")), likeCondition.toLowerCase()));
已经取消这项改动

2022-04-24 13:32 UTC, SladeGranger commented on src/main/resources/admin/css/13.828845cf.css
> +.comment_select_gravatar[data-v-5cb11a90]{border:1px solid #c8c8ca;margin:0 5px 3px 0}
已经修改

2022-04-24 13:34 UTC, SladeGranger commented on src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
> +        File withoutEXIF = null;
暂时没有好的处理方法

2022-04-26 00:26 UTC, SladeGranger commented on src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
> +        File withoutEXIF = null;
最新的commit处理了这个问题

2022-04-29 02:00 UTC, JohnNiang commented
/cc @halo-dev/sig-halo 
/cc @halo-dev/sig-halo-admin

2022-05-06 04:03 UTC, guqing commented
Hi @SladeGranger, 经过 reivew 发现你的代码重复量很大，有如下几点考虑：
1. 后续如果增加其他的附件存储方式，重复代码会不断叠加
2. 如果后续发现有 exif 相关的逻辑有bug会需要修改所有的附件上传方式才能修复
3. 测试困难
修改建议：
使用增加前置处理器
```java
interface AttachmentPreProcessor {
  // 附件上传逻辑调用前的前置处理方法
  void preProcess(InputStream in, String fileName);
}
```
然后增加一个实现类 
```java
public class AttachmentExifPreProcessor implements AttachmentPreProcessor {
    // ...
}
```
然后注册实例到 spring bean container

接着创建一个 MultipartFileWrapper 装饰器类用来包装 其参数 MultipartFile 目的是为了将前置处理器处理后的 InputStream 应用到 MultipartFile 
```java
public class MultipartFileWrapper implements MultipartFile {
    private final MultipartFile multipart;
    private InputStream inputStream;
    private String originalFilename;

    public MultipartFileWrapper(MultipartFile multipart) throws IOException {
        this.multipart = multipart;
        this.inputStream = multipart.getInputStream();
        this.originalFilename = multipart.getOriginalFilename();
    }

    @Override
    public String getName() {
        return multipart.getName();
    }

    @Override
    public String getOriginalFilename() {
        return this.originalFilename;
    }

    @Override
    public String getContentType() {
        return multipart.getContentType();
    }

    @Override
    public boolean isEmpty() {
        return multipart.isEmpty();
    }

    @Override
    public long getSize() {
        return multipart.getSize();
    }

    @Override
    public byte[] getBytes() throws IOException {
        return multipart.getBytes();
    }

    @Override
    public InputStream getInputStream() throws IOException {
        return this.inputStream;
    }

    @Override
    public Resource getResource() {
        return multipart.getResource();
    }

    @Override
    public void transferTo(File dest) throws IOException, IllegalStateException {
        multipart.transferTo(dest);
    }

    @Override
    public void transferTo(Path dest) throws IOException, IllegalStateException {
        multipart.transferTo(dest);
    }

    public void setInputStream(InputStream inputStream) {
        this.inputStream = inputStream;
    }

    public void setOriginalFilename(String originalFilename) {
        this.originalFilename = originalFilename;
    }
}
```
然后在 https://github.com/halo-dev/halo/blob/bca4e53e77fbaa6a1be438b0a0274738c79c176c/src/main/java/run/halo/app/handler/file/FileHandlers.java#L53 做如下操作
```java
MultipartFile fileWrap = new MultipartFileWrapper(file);
applyPreProcessor(file.getInputStream(), file.getOriginalFilename());
// ...
```
```java
private void applyPreProcessor(InputStream in, String originalFileName) {
   // 需要需要将 InputStream 包装为可重复读的 InputStream 方式 preProcess 无法读取,或者将 preProcess的参数InputStream改为 byte[] bytes
    InputStream result = existingInputStream;
    for(AttachmentPreProcessor processor : getPreProcessors()) {
	Object current = processor.preProcess(result, originalFileName);
	if (current == null) {
		return result;
	}
	result = current;
	}
	return result;  
    }
}

public List<AttachmentPreProcessor> getPreProcessors() {
    List<AttachmentPreProcessor> processors = new LinkedList<>();
    applicationContext.getBeansOfType(AttachmentPreProcessor.class).forEach((beanName, processor) -> {
            processors.add(processor);
    });
return processors;
}
```

2022-05-06 04:08 UTC, guqing reviewed
Hi @SladeGranger, 经过 reivew 发现你的代码重复量很大，有如下几点考虑：
1. 后续如果增加其他的附件存储方式，重复代码会不断叠加
2. 如果后续发现有 exif 相关的逻辑有bug会需要修改所有的附件上传方式才能修复
3. 测试困难

修改建议：使用前置处理器

增加附件前置处理器接口
```java
interface AttachmentPreProcessor {
  // 附件上传逻辑调用前的前置处理方法
  void preProcess(InputStream in, String fileName);
}
```
然后增加一个实现类 
```java
public class AttachmentExifPreProcessor implements AttachmentPreProcessor {
    // ...
}
```
然后注册实例到 spring bean container

接着创建一个 MultipartFileWrapper 装饰器类用来包装 其参数 MultipartFile 目的是为了将前置处理器处理后的 InputStream 应用到 MultipartFile 
```java
public class MultipartFileWrapper implements MultipartFile {
    private final MultipartFile multipart;
    private InputStream inputStream;
    private String originalFilename;

    public MultipartFileWrapper(MultipartFile multipart) throws IOException {
        this.multipart = multipart;
        this.inputStream = multipart.getInputStream();
        this.originalFilename = multipart.getOriginalFilename();
    }

    @Override
    public String getName() {
        return multipart.getName();
    }

    @Override
    public String getOriginalFilename() {
        return this.originalFilename;
    }

    @Override
    public String getContentType() {
        return multipart.getContentType();
    }

    @Override
    public boolean isEmpty() {
        return multipart.isEmpty();
    }

    @Override
    public long getSize() {
        return multipart.getSize();
    }

    @Override
    public byte[] getBytes() throws IOException {
        return multipart.getBytes();
    }

    @Override
    public InputStream getInputStream() throws IOException {
        return this.inputStream;
    }

    @Override
    public Resource getResource() {
        return multipart.getResource();
    }

    @Override
    public void transferTo(File dest) throws IOException, IllegalStateException {
        multipart.transferTo(dest);
    }

    @Override
    public void transferTo(Path dest) throws IOException, IllegalStateException {
        multipart.transferTo(dest);
    }

    public void setInputStream(InputStream inputStream) {
        this.inputStream = inputStream;
    }

    public void setOriginalFilename(String originalFilename) {
        this.originalFilename = originalFilename;
    }
}
```
然后在 https://github.com/halo-dev/halo/blob/bca4e53e77fbaa6a1be438b0a0274738c79c176c/src/main/java/run/halo/app/handler/file/FileHandlers.java#L53 做如下操作
```java
MultipartFile fileWrap = new MultipartFileWrapper(file);
applyPreProcessor(file.getInputStream(), file.getOriginalFilename());
// ...
```
```java
private void applyPreProcessor(InputStream in, String originalFileName) {
   // 需要需要将 InputStream 包装为可重复读的 InputStream 方式 preProcess 无法读取
   //或者将 preProcess的参数InputStream改为 byte[] bytes
    InputStream result = existingInputStream;
    for(AttachmentPreProcessor processor : getPreProcessors()) {
	InputStream current = processor.preProcess(result, originalFileName);
	if (current == null) {
		return result;
	}
	result = current;
	}
	return result;  
    }
}

public List<AttachmentPreProcessor> getPreProcessors() {
    List<AttachmentPreProcessor> processors = new LinkedList<>();
    applicationContext.getBeansOfType(AttachmentPreProcessor.class).forEach((beanName, processor) -> {
            processors.add(processor);
    });
   return processors;
}
```

2022-05-06 04:12 UTC, guqing commented
如果你引入了其他依赖，请将该依赖的 github 仓库链接或文档贴在该 PR 的描述上，最好是能描述一下该依赖与其他相同功能的依赖的优势（为什么使用该依赖而不是其他具有同样功能的依赖）

2022-05-06 15:31 UTC, JohnNiang commented
Hi @guqing ，我对 AttachmentPreProcessor  接口的方法有一个疑问：调用完 preProcess 方法后，处理结果应该存放在什么地方，或者接下来如何才能拿到最新的处理结果呢？参数 in 作为输入参数，但它一旦被 read 后，无法再次 read。

```java
interface AttachmentPreProcessor {
  // 附件上传逻辑调用前的前置处理方法，建议此处 InputStream 参数使用 byte[] bytes，此处写InputStream只是为了后续描述方便
  void preProcess(InputStream in, String fileName);
}
```

我的建议：

```java
MultiPartFile preprocess(MultiPartFile file);
```

2022-05-06 15:38 UTC, guqing commented
> Hi @guqing ，我对 AttachmentPreProcessor  接口的方法有一个疑问：调用完 preProcess 方法后，处理结果应该存放在什么地方，或者接下来如何才能拿到最新的处理结果呢？参数 in 作为输入参数，但它一旦被 read 后，无法再次 read。
> 
> ```java
> interface AttachmentPreProcessor {
>   // 附件上传逻辑调用前的前置处理方法，建议此处 InputStream 参数使用 byte[] bytes，此处写InputStream只是为了后续描述方便
>   void preProcess(InputStream in, String fileName);
> }
> ```
> 
> 我的建议：
> 
> ```java
> MultiPartFile preprocess(MultiPartFile file);
> ```

上述评论中对这些都有说明，
1.  MultipartFile接口只有getter方法，所以需要对处理后得到的InputStream或者byte[]包装为MultipartFileWrapper传递给file handler
2. 对于，处理后的结果会在applyPreProcessor方法返回然后
3. 参数不应该用MultipartFile应该用byte[]或者包装后的可重复读的InputStream

2022-05-18 02:10 UTC, JohnNiang commented
Hi @SladeGranger ，请问有最新的进展么，或者现在实现起来遇到什么问题了么？

2022-06-13 02:43 UTC, JohnNiang commented
/ping @SladeGranger

2022-06-16 03:34 UTC, JohnNiang commented
Hi @SladeGranger，感谢你的贡献，不过当前 PR 长时间未活跃，我们将 hold 当前 PR。
/hold

同时，现在已经有活跃的开发者接收了 Issue #1720 。在新的 Pull Request 合并之后，我们会关闭此 issue。

2022-06-16 11:47 UTC, eziosudo commented
你这都差不多写完了 -0- @guqing

2022-06-16 11:54 UTC, JohnNiang commented
> 你这都差不多写完了 -0- @guqing 

/meow

2022-06-16 11:56 UTC, eziosudo commented
/baipiao start...

2022-06-21 13:24 UTC, JohnNiang reviewed
/close

Thank @SladeGranger again!

请参考：
- https://github.com/halo-dev/halo/pull/2168

2022-06-21 13:24 UTC, closed without merging