Refine contribution.md to be clearly
halo-dev/halo pull request #1890
Opened 2022-04-24 09:27 UTC by JohnNiang

### What this PR does

As I mentioned in the title, I refactored documentation in CONTRIBUTION.md file to be clearer.

### Which issue does this PR fix

Fix #1888

/kind documentation
/cc @halo-dev/sig-halo

2022-04-24 09:34 UTC, ruibaby requested changes

2022-04-24 09:34 UTC, ruibaby commented on CONTRIBUTING.md
> +   git clone https://github.com/{YOUR_USERNAME}/halo
是否可以直接简写为：

```
git clone https://github.com/{YOUR_USERNAME}/halo --recursive
```

https://docs.halo.run/developer-guide/core/prepare#%E5%85%8B%E9%9A%86%E9%A1%B9%E7%9B%AEoptional

2022-04-24 09:58 UTC, JohnNiang commented on CONTRIBUTING.md
> +   git clone https://github.com/{YOUR_USERNAME}/halo
已优化，请看：<https://github.com/halo-dev/halo/pull/1890/commits/92b1ac9bf7283b94f2c71075e426b7e9d67ebfe9>。

2022-04-24 10:12 UTC, ruibaby reviewed
/lgtm

2022-04-24 12:53 UTC, guqing approved these changes
/approve

2022-04-24 13:10 UTC, ruibaby approved these changes

2022-04-24 13:10 UTC, merged

2022-04-28 05:52 UTC, JohnNiang commented
/cherrypick release-1.5