Change the url of comment js
halo-dev/halo pull request #2098
Opened 2022-05-19 07:04 UTC by Yhcrown

#### What type of PR is this?
/kind optimization

#### What this PR does / why we need it:
更换了评论组件的默认url
#### Which issue(s) this PR fixes:

Fixes #2097 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
no

```release-note
```

2022-05-19 07:11 UTC, guqing reviewed
/lgtm

2022-05-19 07:11 UTC, guqing commented
good job🥳

2022-05-19 07:13 UTC, ruibaby requested changes

2022-05-19 07:13 UTC, ruibaby commented on src/main/java/run/halo/app/model/properties/CommentProperties.java
> +        "//unpkg.com/halo-comment-normal@1.5.0-alpha.0/dist/halo-comment.min.js"),
```suggestion
        "https://unpkg.com/halo-comment@latest/dist/halo-comment.min.js"),
```

默认还是用这个吧，halo-comment-normal 这个库是另外一个选择。

2022-05-19 07:13 UTC, ruibaby commented on src/main/resources/templates/common/macro/global_macro.ftl
> +        <script src="//unpkg.com/halo-comment-normal@1.5.0-alpha.0/dist/halo-comment.min.js"></script>
```suggestion
        <script src="https://unpkg.com/vue@2.6.14/dist/vue.min.js"></script>
```

2022-05-19 07:13 UTC, ruibaby commented on src/main/resources/templates/common/macro/global_macro.ftl
> +        <script src="${options.comment_internal_plugin_js!'//unpkg.com/halo-comment-normal@1.5.0-alpha.0/dist/halo-comment.min.js'}"></script>
```suggestion
        <script src="${options.comment_internal_plugin_js!'https://unpkg.com/halo-comment@latest/dist/halo-comment.min.js'}"></script>
```

2022-05-19 07:14 UTC, ruibaby commented
/kind improvement
/milestone 1.5.x

2022-05-19 07:15 UTC, ruibaby commented
Hi @Yhcrown ，感谢你的贡献，但这个 PR 似乎包含了以前的提交（不影响合并），建议查阅一下这个文档。https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md

2022-05-19 07:15 UTC, ruibaby reviewed
/lgtm

2022-05-19 07:16 UTC, ruibaby commented
/retitle perf: change the resource address of the default comment component library to unpkg.com

2022-05-19 07:17 UTC, Yhcrown commented
> Hi @Yhcrown ，感谢你的贡献，但这个 PR 似乎包含了以前的提交（不影响合并），建议查阅一下这个文档。https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md

明白，不好意思这次图方便就没有创建新分支，下次会注意的。

2022-05-19 07:20 UTC, JohnNiang commented
> > Hi @Yhcrown ，感谢你的贡献，但这个 PR 似乎包含了以前的提交（不影响合并），建议查阅一下这个文档。https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md
> 
> 明白，不好意思这次图方便就没有创建新分支，下次会注意的。

建议优化一下 commit，可参考：

```bash
git fetch upstream
git reset --soft upstream/master
git add .
// check the changes
git commit -m "your message here"
git push origin feat-comment -f
```

2022-05-19 07:32 UTC, Yhcrown commented
> > > Hi @Yhcrown ，感谢你的贡献，但这个 PR 似乎包含了以前的提交（不影响合并），建议查阅一下这个文档。https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md
> > 
> > 
> > 明白，不好意思这次图方便就没有创建新分支，下次会注意的。
> 
> 建议优化一下 commit，可参考：
> 
> ```shell
> git fetch upstream
> git reset --soft upstream/master
> git add .
> // check the changes
> git commit -m "your message here"
> git push origin feat-comment -f
> ```
我搞砸了，现在好像优化不了了 TAT

2022-05-19 07:34 UTC, JohnNiang commented
> > > > Hi @Yhcrown ，感谢你的贡献，但这个 PR 似乎包含了以前的提交（不影响合并），建议查阅一下这个文档。https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md
> > > 
> > > 
> > > 明白，不好意思这次图方便就没有创建新分支，下次会注意的。
> > 
> > 
> > 建议优化一下 commit，可参考：
> > ```shell
> > git fetch upstream
> > git reset --soft upstream/master
> > git add .
> > // check the changes
> > git commit -m "your message here"
> > git push origin feat-comment -f
> > ```
> 
> 我搞砸了，现在好像优化不了了 TAT

请确保如下命令的结果如下：

```bash
$ git remote -v                                                                                                                                                ? INT ? 
origin  git@github.com:JohnNiang/halo.git (fetch)
origin  git@github.com:JohnNiang/halo.git (push)
upstream        git@github.com:halo-dev/halo.git (fetch)
upstream        git@github.com:halo-dev/halo.git (push)
```

2022-05-19 07:38 UTC, Yhcrown commented
> 

嗯呐是这样的

```
 $ git remote -v
origin  https://github.com/Yhcrown/halo.git (fetch)
origin  https://github.com/Yhcrown/halo.git (push)
upstream        https://github.com/halo-dev/halo.git (fetch)
upstream        https://github.com/halo-dev/halo.git (push)
```

2022-05-19 07:56 UTC, JohnNiang reviewed
/lgtm

2022-05-19 07:56 UTC, JohnNiang commented
/cherrypick release-1.5

2022-05-19 07:58 UTC, guqing commented
/approve

2022-05-19 07:59 UTC, ruibaby approved these changes

2022-05-19 07:59 UTC, merged

2022-10-12 07:04 UTC, caglam1356 commented
?