fix #2090
halo-dev/halo pull request #2104
Opened 2022-05-21 13:11 UTC by ETLAN666

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2022-05-21 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2104) it.</sub>

2022-05-24 10:31 UTC, JohnNiang commented
/retitle Restrict file extension when importing markdown

2022-05-24 11:11 UTC, JohnNiang reviewed
Hi @ETLAN666 ，Thanks for your first contribution.

我这里有两个小问题，请花点儿时间看看：

1. 关于文件大小限制的问题，已经在对应的代码处提交了评论；
2. 请移除与 PR 无关的修改，比如代码格式化。

2022-05-24 11:11 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +        if (file.getSize() > maxMdSize * 1024) {
建议将文件大小的上限设置为 String 所能容纳最大的内容，请看下面的代码：
https://github.com/halo-dev/halo/blob/6d4ac6b79f1c3170352b21df2f0081affc794bf4/src/main/java/run/halo/app/service/impl/BackupServiceImpl.java#L235

这里会将文件内容全部存储至 String 中，但是 String 底层存储采用的数据结构是 `byte[]`。

2022-05-24 11:14 UTC, ETLAN666 commented
谢谢您的回复和建议，我会相应做出修改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 晚上7:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [halo-dev/halo] Restrict file extension when importing markdown (PR #2104)





 
@JohnNiang commented on this pull request.
 
Hi @ETLAN666 ，Thanks for your first contribution.
 
我这里有两个小问题，请花点儿时间看看：
  
关于文件大小限制的问题，已经在对应的代码处提交了评论；
 
请移除与 PR 无关的修改，比如代码格式化。
 
 
In src/main/java/run/halo/app/service/impl/BackupServiceImpl.java:
 &gt; @@ -231,11 +248,24 @@ public BackupServiceImpl(AttachmentService attachmentService, CategoryService ca      @Override      public BasePostDetailDTO importMarkdown(MultipartFile file) throws IOException {   +        final String mdFileName = file.getOriginalFilename(); + +        if (!FileUtils.isLegalMdFilename(mdFileName, legalMdSuffixes)) { +            throw new ServiceException( +                "上传的markdown文件后缀不正确，目前支持的后缀为: " + String.join(", ", legalMdSuffixes)); +        } + +        if (file.getSize() &gt; maxMdSize * 1024) {  
建议将文件大小的上限设置为 String 所能容纳最大的内容，请看下面的代码：
 https://github.com/halo-dev/halo/blob/6d4ac6b79f1c3170352b21df2f0081affc794bf4/src/main/java/run/halo/app/service/impl/BackupServiceImpl.java#L235
 
这里会将文件内容全部存储至 String 中，但是 String 底层存储采用的数据结构是 byte[]。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-05-26 03:11 UTC, JohnNiang reviewed
Hi @ETLAN666 ，我这里有两个小方案需要和你讨论一下：

1. 关于 Markdown 文件的类型是否可配置

    我建议在后台固定文件类型。这个设置感觉有些多余。
    
    一个更方便的实现方式：
    
    ```java
        @PostMapping(value = "markdown/import", consumes = {
            MediaType.TEXT_PLAIN_VALUE,
            MediaType.TEXT_MARKDOWN_VALUE})
        @ApiOperation("Imports markdown")
        public BasePostDetailDTO backupMarkdowns(@RequestPart("file") MultipartFile file)
            throws IOException {
            return backupService.importMarkdown(file);
        }
    ```

2. 关于文件大小是否可配置？

    我建议无须提供该配置，后台限制最大文件大小，并给用户一个友好的提示即可。

2022-05-26 05:05 UTC, ETLAN666 commented
> Hi @ETLAN666 ，我这里有两个小方案需要和你讨论一下：
> 
> 1. 关于 Markdown 文件的类型是否可配置
>    我建议在后台固定文件类型。这个设置感觉有些多余。
>    一个更方便的实现方式：
>    ```java
>        @PostMapping(value = "markdown/import", consumes = {
>            MediaType.TEXT_PLAIN_VALUE,
>            MediaType.TEXT_MARKDOWN_VALUE})
>        @ApiOperation("Imports markdown")
>        public BasePostDetailDTO backupMarkdowns(@RequestPart("file") MultipartFile file)
>            throws IOException {
>            return backupService.importMarkdown(file);
>        }
>    ```
> 2. 关于文件大小是否可配置？
>    我建议无须提供该配置，后台限制最大文件大小，并给用户一个友好的提示即可。

嗯 谢谢您的建议 我会对应重新做出修改

2022-05-26 06:21 UTC, guqing commented on src/main/java/run/halo/app/utils/FileUtils.java
> +    public static boolean isLegalMdFilename(String mdFileName, String[] legalMdSuffixes) {
isLegalMdFilename 这个方法似乎没有用到

2022-05-26 06:30 UTC, ETLAN666 commented on src/main/java/run/halo/app/utils/FileUtils.java
> +    public static boolean isLegalMdFilename(String mdFileName, String[] legalMdSuffixes) {
谢谢提醒，修改后，这个方法的确不再需要，我会删除掉

2022-05-26 06:46 UTC, JohnNiang commented on src/main/java/run/halo/app/utils/FileUtils.java
> +        @NonNull ZipOutputStream zipOut, @Nullable Predicate<Path> filter)
建议撤销与此次 PR 无关的修改。

2022-05-26 06:46 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +        CommentBlackListService commentBlackListService,
建议撤销与此次 PR 无关的修改。

2022-05-26 06:46 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +import org.springframework.beans.factory.annotation.Value;
建议移除没有使用的包引入。

2022-05-26 07:01 UTC, ETLAN666 commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +import org.springframework.beans.factory.annotation.Value;
收到

2022-05-26 07:44 UTC, JohnNiang reviewed
Hi @ETLAN666 ，我这里只有最后一个小问题了。请花点儿时间看看，谢谢！

2022-05-26 07:44 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +        if (file.getSize() > 1994391530) {
Hi @ETLAN666 ，经过测试发现，String 所能存储的数据和 JVM 参数 `-Xmx` 有关系。你可以以不同的 `-Xmx` 参数运行一下测试，结果也会完全不同。

```java
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

class MaxStringTest {

    @Test
    void maxString() {
        AtomicInteger remains = new AtomicInteger(0);

        BufferedInputStream inputStream = new BufferedInputStream(new InputStream() {

            @Override
            public int read() {
                int remain = remains.incrementAndGet();
                if (remain == Integer.MAX_VALUE) {
                    return -1;
                }
                return '0';
            }
        });

        try {
            readString(inputStream);
        } catch (OutOfMemoryError error) {
            System.out.println("Max length of String we can store is " + remains.get());
            throw error;
        }
    }

    public static String readString(InputStream inputStream) {
        return new BufferedReader(
            new InputStreamReader(inputStream, StandardCharsets.UTF_8))
            .lines()
            .collect(Collectors.joining("\n"));
    }
}
```

所以，我建议直接利用 `try ... catch ...` 的方式知晓 `OutOfMemoryError`，并抛出一个友好的提示，例如：

```java
        try {
            String markdown = FileUtils.readString(file.getInputStream());
        } catch (OutOfMemoryError error) {
            throw new ServiceException(
                "文件内容过大，无法导入。" , error);
        }
```

2022-05-26 07:45 UTC, ETLAN666 commented on src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
> +        if (file.getSize() > 1994391530) {
嗯，我再修改完善一下，非常感谢您的建议

2022-05-26 08:25 UTC, JohnNiang reviewed
/kind improvement
/area core
/milestone 1.5.x
/approve
/cherry-pick release-1.5

Thanks for your contribution!

2022-05-26 08:26 UTC, guqing reviewed
/lgtm
/hold

2022-05-26 08:31 UTC, guqing requested changes
你好 234-238行这个文件大小的判断需要删除才能合并，刚刚忽略了这一点没有看到
https://github.com/halo-dev/halo/pull/2104/files#diff-47a20415b26ba5f63a8b3e6f3aba27565ea8b1bd4443367eafd1d1166023ef41R234-R238

2022-05-26 08:32 UTC, ETLAN666 commented
> 你好 234-238行这个文件大小的判断需要删除才能合并，刚刚忽略了这一点没有看到 https://github.com/halo-dev/halo/pull/2104/files#diff-47a20415b26ba5f63a8b3e6f3aba27565ea8b1bd4443367eafd1d1166023ef41R234-R238

嗯嗯，我马上修改

2022-05-26 08:37 UTC, guqing reviewed
/approve
/lgtm
/unhold

2022-05-26 08:37 UTC, guqing approved these changes

2022-05-26 08:40 UTC, merged

2022-05-26 08:40 UTC, guqing commented
Congrats on merging your first pull request! 🎉🎉🎉

2022-05-26 08:42 UTC, JohnNiang commented
/cherry-pick release-1.5