feat: add personal access token authentication mechanism
halo-dev/halo pull request #2116
Opened 2022-05-25 09:50 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:
- 新增 personal access token 机制，用于第三方对 halo API 进行访问

目前没有提供 personal access token 的创建接口，只在系统启动时创建了一个 personal access token 用于测试使用，如下控制台日志
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/38999863/170233839-27c90676-3084-4681-baae-b6a7fe2f6825.png">
通过它，可以访问该 personal access token 关联角色的资源

```shell
curl http://localhost:8090/api/v1/posts -H "Authorization: Bearer your-personal-access-token"
```

refrence:
- [Halo Personal Access Token RFC](https://github.com/halo-dev/rfcs/blob/main/identity/002-security.md)

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-05-25 09:57 UTC, ruibaby reviewed
/lgtm

2022-05-26 06:51 UTC, JohnNiang reviewed
我这里有一个小问题：

1. Personal  Access Token 的生成规则？

    请问有相关的依据证明要采用当前这种方式。这一点在 RFC 中并未提及。

2. Personal Access Token 的存储问题

    目前没有看到关于 Personal Access Token 的 Extension，我们可能需要保存 Personal Access Token 的创建者，token 本身，失效日期，创建时间以及该 Token 可访问的 scope。这一点在 RFC 中也未提及。

2022-05-26 07:08 UTC, guqing commented
> 我这里有一个小问题：
> 
> 1. Personal  Access Token 的生成规则？
>    请问有相关的依据证明要采用当前这种方式。这一点在 RFC 中并未提及。
> 2. Personal Access Token 的存储问题
>    目前没有看到关于 Personal Access Token 的 Extension，我们可能需要保存 Personal Access Token 的创建者，token 本身，失效日期，创建时间以及该 Token 可访问的 scope。这一点在 RFC 中也未提及。

关于生成规则，描述中帖了 RFC 的地址：
<img width="947" alt="image" src="https://user-images.githubusercontent.com/38999863/170436491-1172181e-ba44-4e57-8944-0c47facce6ce.png">
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/38999863/170436529-4c3519d0-0dd7-4ac1-9e12-03ea63b18056.png">

2022-05-26 07:11 UTC, guqing commented
> 我这里有一个小问题：
> 
> 1. Personal  Access Token 的生成规则？
>    请问有相关的依据证明要采用当前这种方式。这一点在 RFC 中并未提及。
> 2. Personal Access Token 的存储问题
>    目前没有看到关于 Personal Access Token 的 Extension，我们可能需要保存 Personal Access Token 的创建者，token 本身，失效日期，创建时间以及该 Token 可访问的 scope。这一点在 RFC 中也未提及。

存储规则同 oauth2 一样，统一使用 OAuth2AuthorizationService 即可，开发和测试时默认使用 InMemoryOAuth2AuthorizationService 是内存级实现，后续会写一个基于自定义模型的实现
<img width="828" alt="image" src="https://user-images.githubusercontent.com/38999863/170436770-4414d5b2-2a7c-4c5f-b634-e321c4e135cf.png">

2022-05-26 07:57 UTC, JohnNiang requested changes

2022-05-26 07:57 UTC, JohnNiang commented on src/main/java/run/halo/app/infra/utils/Base62Codec.java
> +public class Base62Codec {
建议直接引入依赖使用 Base62。这样我们就无需写任何测试代码来覆盖这段代码了，未来也无需维护。

2022-05-26 08:01 UTC, guqing commented on src/main/java/run/halo/app/infra/utils/Base62Codec.java
> +public class Base62Codec {
> 建议直接引入依赖使用 Base62。这样我们就无需写任何测试代码来覆盖这段代码了，未来也无需维护。

找了一圈没有，https://github.com/seruco/base62 这个地址也是2年没活跃了，hutool倒是有一个也来自这

2022-05-26 10:43 UTC, guqing commented
/cc @halo-dev/sig-halo

2022-05-27 06:15 UTC, JohnNiang commented on src/main/java/run/halo/app/infra/SchemeInitializer.java
> +        System.out.println(
建议加上 TODO 表明这段代码在未来可能会被移除或者用 if (logger.isDebugEnabled()) 判断是否需要打印。

2022-05-27 06:19 UTC, guqing commented on src/main/java/run/halo/app/infra/SchemeInitializer.java
> +        System.out.println(
已添加 TODO 表明这些 forTesting 方法将在未来移除

2022-05-27 06:24 UTC, JohnNiang reviewed
/lgtm
/approve

2022-05-27 06:24 UTC, JohnNiang approved these changes

2022-05-27 06:26 UTC, merged