关于文章别名自动生成的实现
halo-dev/halo pull request #2127
Opened 2022-05-29 12:46 UTC by yongzhengluo

当没有手动输入文章别名，即文章别名为空时，将文章别名自动命名为发布文章的时间；如果手动输入了文章别名，则文章别名为输入的内容。

2022-05-29 12:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2127) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2127) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2127) it.</sub>

2022-05-29 14:16 UTC, ruibaby requested changes
@yongzhengluo 感谢你的贡献，这里有几点问题：

1. 这是一个破坏性的改动，但没有事先经过讨论。参考 https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md#%E5%8F%91%E7%8E%B0-issue
2. 之前 issue 的讨论结果是 1.x 不对此进行改动，参见：https://github.com/halo-dev/halo/issues/1790#issuecomment-1081887652
3. 目前已经有自动生成 slug 的方式，而且是生成语义化的别名。

2022-05-29 14:16 UTC, ruibaby commented on pmd.xml
> +<?xml version="1.0"?>
这个文件似乎与此 PR 无关。

2022-05-29 14:16 UTC, ruibaby commented on src/main/java/run/halo/app/handler/file/FilePathDescriptor.java
>                  sb.append(first);
这个修改与此 PR 无关。

2022-05-29 14:16 UTC, ruibaby commented on src/main/java/run/halo/app/utils/SlugUtils.java
> +        Date date1 = new Date();
无意义命名。

2022-05-29 14:18 UTC, ruibaby commented
/hold

/cc @halo-dev/sig-halo

2022-06-07 03:13 UTC, JohnNiang commented
Hi @yongzhengluo ，请根据[模板](https://raw.githubusercontent.com/halo-dev/halo/master/.github/pull_request_template.md)填写 Pull Request 描述。

2022-06-23 03:09 UTC, ruibaby commented
如果此 PR 没有后续动态，我将关闭此 PR。

2022-06-23 09:56 UTC, closed without merging