feat: add yaml descriptor finder for plugin
halo-dev/halo pull request #2132
Opened 2022-06-01 09:30 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:
增加 yaml descriptor finder用于将插件中 resources/plugin.yaml 解析为 DefaultPluginDescriptor
插件管理器需要 DefaultPluginDescriptor 来管理插件
示例格式：
plugin.yaml
```yaml
apiVersion: v1
kind: Plugin
metadata:
  name: plugin-1
spec:
  # 'version' is a valid semantic version string (see semver.org).
  version: 0.0.1
  requires: ">=2.0.0"
  author: guqing
  logo: https://guqing.xyz/avatar
  homepage: https://github.com/guqing/halo-plugin-1
  displayName: "a name to show"
  description: "Tell me more about this plugin."
  license: MIT
```

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-06-02 07:22 UTC, guqing commented
/ping @halo-dev/sig-halo

2022-06-02 08:38 UTC, ruibaby reviewed
/lgtm

2022-06-02 08:56 UTC, JohnNiang requested changes

2022-06-02 08:56 UTC, JohnNiang commented on src/test/java/run/halo/app/plugin/YamlPluginDescriptorFinderTest.java
> +        assertThat(JsonUtils.objectToJson(pluginDescriptor)).isEqualToIgnoringWhitespace("""
建议用 `org.skyscreamer.jsonassert.JSONAssert` 比较两个 JSON。

2022-06-02 11:07 UTC, JohnNiang requested changes

2022-06-02 11:07 UTC, JohnNiang commented on src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
> +            return JsonUtils.jsonToObject(JsonUtils.objectToJson(unstructured),
ObjectMapper 有一个 convert 方法，无需二次转换。

2022-06-02 11:07 UTC, JohnNiang commented on src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
> +    public boolean isApplicable(Path pluginPath) {
建议加上单元测试。

2022-06-02 11:13 UTC, guqing commented on src/main/java/run/halo/app/plugin/DefaultPluginDescriptor.java
> +        protected String displayName;
> 这些字段为什么要设置为 protected 呢

为了继承的时候可以直接用 有一个PluginInfo继承了它

2022-06-06 10:19 UTC, guqing commented
/hold

2022-06-07 02:11 UTC, JohnNiang commented on src/main/java/run/halo/app/plugin/DefaultPluginDescriptor.java
> +        protected String displayName;
getter 和 setter 方法应该可以解决这个问题吧。

2022-06-07 02:49 UTC, guqing commented
/unhold
/cc @halo-dev/sig-halo

2022-06-07 03:11 UTC, JohnNiang requested changes

2022-06-07 03:11 UTC, JohnNiang commented on src/main/java/run/halo/app/plugin/YamlPluginFinder.java
> +        return JsonUtils.DEFAULT_JSON_MAPPER.convertValue(unstructured,
这里建议用 `run.halo.app.extension.Unstructured#OBJECT_MAPPER` 来转换至 Plugin。因为 Unstructured 的 ObjectMapper 会注册一些必要的 Module，且经过测试。

2022-06-07 03:11 UTC, JohnNiang commented on src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
> +        assertThatThrownBy(() -> {
这里建议 assert 一下抛出的 Throwable 类型。

2022-06-07 03:11 UTC, JohnNiang commented on src/test/resources/plugin/plugin.yaml
> +    - "banana"
这里的结构似乎不太符合 Plugin 的定义。

2022-06-07 03:11 UTC, JohnNiang commented on src/main/java/run/halo/app/plugin/Plugin.java
> +        protected String displayName;
建议将修饰符修改为 private。protected 可能会导致 Schema 生成器错误解析。

2022-06-07 06:08 UTC, JohnNiang approved these changes
/approve

2022-06-07 06:16 UTC, guqing commented
/ping @ruibaby

2022-06-07 06:31 UTC, ruibaby reviewed
/lgtm

2022-06-07 06:32 UTC, merged