feature: support issue-2171
halo-dev/halo pull request #2229
Opened 2022-07-09 11:28 UTC by Raremaa

Halo Admin API for #2171 

先满足场景，后续优化吧

前端部分稍后上传

2022-07-09 11:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2229) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2229) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2229) it.</sub>

2022-07-09 11:38 UTC, ruibaby requested changes

2022-07-09 11:38 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/PostController.java
> -import static org.springframework.data.domain.Sort.Direction.DESC;
不必要地修改，你可以先按照文档配置一下 checkstyle。

https://docs.halo.run/developer-guide/core/code-style

2022-07-09 11:38 UTC, ruibaby commented on src/main/java/run/halo/app/controller/admin/api/PostController.java
> +import javax.validation.Valid;
同上。

2022-07-09 11:38 UTC, ruibaby commented on src/main/java/run/halo/app/service/PostService.java
> -import java.util.Collection;
同上

2022-07-09 11:38 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> -import static org.springframework.data.domain.Sort.Direction.DESC;
同上，格式化问题。

2022-07-09 11:38 UTC, ruibaby commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
/ping @JohnNiang 帮忙看看通过 Specification 的方式来处理这个问题会不会好一点。个人感觉最好在原有文章查询接口支持这个排序。

2022-07-09 11:39 UTC, ruibaby commented
@Raremaa 感谢你的贡献。请先按照 https://github.com/halo-dev/halo/pull/2229#issuecomment-1179527735 的要求 Sign 一下我们的 CLA。另外，请按照我们的 Pull Request 模板修改一下 PR 描述。

2022-07-09 11:40 UTC, ruibaby commented
/retitle feat: post support sorting by number of comments

2022-07-11 05:38 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
因为文章评论数不属于Post这个entity...规格模式下不清楚要怎么做这个特性==
@JohnNiang  真心求教John大佬

2022-07-11 05:38 UTC, Raremaa commented
> 

好滴 我晚上修改一下～

2022-07-11 06:55 UTC, Raremaa commented on src/main/java/run/halo/app/controller/admin/api/PostController.java
> -import static org.springframework.data.domain.Sort.Direction.DESC;
看了一下 -- 应该是不小心切换到公司的checkstyle上去了 我粗心了一下

晚上的时候我重新配置一下halo的style

2022-07-11 11:19 UTC, Raremaa commented
@ruibaby  

- CLA已sign
- 代码风格已调整

2022-07-12 15:32 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
明天我试着用 Specification 写一下。

2022-07-13 07:07 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
Hi @Raremaa ，请参考：<https://github.com/Raremaa/halo/pull/1>。

2022-07-14 01:17 UTC, Raremaa commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
@JohnNiang 非常感谢！我先看一下 这周更新一下！

2022-08-15 15:23 UTC, JohnNiang commented on src/main/java/run/halo/app/service/impl/PostServiceImpl.java
> +    public List<Post> pageMostCommentPost(int top) {
/ping @Raremaa : )

2023-03-07 06:03 UTC, ruibaby commented
由于 1.x 的版本已经进入维护阶段，不会添加新功能，并且此 PR 也已经不适用于 2.x，所以我将关闭此 PR。

再次感谢你的贡献。

/close

2023-03-07 06:03 UTC, closed without merging