fix: 修改后台管理页面为直接渲染而不是重定向，以更好的兼容反向代理
halo-dev/halo pull request #2259
Opened 2022-07-17 08:55 UTC by viticis

#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

访问后台管理时使用重定向，在有反向代理且配置不完善的情况下，会导致重定向的域名发生错误。
#### Which issue(s) this PR fixes:

Fixes #2254

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

NONE

```release-note
```

2022-07-17 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2259) it.</sub>

2022-07-18 01:40 UTC, ruibaby reviewed
感谢你的贡献，这里有一些小建议。

我们将在稍后进行实际测试。

2022-07-18 01:40 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/MainController.java
> +    public String admin(HttpServletResponse response) throws IOException {
```suggestion
    public String admin() throws IOException {
```

2022-07-18 01:40 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/MainController.java
> +        return adminIndexRedirectUri;
可以直接 `return HaloUtils.ensureBoth(haloProperties.getAdminPath(), HaloUtils.URL_SEPARATOR) + INDEX_REDIRECT_URI`;

2022-07-18 01:40 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/MainController.java
> +    public String installation(HttpServletResponse response) throws IOException {
```suggestion
    public String installation() throws IOException {
```

2022-07-18 01:40 UTC, ruibaby commented on src/main/java/run/halo/app/controller/content/MainController.java
> +            return installRedirectUri;
可以直接 `StringUtils.appendIfMissing(this.haloProperties.getAdminPath(), "/") + INSTALL_REDIRECT_URI;`

2022-07-18 02:29 UTC, ruibaby commented
/retitle perf: access to admin page changed to template rendering

2022-07-18 02:34 UTC, viticis commented
了解，我稍后会在此PR上作修改。

2022-07-18 02:36 UTC, ruibaby commented
@viticis 另外需要签署一下我们的 CLA，否则我们没有权限合并。

https://github.com/halo-dev/halo/pull/2259#issuecomment-1186450346

2022-07-18 02:47 UTC, guqing commented
关于此 PR 的写法如何工作可以参考以下链接
- https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#spring-web
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/view/InternalResourceViewResolver.html
- https://docs.spring.io/spring-framework/docs/5.3.22/javadoc-api/org/springframework/web/reactive/result/view/UrlBasedViewResolver.html

ContentNegotiatingViewResolver#resolveViewName() -> ContentNegotiatingViewResolver#getCandidateViews() -> InternalResourceViewResolver -> 调用父类 UrlBasedViewResolver#buildView方法将静态资源创建为InternalResourceView

2022-07-18 02:49 UTC, guqing commented
/area core
/milestone 1.5.x

2022-07-18 04:26 UTC, ruibaby commented
> /area core /milestone 1.5.x

这个改动放在 1.6.x 合适一点。

/milestone 1.6.x

2022-07-19 02:10 UTC, viticis commented
已作修改，已签署CLA。
好标准的PR流程，受益匪浅。🙏

2022-07-19 02:23 UTC, JohnNiang requested changes

2022-07-19 02:23 UTC, JohnNiang commented on src/main/java/run/halo/app/controller/content/MainController.java
> +        return HaloUtils.ensureBoth(haloProperties.getAdminPath(), HaloUtils.URL_SEPARATOR) +
根据 checkstyle 规则，这里的 `+` 应该在下一行。不然 `./gradlew check -x test` 无法通过。

2022-07-19 02:31 UTC, guqing reviewed
/lgtm

2022-07-19 02:31 UTC, ruibaby reviewed
/lgtm

已在实际情况下进行测试，符合预期。感谢 @viticis 的反馈和贡献。

2022-07-19 02:35 UTC, JohnNiang approved these changes
/approve

2022-07-19 02:36 UTC, merged

2022-07-19 02:38 UTC, viticis commented
感谢 review and merge.