feat: add theme install endpoint
halo-dev/halo pull request #2302
Opened 2022-08-03 10:33 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:
新增主题安装功能，endpoint：POST /apis/api.halo.run/v1alpha1/themes/install
限制：主题不允许重复安装，重复安装属于更新功能
#### Which issue(s) this PR fixes:

Fixes #2291

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-08-03 10:42 UTC, guqing commented
/hold

2022-08-04 04:24 UTC, guqing commented
/unhold
/cc @halo-dev/sig-halo

2022-08-04 06:09 UTC, ruibaby reviewed
/lgtm

2022-08-04 08:06 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
> +            ZipInputStream zipInputStream = new ZipInputStream(inputStream);
建议用 try with resource 包裹 zipInputStream。

2022-08-04 08:06 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
> +                FileUtils.closeQuietly(inputStream);
如果我们已经关闭 zipInputStream 了，就无需再关闭 inputStream。

2022-08-04 08:06 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
> +                FileSystemUtils.deleteRecursively(tempDirectory);
建议在 finally 中清理资源。

2022-08-04 08:06 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
> +                throw new UnsupportedOperationException("Unable to unzip theme", e);
这里出现 IO 异常后抛出 UnspportedOperationException 不太合适，这个异常大多表示逻辑还未实现或者不允许用户调用。这里抛出 RuntimeException 或者自定义 Exception（例如：ThemeInstallationException）更合适。

2022-08-04 09:12 UTC, JohnNiang requested changes

2022-08-04 09:12 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
> +                    .response(responseBuilder())
建议加上 Response 的 Implementation。

2022-08-04 09:19 UTC, JohnNiang approved these changes
/lgtm
/approve

2022-08-04 09:24 UTC, merged