Fixes #2283
halo-dev/halo pull request #2317
Opened 2022-08-05 09:22 UTC by JustinLiang522

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

修复了在云端删除文件后，在Halo同时删除多个附件失败的bug。

Halo数据库里的附件并不会和云端文件实时同步，如果在云端删除文件多个后又在Halo删除，在删除第一个文件后则会抛出异常导致其它文件无法在halo的数据库中正常删除。这个PR通过删除在删除又拍云和七牛云的附件后判断返回状态和抛出异常的代码来解决这个问题。

#### Which issue(s) this PR fixes:

Fixes #2283

#### Special notes for your reviewer:
该bug只在七牛云和又拍云存在，其它云储存没有判断返回状态和抛出异常的代码，因此不存在这个问题。

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-08-05 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2317) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2317) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2317) it.</sub>

2022-08-05 13:11 UTC, ruibaby requested changes

2022-08-05 13:11 UTC, ruibaby commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> -                log.warn("附件 " + key + " 从七牛云删除失败");
建议保留这个日志。

2022-08-05 13:11 UTC, ruibaby commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> -                log.warn("附件 " + key + " 从又拍云删除失败");
同上

2022-08-05 13:11 UTC, ruibaby commented
/cc @halo-dev/sig-halo

2022-08-09 07:51 UTC, guqing commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> -                throw new FileOperationException("附件 " + key + " 从七牛云删除失败");
如果删除了异常catch，那么可能因为网络问题而导致删除失败时，halo中的数据库记录却被删除了的问题从而导致文件遗留。
建议先查询一次来判断 bucket 中是否存在文件，如果不存在则直接跳到删除数据库记录的逻辑，否则不需要改变原来的逻辑，用户可以通过手动重试来解决

2022-08-09 10:01 UTC, JustinLiang522 commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> -                throw new FileOperationException("附件 " + key + " 从七牛云删除失败");
在[原来的代码里](https://github.com/halo-dev/halo/blob/HEAD/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L147-L152)，删除附件时会先在数据库里删除后向云端发起删除请求，所以就算抛出了异常还是会有文件遗失问题。如果想要通过抛出异常防止文件遗失，可能要先将这个顺序改过来？

2022-08-09 10:14 UTC, JohnNiang commented
建议根据 OSS SDK 检查一下文件已删除的错误，再决定是否继续抛出异常。

2022-08-09 11:05 UTC, guqing commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> -                throw new FileOperationException("附件 " + key + " 从七牛云删除失败");
> 在[原来的代码里](https://github.com/halo-dev/halo/blob/HEAD/src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java#L147-L152)，删除附件时会先在数据库里删除后向云端发起删除请求，所以就算抛出了异常还是会有文件遗失问题。如果想要通过抛出异常防止文件遗失，可能要先将这个顺序改过来？

那对于这个方法可以在进入时查询一下bucket中该文件是否存在，不存在直接return即可，存在再删除，这样就不需要去改原来的顺序问题了

2022-08-09 11:08 UTC, JustinLiang522 commented
> 建议根据 OSS SDK 检查一下文件已删除的错误，再决定是否继续抛出异常。

通过判断请求返回的status_code是否为404可以知道文件是否已在云端删除，是否需要添加这一层判断？

2022-08-09 11:26 UTC, JustinLiang522 commented
我重新修改了一下代码，目前的逻辑是附件正常删除或者附件已经在云端被删除（即请求返回的status_code为404）时不抛出异常，其它情况下抛出异常，这样处理是否可行？

2022-08-15 15:22 UTC, JohnNiang commented
/cc @halo-dev/sig-halo

2022-08-17 03:43 UTC, JohnNiang requested changes

2022-08-17 03:43 UTC, JohnNiang commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> +            if (!response.isOK() && response.statusCode != 404) {
建议查阅一下七牛云 API 文档的响应码规则：<https://developer.qiniu.com/kodo/1257/delete>。删除的时候如果资源不存在，可能不是返回 404 的响应码。

2022-08-17 03:50 UTC, JohnNiang commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            if (!result.isSuccessful() && result.code() != 404) {
建议参考一下又拍云的错误码表：<http://docs.upyun.com/api/errno/>。这里可能还得判断一下 ResponseBody 中的 code 字段。

2022-08-17 06:41 UTC, JustinLiang522 commented on src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
> +            if (!response.isOK() && response.statusCode != 404) {
感谢提醒，我参考七牛云的文档，修改了对状态码的判断。七牛云在删除云端已删除附件时会直接抛出异常，异常的状态码为612，所以我将代码修改为：判断异常状态码为612时则不抛出异常。修改后测试了可以正常删除附件。

2022-08-17 06:44 UTC, JustinLiang522 commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            if (!result.isSuccessful() && result.code() != 404) {
谢谢你的建议，但我查看了删除后返回的Response的属性，其中只能获得404的状态码，并没有文档中提到的响应体。

2022-08-17 07:47 UTC, JohnNiang commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            if (!result.isSuccessful() && result.code() != 404) {
可以看看：`response#body()`。可以调试看看是否有对应的响应体。

2022-08-17 12:48 UTC, JustinLiang522 commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            if (!result.isSuccessful() && result.code() != 404) {
好的，已参考文档修改，并且测试过可以正常删除附件。:)

2022-08-18 04:11 UTC, JustinLiang522 commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            String code = result.body().string().split(",")[1].split(":")[1];
请问这样子改可以吗？
```
Response result = manager.deleteFile(key, null);
HashMap respondBody = JsonUtils.jsonToObject(result.body().string(), HashMap.class);
if (!result.isSuccessful() &&
    !(result.code() == 404 && respondBody.get("code").equals(40400001))) {
    log.warn("附件 " + key + " 从又拍云删除失败");
    throw new FileOperationException("附件 " + key + " 从又拍云删除失败");
}
```

2022-08-18 05:13 UTC, JohnNiang commented on src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
> +            String code = result.body().string().split(",")[1].split(":")[1];
可以的

2022-08-18 06:40 UTC, JohnNiang approved these changes
Thank you for your first contribution!
/approve

2022-08-18 06:54 UTC, ruibaby approved these changes
/lgtm

Thanks for your first contribution.

2022-08-18 06:54 UTC, ruibaby commented
/milestone 1.5.x

2022-08-18 06:54 UTC, ruibaby commented
/cherry-pick release-1.5

2022-08-18 06:56 UTC, ruibaby commented
@JustinLiang522 还有一点 CheckStyle 的问题，导致 Merge 被 Block。你可以按照文档配置一下：https://docs.halo.run/developer-guide/core/code-style

https://github.com/halo-dev/halo/pull/2317/checks

2022-08-18 08:04 UTC, ruibaby approved these changes
/lgtm

2022-08-18 08:06 UTC, merged