feat: add post module basic implementation
halo-dev/halo pull request #2326
Opened 2022-08-15 09:22 UTC by guqing

#### What type of PR is this?
/kind feature
/milestone 2.0
/area core

#### What this PR does / why we need it:
新增文章模块的基本实现
提供创建文章，更新草稿和发布文章三个 API
#### Which issue(s) this PR fixes:

A part of #2322

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-08-15 09:54 UTC, guqing commented
/hold

2022-08-16 03:28 UTC, ruibaby requested changes

2022-08-16 03:28 UTC, ruibaby commented on src/main/java/run/halo/app/core/extension/Category.java
> +    private CategoryStatus status;
这个 status 应该不是 required 的。

2022-08-16 11:34 UTC, ruibaby commented
最新的提交（<https://github.com/halo-dev/halo/pull/2326/commits/92b982bd053a8c34d616ef84bc77d87a2fd0e0eb>）无法通过 OpenAPI Generator 生成 Client。

```shell
openapi-generator-cli generate -i http://localhost:8090/v3/api-docs/all-api -g typescript-axios -o ./src
```

```shell
 ~/Workspace/github/halo-dev/api-client   main !2                                                        19:32:27 ─╮
❯ pnpm gen                                                                                                            ─╯

> @halo-dev/api-client@0.0.11 gen /Users/ryanwang/Workspace/github/halo-dev/api-client
> openapi-generator-cli generate -i http://localhost:8090/v3/api-docs/all-api -g typescript-axios -o ./src && pnpm lint && pnpm prettier

Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
	-attribute paths.'/apis/api.halo.run/v1alpha1/contents/{snapshotName}'. Declared path parameter snapshotName needs to be defined as a path parameter in path or operation level
	-attribute paths.'/apis/api.halo.run/v1alpha1/contents/{snapshotName}/publish'. Declared path parameter snapshotName needs to be defined as a path parameter in path or operation level

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

2022-08-18 09:06 UTC, guqing commented
补充：
1. 提供了文章列表自定义 API 用于查询文章列表数据1.
2. 提供一个 PostReconciler 用于处理 permalink, contributors, excerpt等属性

2022-08-18 10:35 UTC, guqing commented
/unhold
/cc @halo-dev/sig-halo

2022-08-19 09:38 UTC, guqing commented
/cc @JohnNiang

2022-08-22 04:05 UTC, JohnNiang commented on src/main/java/run/halo/app/content/PatchUtils.java
> +    private static final String DELIMITER = "\n";
这里分隔符是否需要考虑 `\r\n` 呢

2022-08-22 04:10 UTC, guqing commented on src/main/java/run/halo/app/content/PatchUtils.java
> +    private static final String DELIMITER = "\n";
> 这里分隔符是否需要考虑 `\r\n` 呢

根据\n将文本拆分为List然后diff行就可以了吧，恢复的时候还要把\n恢复回去的，用\r\n应该拆不开吧

2022-08-22 05:35 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
> +            .POST("posts", this::draftPost,
这个接口路径建议用：`/posts/{name}/draft`。

2022-08-22 05:36 UTC, guqing commented on src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
> +            .POST("posts", this::draftPost,
> 这个接口路径建议用：`/posts/{name}/draft`。可参考 publish 接口

可以

2022-08-22 06:34 UTC, guqing commented on src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
> +            .POST("posts", this::draftPost,
> > 这个接口路径建议用：`/posts/{name}/draft`。可参考 publish 接口
> 
> 可以

不对啊 我刚发现，起草文章哪里来的name

2022-08-22 06:46 UTC, JohnNiang approved these changes
/approve

2022-08-22 07:30 UTC, JohnNiang commented
/lgtm

2022-08-22 07:32 UTC, merged