feat: add single page extension module
halo-dev/halo pull request #2381
Opened 2022-09-05 12:38 UTC by guqing

#### What type of PR is this?
/kind feature
/milestone 2.0
/area core

#### What this PR does / why we need it:
新增自定义页面模块

#### Which issue(s) this PR fixes:

Fixes #2379

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-09-05 12:39 UTC, guqing commented
@ruibaby 此 PR 合并后改一下文章列表的查询参数
<img width="577" alt="image" src="https://user-images.githubusercontent.com/38999863/188451409-ffb8c4aa-22d4-424b-9215-4e36bdd265d8.png">

2022-09-05 15:19 UTC, JohnNiang commented on src/main/java/run/halo/app/content/SinglePageQuery.java
> +        List<String> contributorList = queryParams.get("contributor");
建议将这段逻辑放在 #getContributors 内部。

queryParams 字段是 protected 的，可直接访问到。

2022-09-05 16:42 UTC, guqing commented on src/main/java/run/halo/app/content/SinglePageQuery.java
> +        List<String> contributorList = queryParams.get("contributor");
> 建议将这段逻辑放在 #getContributors 内部。
> 
> queryParams 字段是 protected 的，可直接访问到。

ok

2022-09-06 08:22 UTC, ruibaby commented
测试之后发现两个问题：

1. listSinglePages 中的 contributors 没有数据。
2. listSinglePages 中的 status 没有 inProgress 字段。

2022-09-06 13:35 UTC, guqing commented
> 测试之后发现两个问题：
> 
> 1. listSinglePages 中的 contributors 没有数据。
> 2. listSinglePages 中的 status 没有 inProgress 字段。

retry

2022-09-07 02:21 UTC, ruibaby commented
使用 `/apis/api.halo.run/v1alpha1/singlepages/{name}/publish` 接口无法发布。具体表现为 `status.inProgress = true` `status.phase = DRAFT`

2022-09-07 03:31 UTC, guqing commented
> 使用 `/apis/api.halo.run/v1alpha1/singlepages/{name}/publish` 接口无法发布。具体表现为 `status.inProgress = true` `status.phase = DRAFT`

ok 了

2022-09-07 06:08 UTC, JohnNiang requested changes

2022-09-07 06:08 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
> +                    addFinalizerIfNecessary(oldPage);
参考：https://github.com/halo-dev/halo/pull/2382#discussion_r963798820 和 <https://github.com/halo-dev/halo/pull/2382#discussion_r964395619>。

2022-09-07 07:38 UTC, JohnNiang approved these changes
/approve

2022-09-07 07:47 UTC, ruibaby approved these changes
/lgtm

2022-09-07 07:48 UTC, merged