fix: permalink update when slug changed
halo-dev/halo pull request #2382
Opened 2022-09-06 03:11 UTC by guqing

#### What type of PR is this?
/kind bug
/area core
/milestone 2.0

#### What this PR does / why we need it:
修复文章 分类 标签的 slug 改变时，没有重新生成 permalink 的问题
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-09-06 03:16 UTC, guqing commented
/hold

2022-09-06 04:38 UTC, guqing commented
/unhold

2022-09-06 06:19 UTC, ruibaby reviewed
/lgtm

2022-09-06 07:15 UTC, JohnNiang requested changes

2022-09-06 07:15 UTC, JohnNiang commented on src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java
> +    @BeforeEach
可直接在 TagReconciler 上加上 @InjectMock 注解替代。

2022-09-06 07:15 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
> +    private static final String PERMALINK_FINALIZE = "permalink";
这里的 finalizer 名称建议不这么具体，当前 reconciler 后面可能还会进行其他预删除逻辑。这里举几个 Kubernetes 例子：

- kubernetes.io/pv-protection
- kubernetes.io/pvc-protection
- service.kubernetes.io/load-balancer-cleanup
- kubernetes

顺便提一下：一个 reconciler 只需要负责一个 finalizer 即可。

2022-09-06 07:15 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
> +                finalizeFlag(category);
应该先判断资源是否为删除状态，再添加对应的 finalizer。

2022-09-06 14:43 UTC, JohnNiang requested changes

2022-09-06 14:43 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
> +                    addFinalizerIfNecessary(category);
请参考：https://github.com/halo-dev/halo/blob/e5145b4c7f0613c50b1e016e2467600b54f71939/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java#L58

2022-09-07 05:29 UTC, JohnNiang requested changes

2022-09-07 05:29 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
> +                    cleanUpResourcesAndRemoveFinalizer(request.name());
别忘记在这里 return。

2022-09-07 08:14 UTC, JohnNiang approved these changes
/lgtm
/approve

2022-09-07 08:26 UTC, ruibaby reviewed
/lgtm

2022-09-07 08:28 UTC, merged