docs: remove readme documentation about running with jar
halo-dev/halo pull request #2501
Opened 2022-10-01 02:33 UTC by ruibaby

#### What type of PR is this?

/kind documentation
/milestone 2.0

#### What this PR does / why we need it:

因为目前暂时没有提供 JAR 包，所以移除 README 有关使用 JAR 包运行的文档。

#### Special notes for your reviewer:

/cc @halo-dev/sig-halo 

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-01 04:04 UTC, JohnNiang approved these changes
/approve

2022-10-01 04:05 UTC, JohnNiang requested changes
Docker 的部分是不是也需要修改呢？

2022-10-01 04:37 UTC, ruibaby commented
> Docker 的部分是不是也需要修改呢？

已修改。

2022-10-01 04:53 UTC, guqing reviewed
/lgtm

2022-10-04 15:05 UTC, ruibaby commented
cc @halo-dev/sig-halo

2022-10-04 16:20 UTC, JohnNiang approved these changes
/approve

2022-10-04 16:22 UTC, merged