fix: list as tree in category finder
halo-dev/halo pull request #2537
Opened 2022-10-12 05:38 UTC by guqing

#### What type of PR is this?
/kind bug
/area core
/milestone 2.0

#### What this PR does / why we need it:
修复分类树查询
#### Which issue(s) this PR fixes:

Fixes #2532
#### Special notes for your reviewer:
how to test it?
1. 新建分类并，并拖动构建一个树形
2. 在主题端通过以下代码查看浏览器控制台打印是否正确
```javascript
<script th:inline="javascript">
  const string = [[${categoryFinder.visualizeTree(categoryFinder.listAsTree())}]]
  console.log(string)
</script>
```
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
修复分类树状数据查询
```

2022-10-13 06:49 UTC, ruibaby commented
经过测试目前分级是没有问题的，但是没有按照 priority 字段排序，如：

<img width="645" alt="image" src="https://user-images.githubusercontent.com/21301288/195522371-1656e2f7-c7de-4f76-ab60-19eb9df2dc1a.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/21301288/195522442-d8b844f7-700d-4fe3-814e-78ba07ebe74f.png">

2022-10-13 08:32 UTC, ruibaby reviewed
/lgtm

实际测试符合预期。

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/21301288/195545052-f2a207e9-959a-4754-9c6e-d5832bab30ea.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/21301288/195545129-27ff60c6-ec8c-4355-a3bd-b1c0f48f3b53.png">

2022-10-13 08:42 UTC, ruibaby commented
/cc @halo-dev/sig-halo

2022-10-17 03:34 UTC, JohnNiang requested changes

2022-10-17 03:34 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +    public static String visualizeTree(List<CategoryTreeVo> categoryTreeVos) {
该方法仅作为测试或调试的时候使用，建议用 private 修饰符对主题调用隐藏。

2022-10-18 04:18 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
> +    public void print(StringBuilder buffer, String prefix, String childrenPrefix) {
建议用 `VisualizableTreeNode#print` 替换，请参考：<https://github.com/halo-dev/halo/pull/2587/commits/96d88a670b5d709edd2343efcd7a291bcccd0779>

2022-10-18 08:23 UTC, ruibaby reviewed
/lgtm

/cc @halo-dev/sig-halo

2022-10-19 02:39 UTC, guqing commented
/ping @halo-dev/sig-halo

2022-10-19 02:44 UTC, JohnNiang approved these changes
/approve

2022-10-19 02:46 UTC, merged