feat: head tag supports extension for template
halo-dev/halo pull request #2574
Opened 2022-10-14 16:53 UTC by guqing

#### What type of PR is this?
/kind feature
/milestone 2.0
/area core

#### What this PR does / why we need it:
允许插件通过实现 TemplateHeadProcessor 接口来修改主题模板的 head 标签

#### Which issue(s) this PR fixes:
how to test it?
1. 克隆 https://github.com/ruibaby/plugin-umami
2. build 一个 jar 包作为插件使用
3. 配置 plugin-umami 后能在主题页的 head 标签看到一个用于 umami 统计的 script 标签

Fixes #

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-15 04:23 UTC, ruibaby reviewed
/lgtm

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/21301288/195968502-3765d954-5557-4a03-85a6-499ed2c44189.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/195968513-76417d51-1070-4853-8d96-ab79523e1a1c.png">

2022-10-17 06:36 UTC, JohnNiang requested changes

2022-10-17 06:36 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        } catch (NoSuchBeanDefinitionException e) {
建议移除没有必要的 catch。ExtensionComponentsFinder 已经包含 `@Component` 注解。

2022-10-18 04:02 UTC, JohnNiang approved these changes
/approve
/lgtm

2022-10-18 04:10 UTC, guqing commented
/lgtm

2022-10-18 04:12 UTC, ruibaby reviewed
/lgtm

2022-10-18 04:18 UTC, merged