refactor: files were not deleted when the plugin was uninstalled
halo-dev/halo pull request #2613
Opened 2022-10-20 09:29 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.0
#### What this PR does / why we need it:
修复插件卸载时没有连同删除插件 JAR 文件的问题
#### Which issue(s) this PR fixes:

Fixes #2552

#### Special notes for your reviewer:
how to test it?
1. 以 deployment 模式安装一个插件
2. 插件的名称在插件目录是以 {pluginName}-{version}.jar 的方式命名的
3. 卸载插件时会连同删除插件的 JAR 文件
4. 开发模式下不会删除插件文件

/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
修复插件卸载时没有连同删除插件 JAR 文件的问题
```

2022-10-20 10:10 UTC, ruibaby reviewed
/lgtm

实测符合预期。

2022-10-24 02:55 UTC, guqing commented
/cc @halo-dev/sig-halo

2022-10-24 07:29 UTC, JohnNiang requested changes

2022-10-24 07:29 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/Plugin.java
> +        @Schema(required = true, pattern = "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-("
建议把这段 pattern 放入 Contant 中。并加上关于 pattern 的测试类。

2022-10-24 14:17 UTC, JohnNiang approved these changes
It works very well!

/approve

2022-10-25 02:40 UTC, ruibaby reviewed
/lgtm

2022-10-25 02:42 UTC, merged