refactor: plugin reconciler to fix entry path when optimistic lock occurred
halo-dev/halo pull request #2625
Opened 2022-10-25 06:16 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.0
#### What this PR does / why we need it:
重构 PluginReconciler，避免因为每一段逻辑的执行时间太长而增加乐观锁错误的发生概率
修复判断逻辑问题导致启动时因为发生乐关锁错误造成没有填充 entry 和 stylesheet 字段的问题
#### Which issue(s) this PR fixes:
Fixes #2616

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-25 15:09 UTC, JohnNiang requested changes

2022-10-25 15:09 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +                if (!Objects.equals(pluginStatus.getPhase(), pluginWrapper.getPluginState())) {
这里的判断可能有些多余。直接 setPhase 就好了。

2022-10-26 03:01 UTC, JohnNiang approved these changes
/approve

2022-10-26 03:09 UTC, ruibaby reviewed
/lgtm

2022-10-26 03:10 UTC, merged

2022-12-14 14:25 UTC, minliacom commented
嗯，这里reconciler会一直重试直到成功，但是于用户侧来看这里报出了错误就会认为是有什么问题。我在本地做了一下尝试，效果还不错，看看这样有没有问题：

```
} catch (Throwable t) {
                        if (t instanceof OptimisticLockingFailureException) {
                            log.debug(
                                "Optimistic locking failure when reconciling request: {}",
                                t.getMessage());
                        } else {
                            log.error("Reconciler in " + this.name
                                    + " aborted with an error, re-enqueuing...",
                                t);
                        }
                        result = new Reconciler.Result(true, null);
                    } finally {
                        queue.done(entry.getEntry());
                    }
```

2022-12-14 14:28 UTC, minliacom commented
/assign