feat: Support obtaining the previous post and next post according to post name
halo-dev/halo pull request #2636
Opened 2022-10-27 09:12 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/milestone 2.0

#### What this PR does / why we need it:
支持通过文章名称获取上一篇和下一篇文章数据

本 PR 通过实现一个固定大小的滑动窗口数据结构来通过传入的文章名称获取上一篇和下一篇文章
例如当具有一系列文章名为 [a, b, c, d, e, f, g]
查询文章名为 d 的文章的上一篇和下一篇则使用一个固定大小为 3 的滑动窗口, 示意图如下
<img width="526" alt="image" src="https://user-images.githubusercontent.com/38999863/198243133-20f77431-1107-4526-9f4f-6a11c68204e7.png">
通过窗口右移来调整当窗口圈住所需元素 D 时且 元素 D 的位置不是窗口的最后一个元素时得到一个想要的窗口
此时：
1. 如果 D 位于 window 中的第一个元素则 D 没有上一篇
2. 如果 D 位于 window 中间则 window 的第一个元素为 D 的上一篇，最后一个元素为下一篇
3. 如果 D 位于 window 的最后一个位置，则 D 没有下一篇
#### Which issue(s) this PR fixes:

Fixes #2635

#### Special notes for your reviewer:
how to test it?
1. 创建几篇文章然后发布
4. 能通过 `${postFinder.cursor(your-post-name)}` 来获取到带有上一页下一页的文章数据
5. 当文章处于第一条时没有上一页，当文章处于最后一页时没有下一页（可以通过`${postCursor.hasPrevious()}` 和 `${postCursor.hasNext()}` 判断按钮是否展示）

/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
支持通过文章名称获取上一篇和下一篇文章数据
```

2022-10-28 05:18 UTC, ruibaby reviewed
/lgtm

可使用 https://github.com/halo-sigs/theme-anatole/commit/561c34a73670decb2719aeecbf596ddddc241489 进行测试。

2022-10-31 06:25 UTC, JohnNiang requested changes

2022-10-31 06:25 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
> +        List<String> postNames = client.list(Post.class, FIXED_PREDICATE, defaultComparator())
建议加上 TODO，未来会优化这个地方。

2022-10-31 06:27 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/finders/vo/PostCursorVo.java
> +public class PostCursorVo {
类名修改为 NavigationPost 如何？

2022-10-31 06:57 UTC, JohnNiang commented
测试主题：[theme-anatole-561c34a73670decb2719aeecbf596ddddc241489.zip](https://github.com/halo-dev/halo/files/9898704/theme-anatole-561c34a73670decb2719aeecbf596ddddc241489.zip)

2022-10-31 07:25 UTC, guqing commented on src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
> +        List<String> postNames = client.list(Post.class, FIXED_PREDICATE, defaultComparator())
ok

2022-10-31 07:26 UTC, guqing commented on src/main/java/run/halo/app/theme/finders/vo/PostCursorVo.java
> +public class PostCursorVo {
> 类名修改为 NavigationPost 如何？

That sounds good

2022-10-31 07:32 UTC, JohnNiang approved these changes
/approve

2022-10-31 07:43 UTC, ruibaby reviewed
/lgtm

2022-10-31 07:44 UTC, merged