refactor: ThemeLinkBuilder needs to rely on external url
halo-dev/halo pull request #2661
Opened 2022-11-04 10:34 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.0
#### What this PR does / why we need it:
主题预览使用的 ThemeLinkBuilder 需要根据 `halo.externalUrl` 配置来决策是否带预览参数

#### Special notes for your reviewer:
how to test it?
安装几个主题后预览看链接是否正确

/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-11-04 11:30 UTC, JohnNiang requested changes

2022-11-04 11:30 UTC, JohnNiang commented on src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java
> +        assertThat(ThemeLinkBuilder.linkInSite(externalUrlSupplier.get(), "/post")).isTrue();
这里测试 linkInSite 应该不需要引入 externalUrlSupplier 吧。直接构造一个 URI 即可。

2022-11-04 11:30 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/ThemeLinkBuilder.java
> +    static boolean linkInSite(@NonNull URI externalUri, @NonNull String link) {
对于主机名（域名）一致，但端口不一致是否，是否属于有同一个 Site 呢？

建议在测试用例中体现一下。

2022-11-04 11:56 UTC, guqing commented on src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java
> +        assertThat(ThemeLinkBuilder.linkInSite(externalUrlSupplier.get(), "/post")).isTrue();
> 这里测试 linkInSite 应该不需要引入 externalUrlSupplier 吧。直接构造一个 URI 即可。

有道理

2022-11-04 12:17 UTC, guqing commented on src/main/java/run/halo/app/theme/ThemeLinkBuilder.java
> +    static boolean linkInSite(@NonNull URI externalUri, @NonNull String link) {
> 对于主机名（域名）一致，但端口不一致是否，是否属于有同一个 Site 呢？
> 
> **建议在测试用例中体现一下**。

https://github.com/halo-dev/halo/blob/69a112a060ef9c8ae33a3ced489b475b22e6a1bb/src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java#L122-L123

2022-11-07 03:47 UTC, JohnNiang reviewed
/lgtm

2022-11-07 07:00 UTC, ruibaby approved these changes
/approve

2022-11-07 10:15 UTC, ruibaby commented
/close

2022-11-07 10:15 UTC, ruibaby commented
/reopen

2022-11-07 14:50 UTC, JohnNiang approved these changes

2022-11-08 01:33 UTC, merged