chore: 调整dev profile配置
halo-dev/halo pull request #2753
Opened 2022-11-24 04:03 UTC by wan92hen

#### What type of PR is this?
/kind support

#### What this PR does / why we need it:

1. 增加console代理配置，默认代理到`http://localhost:3000/`。
2. 增加用户名密码初始化配置。
3. 调整`halo.work-dir`为相对路径`./halo2-dev`，可以兼容Window下运行；同时在`.gitignore`中忽略该工作目录。

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2022-11-24 06:14 UTC, ruibaby requested changes

2022-11-24 06:14 UTC, ruibaby commented on src/main/resources/application-dev.yaml
> +  work-dir: ./halo2-dev
这个改动可能不太适合直接在 dev 配置里面改，因为主题开发时，主题项目需要基于这个目录。如果在 Windows 平台有路径问题且无法兼容，建议增加一个 application-windows.yaml

2022-11-24 07:47 UTC, wan92hen commented on src/main/resources/application-dev.yaml
> +  work-dir: ./halo2-dev
确实会有这样子的问题。

2022-11-24 08:15 UTC, wan92hen commented on src/main/resources/application-dev.yaml
> +  work-dir: ./halo2-dev
新的 commit 中增加了 dev-win profile，工作目录使用了 `../halo-dev`，这样其他人没有特殊要求的话，可以不用改配置也能跑起来，也不影响在工作目录中放主题仓库。

2022-11-24 10:28 UTC, JohnNiang requested changes
建议提供一个新的配置文件（`application-win.yaml`），内容如下：

```yaml
spring:
  r2dbc:
    url: r2dbc:h2:file:///~/halo2-dev/db/halo-next?MODE=MySQL&DB_CLOSE_ON_EXIT=FALSE
halo:
  work-dir: ${user.home}/halo2-dev
```

这样可以减少相同配置的维护。

我们在运行（调试） Halo 的时候可以指定 profile：`dev,win` 即可。

2022-11-28 02:43 UTC, JohnNiang commented
/ping @wan92hen

2022-11-28 04:16 UTC, ruibaby reviewed
/lgtm

实际测试可以正常运行。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/21301288/204192904-bd93445d-74ad-413e-a0fe-1696b8ba4bcc.png">

2022-11-28 06:22 UTC, JohnNiang approved these changes
/approve

2022-11-28 06:24 UTC, ruibaby approved these changes

2022-11-28 06:24 UTC, guqing reviewed
/lgtm

2022-11-28 06:26 UTC, merged