Halo2.0 Support MariaDB Native Driver
halo-dev/halo pull request #2787
Opened 2022-11-27 09:04 UTC by codychau

#### What type of PR is this?
/kind improvement

#### What this PR does / why we need it:
引入对R2DBC的MariaDB的支持，增加例子配置

#### Special notes for your reviewer:
现在，Halo可以使用MariaDB数据库原生驱动了，摆脱MySQL驱动带来的连接问题。

- [x] 支持首次启动执行SQL脚本创建表

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-11-27 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2787) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2787) before we can accept your contribution.<br/><hr/>**zbhcni** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2787) it.</sub>

2022-11-27 09:19 UTC, codychau commented
你们手工测一下吧，我测过功能是正常才提交的。THX

2022-11-27 10:14 UTC, ruibaby commented
@codychau 感谢你的贡献，在合并之前需要签署一下我们的 CLA https://github.com/halo-dev/halo/pull/2787#issuecomment-1328200919 

另外，似乎单元测试没有通过。

2022-11-27 15:43 UTC, JohnNiang commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
需要注意的是，最新的 MariaDB（1.1.2）驱动并未实现 R2DBC Spec [1.0.0.RELEASE](https://r2dbc.io/spec/1.0.0.RELEASE/spec/html/)，目前仅支持 [0.9.1.RELEASE](https://r2dbc.io/spec/0.9.1.RELEASE/spec/html/)，可能会存在不兼容的问题。这也是我们一直没有添加 Maria DB 驱动支持的缘故。

参考：
- https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/8ee91691157831683e2e44d3ae3107560c9cd577/README.md
    ![image](https://user-images.githubusercontent.com/16865714/204144057-035d7cc4-035f-4938-aa62-b2e390471e1c.png)

2022-11-28 01:34 UTC, codychau commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
好的，明白了。感谢指导！不过我会身先士卒，自己先把所有的Halo的特性在MariaDB中充分测试，如果没有什么问题的话，可以尽快推出兼容方案，因为MariaDB仍是大势所趋，特别是云服务方面。如果因为不完全兼容R2DBC而导致的市场流失，损失可能更大。

2022-11-28 02:03 UTC, JohnNiang commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
@codychau 如果能够推进 [MariaDB R2DBC connector](https://github.com/mariadb-corporation/mariadb-connector-r2dbc) 支持 R2DBC SPI 1.0.0.RELEASE 的话，可能会更好 : P

/meow

2022-11-28 02:17 UTC, codychau commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
我觉得可以，但是我估计有很多人在做了，很快就会有相应的更新；说不定我们可以fork他们那一份，做一个尊享版Halo MariaDB Driver。更安全可靠。（开个玩笑）

2022-11-28 02:29 UTC, JohnNiang commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
@codychau 可以参考一下这个提交：<https://github.com/mariadb-corporation/mariadb-connector-r2dbc/commit/7a89c0d4e198016652175bd82fa0b4f296eeb56f>。他们似乎已经在 develop 分支支持了，等待他们发布最新的版本吧。

2022-11-28 02:31 UTC, codychau commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
@JohnNiang 
或许我可以先尝试一下它们的开发分支，其实上面那个问题它们已经解决了，只是待其他功能一起发布而已，捂脸哭
![image](https://user-images.githubusercontent.com/22789452/204178428-73ed4bdd-ac95-4f5e-aad2-718517ea8fe0.png)
你看嘛，1.1.3-快照版就支持了。解决方法也是简单粗暴！
![image](https://user-images.githubusercontent.com/22789452/204178888-bb5a0d9a-42b8-46c4-9641-8389df4d7e66.png)

2022-11-28 02:41 UTC, codychau commented on build.gradle
> +    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.2'
> @codychau 可以参考一下这个提交：[mariadb-corporation/mariadb-connector-r2dbc@7a89c0d](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/commit/7a89c0d4e198016652175bd82fa0b4f296eeb56f)。他们似乎已经在 develop 分支支持了，等待他们发布最新的版本吧。

对的，这个是它们修复了跟R2DBC返回值长度不一致导致的问题，这个其实我也发现了，在处理一些ddl的时候会碰到

2022-12-06 14:33 UTC, JohnNiang commented
Hi @codychau ，如果现在能够引入 `org.mariadb:r2dbc-mariadb:1.1.3-SNAPSHOT` 依赖，我们可以提前完成支持 MariaDB 这件事情，距离 2.1.0 发布还有一段时间，有足够的时间给到社区测试。

2022-12-12 08:17 UTC, codychau commented
@JohnNiang 我最近在尝试用CI工具编译org.mariadb:r2dbc-mariadb:1.1.3-SNAPSHOT ，目前看是可以正常编译的，然后计划近期就以SystemScope的方式引入测试，如果都没什么问题的话，就会通知您

2022-12-23 14:13 UTC, JohnNiang commented
https://github.com/mariadb-corporation/mariadb-connector-r2dbc/releases/tag/1.1.3

mariadb connector  r2dbc 终于发布新版了。

2022-12-24 05:55 UTC, codychau commented
@JohnNiang   我已经用上了，跟SQL相关的报错似乎都得到了解决，测试了两天后台日志都是比较的干净，功能也是正常的，不过我之前用1.1.2的时候功能貌似也没太大影响。现在有新的包肯定是用新的更好

2022-12-24 06:00 UTC, codychau commented
@JohnNiang   我已经用上了，跟SQL相关的报错似乎都得到了解决，测试了两天后台日志都是比较的干净，功能也是正常的，不过我之前用1.1.2的时候功能貌似也没太大影响。现在有新的包肯定是用新的更好

2022-12-24 07:46 UTC, ruibaby commented
@codychau 为什么要关闭这个 PR 然后再重新提交呢？ 这样会丢失所有 Review 记录。

2022-12-25 03:03 UTC, codychau commented
@ruibaby 我换了一个分支，之前我的分支加了很多自己的东西进去，用新的分支提交

2022-12-25 13:26 UTC, ruibaby commented
> @ruibaby 我换了一个分支，之前我的分支加了很多自己的东西进去，用新的分支提交

你可以参考 https://github.com/halo-dev/halo/pull/3038#issuecomment-1364671579 操作一下，我建议使用还是使用这个 PR。

2022-12-26 01:31 UTC, codychau commented
@ruibaby 我已经把我的main分支rebase了，提示“已经是最新”，无奈之下我把专门为了提PR的内容也给reset到了main分支，并且重开这个PR了，也检查了对比文件确认只剩我需要提交给你们的部分了。那个新PR我也给关闭了重启这个PR，已经仁至义尽了。

2022-12-26 02:08 UTC, JohnNiang requested changes

2022-12-26 02:08 UTC, JohnNiang commented on src/main/resources/application-mariadb.yaml
> +halo:
mariadb profile 的配置建议不包含 halo 相关的配置。

2022-12-26 03:59 UTC, ruibaby reviewed
/lgtm

<img width="745" alt="image" src="https://user-images.githubusercontent.com/21301288/209497955-63941344-e5f0-4012-a2b2-f4cfc4150c27.png">
<img width="1737" alt="image" src="https://user-images.githubusercontent.com/21301288/209498012-74899a41-0371-4803-847c-cd6e6a0731bb.png">

2022-12-26 04:01 UTC, JohnNiang approved these changes
/approve

Thank you for your first contribution!

2022-12-26 04:02 UTC, merged

2022-12-26 04:55 UTC, codychau commented
感谢各位的付出和包容，虽然最终结果是好的，但是给你们添了不少麻烦！给你们点个赞，辛苦了！下面是我的个人官网，目前仍在装修中，所使用的技术正是Halo2+MariaDB的环境，目前运行良好，我很喜欢，后面我会继续关注网友提出的问题并尝试修复，希望以后合作愉快！
[http://nacgame.com/upassistant2](http://nacgame.com/upassistant2)