Temporary solution to the problem of not being able to start the sys
halo-dev/halo pull request #2907
Opened 2022-12-09 09:14 UTC by minliacom

…em when developing plugins.

#### What type of PR is this?
/kind improvement

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2022-12-09 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2907) it.</sub>

2022-12-09 11:34 UTC, guqing requested changes

2022-12-09 11:34 UTC, guqing commented on src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java
> +                pluginId=  pluginManager.loadPlugin(path);
这行上面有一个 idForPath 的方法返回值就是 pluginId 使用变量接收它即可不需要重复 load

2022-12-09 11:34 UTC, guqing commented on src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java
>              }
这里已经做了你所做的判断，问题并非是这样

2022-12-09 11:36 UTC, guqing commented
参考 https://github.com/halo-dev/halo/issues/2901#issuecomment-1343998122
catch 这行的异常忽略它即可

2022-12-11 14:41 UTC, guqing reviewed
/approve

2022-12-12 02:22 UTC, JohnNiang approved these changes
/lgtm

2022-12-12 02:24 UTC, merged