fix: optimistic locking failure when reconciling
halo-dev/halo pull request #2957
Opened 2022-12-15 04:00 UTC by minliacom

#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

/kind api-change

#### Which issue(s) this PR fixes:

Fixes #2591

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```
NONE
```

2022-12-15 05:11 UTC, guqing reviewed
/lgtm

2022-12-15 15:00 UTC, JohnNiang requested changes

2022-12-15 15:45 UTC, guqing commented on src/main/java/run/halo/app/extension/controller/DefaultController.java
> +                                t.getMessage());
Entry 只包含了一个 name 感觉并看不出来什么信息 且大部分时候都是uuid

2022-12-16 03:31 UTC, guqing commented on src/main/java/run/halo/app/extension/controller/DefaultController.java
> +                                t.getMessage());
可以

2022-12-16 06:21 UTC, JohnNiang approved these changes
/approve
/retitle Change log level to warn for optimistic locking failure error

2022-12-16 07:00 UTC, guqing commented
/lgtm

2022-12-16 07:09 UTC, merged