fix: when the theme was upgraded, the template content was not refreshed
halo-dev/halo pull request #2970
Opened 2022-12-15 12:07 UTC by minliacom

#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

通过在添加模板引擎管理里添加clearCache方法，在升级主题后进行缓存刷新，让新模板内容生效。

#### Which issue(s) this PR fixes:

Fixes #2953 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2022-12-15 12:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=2970) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=2970) before we can accept your contribution.<br/><hr/>**Your Name** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=2970) it.</sub>

2022-12-15 12:32 UTC, ruibaby commented on src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
> +            .doOnNext(theme -> {
可能需要在安装的时候也要清理，因为我尝试先删掉旧主题然后安装新主题时同样没有清理缓存。

2022-12-15 12:34 UTC, ruibaby commented
感谢 @minliacom 的贡献，在 Review 前请先签署我们的 CLA 协议：https://github.com/halo-dev/halo/pull/2970#issuecomment-1352966418

另外，测试似乎没有通过。

2022-12-15 14:41 UTC, JohnNiang requested changes

2022-12-15 14:41 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
> +            .doOnNext(theme -> templateEngineManager.clearCache(request))
在 doOnNext 内调用 Reactive 方法似乎不会生效。

2022-12-15 15:28 UTC, minliacom commented on src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
> +            .doOnNext(theme -> templateEngineManager.clearCache(request))
应该放在哪里， 还没学会reactive，不太会

2022-12-15 15:43 UTC, guqing commented on src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
> +            .doOnNext(theme -> templateEngineManager.clearCache(request))
Install 这clear感觉并不合适，可以在卸载主题后清除

2022-12-16 02:28 UTC, ruibaby commented on src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
> +            .doOnNext(theme -> templateEngineManager.clearCache(request))
> Install 这clear感觉并不合适，可以在卸载主题后清除

agree

2022-12-16 03:20 UTC, guqing commented
我忽略了一点 卸载的时候应该要在 reconciler 清除缓存，这时候还不太好得到 themeContext 作为 key，根据 key 删除
```
private final ConcurrentLruCache<ThemeContext, ISpringWebFluxTemplateEngine> engineCache;
```
是否可以暂时直接清除这个 LRU cache 来实现清除缓存 @JohnNiang

2022-12-16 05:34 UTC, minliacom commented
> 我忽略了一点 卸载的时候应该要在 reconciler 清除缓存，需要在 ThemeResolver 中添加一个根据 theme name 得到 ThemeContext 的方法

嗯，我按这样尝试一下

2022-12-16 06:45 UTC, JohnNiang commented
如果要更细致的话，在切换主题的时候就得清理 Thymeleaf 缓存。

2022-12-16 06:50 UTC, JohnNiang commented
Hi @minliacom ，建议当前 PR 只解决升级时清理缓存即可。暂时不用管删除和切换主题的情况。

2022-12-16 06:52 UTC, minliacom commented
> Hi @minliacom ，建议当前 PR 只解决升级时清理缓存即可。暂时不用管删除和切换主题的情况。

那我先把删除和切换的代码删除了再提交

2022-12-16 07:43 UTC, guqing commented on src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
> +    private final TemplateEngineManager templateEngineManager;
这里没有用到可以去掉 templateEngineManager 还有对应的测试类也是

2022-12-16 07:47 UTC, guqing commented on src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
>                  .uri("/themes/default/upgrade")
建议在这个 124 行下面加上 verify
verify(templateEngineManager, times(1)).clearCache(eq("default"));

2022-12-16 08:08 UTC, guqing reviewed
/approve
经测试符合预期 🎉

2022-12-16 11:44 UTC, ruibaby reviewed
/lgtm

2022-12-16 15:39 UTC, JohnNiang commented
/hold

Please wait for my code review.

2022-12-16 16:04 UTC, JohnNiang approved these changes
/unhold

2022-12-17 12:55 UTC, ruibaby commented
https://github.com/halo-dev/halo/pull/2970#issuecomment-1352966418

这里有一个名为 `Your Name` 的用户名没有签署 CLA，导致无法合并。建议进行以下操作：

```
git fetch upstream/main

git reset --soft upstream/main

git add .

git commit -m "fix: not clearing the template engine cache after upgrading the theme"

git push -f
```

2022-12-17 13:55 UTC, minliacom commented
@ruibaby OK了

2022-12-19 02:23 UTC, JohnNiang approved these changes
/lgtm

2022-12-19 02:24 UTC, merged

2022-12-19 14:51 UTC, ruibaby commented
@halo-dev/sig-halo 其他需要清理缓存的情况是否需要提交 issue 呢？