Add a method listSubTreeByName
halo-dev/halo pull request #2995
Opened 2022-12-18 11:42 UTC by chengfeiyue

What type of PR is this?
/kind feature
/kind api-change

What this PR does / why we need it:
添加一个方法可以根据分类树的任意一层级的名称查询子树

Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/pull/2962#issuecomment-1354262095

Special notes for your reviewer:
None
Does this PR introduce a user-facing change?
None

2022-12-19 07:02 UTC, ruibaby commented
/cc @halo-dev/sig-halo

2022-12-19 08:23 UTC, guqing commented on src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +                : StringUtils.equalsIgnoreCase(v.getMetadata().getName(), nodeName))
这里不建议使用 equalsIgnoreCase 直接 equals 即可

2022-12-19 08:27 UTC, guqing commented on src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +    public Flux<CategoryTreeVo> listSubTreeByName(String nodeName) {
方法名称建议为 listAsTree(String name)，并需要添加一些测试，参考 [CategoryFinderImplTest#listAsTree](https://github.com/halo-dev/halo/blob/27775c9ac933f01e477343b8c74502c9e33c212d/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java#L97)

2022-12-19 08:59 UTC, chengfeiyue commented on src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +    public Flux<CategoryTreeVo> listSubTreeByName(String nodeName) {
已改为equals,并添加了测试方法

2022-12-21 10:38 UTC, ruibaby commented
/retitle feat: add listAsTree(name) method for category finder

2022-12-21 14:33 UTC, guqing commented on src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +            defaultComparator(), pageNullSafe(page), sizeNullSafe(size))
建议撤回这一行改动，可以配置一下 checkstyle，这行改动会导致与 IDEA 格式化行为不一样，格式化时会变动，造成修改困扰

2022-12-21 14:36 UTC, guqing commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos).hasSize(1);
这里建议明确断言一下这一个元素的 name 是否为期望值
```
assertThat(treeVos.get(0).getMetadata().getName()).isEqualTo("E");
```

2022-12-21 15:13 UTC, chengfeiyue commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos).hasSize(1);
按照：https://docs.halo.run/1.6/developer-guide/core/code-style 这里配置checkStyle，发现格式化 还是57行这样，不明所以，然后就手动还原了下原格式
<img width="846" alt="image" src="https://user-images.githubusercontent.com/49852751/208938321-365dfd70-f3b5-43d9-a7c9-0bc631152850.png">
里建议明确断言一下这一个元素的 name 是否为期望值
------------已明确

2022-12-21 16:33 UTC, JohnNiang requested changes

2022-12-21 16:33 UTC, JohnNiang commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos.get(0).getMetadata().getName()).isEqualTo("E");
建议验证一下子节点是否正确。

2022-12-22 03:25 UTC, chengfeiyue commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos.get(0).getMetadata().getName()).isEqualTo("E");
已添加验证子节点断言

2022-12-22 03:25 UTC, chengfeiyue commented on src/main/java/run/halo/app/theme/finders/CategoryFinder.java
> +    Flux<CategoryTreeVo> listAsTree(String nodeName);
已修改为name 为变量名

2022-12-22 03:37 UTC, JohnNiang commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos.get(0).getMetadata().getName()).isEqualTo("E");
```
        /*
         *  D
         *  ├── E
         *  │   ├── A
         *  │   │   └── B
         *  │   └── C
         *  └── G
         *  ├── F
         *      └── H
         */
```

从构造的分类树来看，E 节点下有两个子节点：A 和 C，节点 A 下有一个子节点 B。建议至少再加上节点 C 的验证。

2022-12-22 03:44 UTC, chengfeiyue commented on src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
> +        assertThat(treeVos.get(0).getMetadata().getName()).isEqualTo("E");
已添加E节点下的多个子节点验证：A和C

2022-12-22 03:47 UTC, JohnNiang approved these changes
/lgtm

2022-12-22 03:54 UTC, ruibaby approved these changes

2022-12-22 03:56 UTC, merged