fix issue 3265
halo-dev/halo pull request #3293
Opened 2023-02-12 15:18 UTC by JustinLiang522

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

文章发布用户被删除后，设置这篇文章的发布人为Ghost

#### Which issue(s) this PR fixes:

Fixes #3265

```release-note
NONE
```

2023-02-13 06:42 UTC, guqing commented on src/main/java/run/halo/app/content/impl/PostServiceImpl.java
> +                var contributor = new Contributor();
建议将这个 ghost 对象放到 Contributor 类作为静态方法，可能不止这个地方会用到免得到处填充对象，然后直接用 defaultIfEmpty 方法即可

2023-02-14 03:23 UTC, ruibaby requested changes

2023-02-14 03:23 UTC, ruibaby commented on src/main/java/run/halo/app/content/Contributor.java
> +        contributor.setDisplayName("Ghost");
建议目前设置为 **已删除用户**

2023-02-14 07:39 UTC, JohnNiang commented on src/main/java/run/halo/app/content/Contributor.java
> +        contributor.setDisplayName("Ghost");
更建议添加一个标识，如 deleted 来表示 contributor 是否已删除。

2023-02-14 09:47 UTC, JustinLiang522 commented on src/main/java/run/halo/app/content/Contributor.java
> +        contributor.setDisplayName("Ghost");
> 更建议添加一个标识，如 deleted 来表示 contributor 是否已删除。

这个deleted属性应该怎么用？是要返回原Contributor的名字然后将deleted属性设置为true吗？那是不是就不需要ghost了？

2023-02-14 11:03 UTC, ruibaby commented on src/main/java/run/halo/app/content/Contributor.java
> +        contributor.setDisplayName("Ghost");
> 更建议添加一个标识，如 deleted 来表示 contributor 是否已删除。

对用户做逻辑删除吗？

2023-02-14 12:39 UTC, JohnNiang commented on src/main/java/run/halo/app/content/Contributor.java
> +        contributor.setDisplayName("Ghost");
当前 PR 可简单处理，是否加上 deleted 属性到 contributor 上后面再说吧。

/lgtm

2023-02-15 05:05 UTC, guqing reviewed
/lgtm

2023-02-15 05:29 UTC, ruibaby reviewed
/approve

2023-02-15 05:30 UTC, rootvip commented
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

2023-02-15 05:35 UTC, ruibaby approved these changes

2023-02-15 05:36 UTC, merged

2023-02-15 05:36 UTC, ruibaby commented
/cherry-pick release-2.2