refactor: APIs returns ghost users when user is deleted
halo-dev/halo pull request #3373
Opened 2023-02-23 08:32 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.3.x

#### What this PR does / why we need it:
用户被删除时关联到的用户返回 ghost 用户信息

#### Which issue(s) this PR fixes:

Fixes #3356

#### Special notes for your reviewer:
/cc @halo-dev/sig-halo 
#### Does this PR introduce a user-facing change?
```release-note
用户被删除时关联到的用户返回 ghost 用户信息
```

2023-02-23 14:02 UTC, JohnNiang requested changes

2023-02-23 14:02 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/service/UserService.java
> +    Mono<User> userOrGhost(String username);
方法名建议更改为：`getUserOrGhost`。

2023-02-24 03:21 UTC, JohnNiang requested changes

2023-02-24 03:21 UTC, JohnNiang commented on src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +
```suggestion
```

2023-02-24 03:21 UTC, JohnNiang commented on src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
> +            .switchIfEmpty(Mono.defer(() -> client.fetch(User.class, GHOST_USER_NAME)));
这里建议调用 `client#get`。这里得假设 ghost 用户永远存在。

2023-02-24 03:25 UTC, guqing commented on src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
> +            .switchIfEmpty(Mono.defer(() -> client.fetch(User.class, GHOST_USER_NAME)));
good catch

2023-02-24 03:44 UTC, JohnNiang requested changes

2023-02-24 03:44 UTC, JohnNiang commented on src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
>              .defaultIfEmpty(OwnerInfo.ghostUser());
建议移除 defaultIfEmpty。

2023-02-24 03:44 UTC, JohnNiang commented on src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
>                  .switchIfEmpty(Mono.just(OwnerInfo.ghostUser()));
建议移除 switchIfEmpty。

2023-02-24 04:36 UTC, JohnNiang approved these changes
/approve

2023-02-24 06:22 UTC, ruibaby approved these changes
/lgtm

2023-02-24 06:24 UTC, merged