feat: add indexer implementation to solve the slow tag stats
halo-dev/halo pull request #3420
Opened 2023-02-28 04:34 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.3.x

#### What this PR does / why we need it:
修复标签关联文章数量统计不正确的问题
1. 实现简要的 Indexer 可以通过 IndexFunc 来提取需要构建 indacates 的信息，比如对文章的标签和 labels 建立 indacates
2. Indexer 通过 Watch 文章数据来维护 Indicates 使其与数据库一致
3. TagReconciler 一分钟 requeue 一次，但直接通过 Indexer 获取文章名称来统计数量，无需 list 文章数据

how to test it?
1. 创建文章并绑定标签
2. 测试文章解绑标签，关联新标签等操作是否会在一分钟后在标签处正确显示文章数量

#### Which issue(s) this PR fixes:
Fixes #3311

#### Does this PR introduce a user-facing change?

```release-note
修复标签关联文章数量统计不正确的问题，优化统计速度
```

2023-02-28 15:51 UTC, JohnNiang reviewed
Indexer 的设计有参考过什么文档或者什么项目么？

2023-02-28 15:54 UTC, JohnNiang requested changes

2023-02-28 16:22 UTC, guqing commented
> Indexer 的设计有参考过什么文档或者什么项目么？

参考过这篇文章的一些思路：https://juejin.cn/post/7132767272841510926

2023-02-28 16:23 UTC, guqing commented on src/test/java/run/halo/app/content/DefaultIndexerTest.java
> +        assertEquals("[post-1, post-2]", t2PostNames.toString());
> 这里的 postNames 的排序似乎不稳定。
> 
> 
> 
> <img width="831" alt="image" src="https://user-images.githubusercontent.com/16865714/221906946-0474b3ad-73eb-4ee3-b035-2707142f9b60.png">
> 
> 

ok 我明天改一下 断言应该用contains

2023-03-01 03:38 UTC, ruibaby approved these changes
/approve

2023-03-01 03:43 UTC, JohnNiang approved these changes
/approve

2023-03-01 03:43 UTC, ruibaby reviewed
/lgtm

2023-03-01 03:44 UTC, merged