fix: the rawType of Content was not updated when switching editors
halo-dev/halo pull request #3516
Opened 2023-03-14 11:42 UTC by intoyang

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #3512 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2023-03-14 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=3516) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=3516) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=3516) it.</sub>

2023-03-14 11:47 UTC, LIlGG commented
@intoyang  需要签署一下 CLA

2023-03-14 13:43 UTC, ruibaby commented
这里也需要修改一下：https://github.com/halo-dev/halo/blob/f43888bc2c4c6f7a96cc5da8e3d7f7346985d8ec/console/src/modules/contents/pages/SinglePageEditor.vue#L45-L51

2023-03-14 13:57 UTC, ruibaby requested changes

2023-03-14 13:57 UTC, ruibaby commented on console/src/modules/contents/posts/PostEditor.vue
> +  formState.value.content.rawType = provider.rawType
```suggestion
  formState.value.content.rawType = provider.rawType;
```

2023-03-15 03:03 UTC, ruibaby requested changes

2023-03-15 03:03 UTC, ruibaby commented on console/src/modules/contents/pages/SinglePageEditor.vue
> +  formState.value.content.rawType = provider.rawType
```suggestion
  formState.value.content.rawType = provider.rawType;
```

2023-03-15 03:05 UTC, ruibaby approved these changes
/approve

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/21301288/225194903-5b6ca726-e850-4165-91f0-d15588ac91c7.png">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/21301288/225194950-8d322b8f-239c-4ce6-9933-a400ee70d99f.png">

2023-03-15 03:10 UTC, JohnNiang approved these changes
/lgtm

2023-03-15 03:12 UTC, merged

2023-03-15 05:23 UTC, wan92hen commented
cherry pick release-2.3?