feat: add supports for clicking the visibility icon in the post list to modify visibility
halo-dev/halo pull request #3581
Opened 2023-03-24 10:22 UTC by 123abcabcabcabcba

#### What type of PR is this?

/kind improvement
/area console

#### What this PR does / why we need it:

通过点击“眼睛”图标，可以比较方便地修改文章或者页面的可视性。
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/114651359/227491296-5f96e605-1137-4f6f-b506-d33b329045fc.png">

#### Which issue(s) this PR fixes:

Ref #3501 

#### Special notes for your reviewer:

1.修改了两个页面，路径为：
（1）console/src/modules/contents/pages/SinglePageList.vue
（2）console/src/modules/contents/posts/PostList.vue
2.原本“眼睛”图标是没有设置点击事件的，现在添加了点击改变选中文章或页面可视性的功能。

#### Does this PR introduce a user-facing change?

```release-note
action required  当用户点击“眼睛”图标时，会提示用户“可视化修改成功”
```

2023-03-24 15:28 UTC, JohnNiang commented on console/src/modules/contents/posts/PostList.vue
> +  Toast.success("可见性修改成功");
这里的 message 可能需要适配一下 i18n。

2023-03-25 02:51 UTC, ruibaby requested changes

2023-03-25 02:51 UTC, ruibaby commented on console/src/modules/contents/posts/PostList.vue
> +  const singlePostToUpdate = cloneDeep(post);
在修改之前，是否需要一个 Dialog 来让用户二次确认？以防止误操作。

2023-03-25 02:51 UTC, ruibaby commented on console/src/modules/contents/posts/PostList.vue
> +  selectedPost.value = data;
这里给 selectedPost 设置值的目的是？

2023-03-25 04:21 UTC, 123abcabcabcabcba commented on console/src/modules/contents/posts/PostList.vue
> +  const singlePostToUpdate = cloneDeep(post);
感觉不需要吧，这样比较方便，就算误点了，也可以马上改回来

2023-03-25 04:25 UTC, 123abcabcabcabcba commented on console/src/modules/contents/posts/PostList.vue
> +  selectedPost.value = data;
因为每一次后台对数据进行更新，该数据的version就会加1，如果不重新从后台对该数据进行获取的话，下次进行更新的时候就会由于版本号不同而找不到数据。

2023-03-25 04:27 UTC, 123abcabcabcabcba commented on console/src/modules/contents/posts/PostList.vue
> +  Toast.success("可见性修改成功");
抱歉，具体是要怎么适配，不太明白呐

2023-03-25 06:02 UTC, ruibaby commented on console/src/modules/contents/posts/PostList.vue
> +  selectedPost.value = data;
那这里仅需调用 refresh 即可，selectedPost 代表的当前选择的文章用于给设置弹窗数据，但如果打开的不是这文章呢？

2023-03-25 07:15 UTC, 123abcabcabcabcba commented on console/src/modules/contents/posts/PostList.vue
> +  selectedPost.value = data;
ok， 我可以试试

2023-03-27 03:17 UTC, ruibaby commented on console/src/modules/contents/posts/PostList.vue
> +  Toast.success("可见性修改成功");
参考：https://github.com/halo-dev/halo/pull/3506

2023-03-28 08:52 UTC, JohnNiang approved these changes
Thank you for your first contribution!

It works very well.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/16865714/228182830-26126a90-36c6-4121-8d27-62a5dcf91279.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/16865714/228183076-129f6f24-6642-48d1-9861-c66bd9a4f01c.png">

/approve

2023-03-29 03:43 UTC, ruibaby reviewed
/lgtm

2023-03-29 03:43 UTC, ruibaby approved these changes

2023-03-29 03:52 UTC, merged