[WIP] feat: add public APIs for client side
halo-dev/halo pull request #3787
Opened 2023-04-19 04:44 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/milestone 2.5.x
/kind api-change

#### What this PR does / why we need it:
为客户端提供一套 APIs

#### Which issue(s) this PR fixes:
Fixes #3661

#### Does this PR introduce a user-facing change?
```release-note
为访客端提供一套完整的 API
```

2023-04-23 03:33 UTC, LIlGG requested changes
## 菜单
1、请求 `/apis/api.halo.run/v1alpha1/menus/-` 
报错提示 `No path variable with name "name" available`

2、菜单中的层级关系没有表示出来
<details>
  <summary>层级关系如下</summary>
![image](https://user-images.githubusercontent.com/31335418/233818282-1bbf9d8d-3805-4337-83c5-a29a27093dda.png)
返回数据中 `children` 为空
![image](https://user-images.githubusercontent.com/31335418/233818291-cf3b1c7c-cbfa-487b-8716-cd6be57f02d5.png)
<details>

2023-04-23 04:08 UTC, LIlGG requested changes

2023-04-23 04:08 UTC, LIlGG commented on application/src/main/java/run/halo/app/theme/endpoint/SinglePageQueryEndpoint.java
> +            );
此处应该校验一下是否存在对应的 `singlePage`，不存在则返回 `NotFoundException`。

2023-04-23 04:17 UTC, LIlGG reviewed
是否应该提供一个 `/apis/api.content.halo.run/v1alpha1/tags/{name}` 接口？

2023-04-23 04:59 UTC, guqing commented on application/src/main/java/run/halo/app/theme/endpoint/SinglePageQueryEndpoint.java
> +            );
> 此处应该校验一下是否存在对应的 `singlePage`，不存在则返回 `NotFoundException`。

Done

2023-04-23 04:59 UTC, guqing commented
> 是否应该提供一个 `/apis/api.content.halo.run/v1alpha1/tags/{name}` 接口？

可以，加了

2023-04-23 06:40 UTC, guqing commented
> 2、菜单中的层级关系没有表示出来 层级关系如下： 

已修

2023-04-23 08:19 UTC, LIlGG approved these changes

2023-04-24 09:23 UTC, ruibaby reviewed
/lgtm

2023-04-24 12:16 UTC, merged