refactor: add custom API for create user
halo-dev/halo pull request #3803
Opened 2023-04-21 04:51 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.5.x
/kind api-change

#### What this PR does / why we need it:
提供自定义 API 用于创建用户账号
简化了创建用户账号需要先创建账号，再分配角色再重置密码的复杂流程。
需要 Console 端适配此 PR

#### Which issue(s) this PR fixes:
Fixes #2852

#### Does this PR introduce a user-facing change?
```release-note
优化用户账号创建流程
```

2023-04-21 08:15 UTC, ruibaby commented
> 需要 Console 端适配此 PR

Done

2023-04-21 09:47 UTC, ruibaby approved these changes
/approve

2023-04-23 03:04 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +    record CreateUserRequest(@Schema(requiredMode = REQUIRED) String name,
这里建议“创建”和“更新”都用同一个 Request。

2023-04-23 03:04 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +                             Map<String, String> additionalAttributes,
建议直接命名为 annotations。和 user.metadata.annotations 保持一致可以减少理解成本。

2023-04-23 03:04 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
> +                    .onErrorMap(throwable -> {
这里用 fetch + switchIfEmpty 会不会更好呢。

2023-04-23 03:11 UTC, LIlGG requested changes
测试发现如下问题/建议：
1、新增用户时，角色默认为“请选择角色”，但并未设置正常的默认项且未提示必须更改，用户直接提交时报错 400。
![image](https://user-images.githubusercontent.com/31335418/233817328-60d1ae4b-3e6b-4a48-83f4-ea51ef23d877.png)

可以将默认的“请选择角色”改为访客。

2、建议将表单中必填项位置集中，例如将新密码位置移动到电子邮箱后，非必填项可以往后移动。

2023-04-23 03:45 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +    record CreateUserRequest(@Schema(requiredMode = REQUIRED) String name,
> 这里建议“创建”和“更新”都用同一个 Request。

目前没有给管理员用的更新用户信息的 API，只有更新 profile 的

2023-04-23 04:31 UTC, guqing commented
> 

去掉了角色必选的校验，用户可以后续设置

2023-04-23 04:32 UTC, guqing commented
> 测试发现如下问题/建议： 1、新增用户时，角色默认为“请选择角色”，但并未设置正常的默认项且未提示必须更改，用户直接提

去掉了角色必选的校验，用户可以后续设置

2023-04-23 04:32 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
> +                    .onErrorMap(throwable -> {
> 这里用 fetch + switchIfEmpty 会不会更好呢。

Done🫡

2023-04-23 04:32 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +                             Map<String, String> additionalAttributes,
> 建议直接命名为 annotations。和 user.metadata.annotations 保持一致可以减少理解成本。

好的

2023-04-23 07:06 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
> +                            "There is some illegal data in the roles parameter"))
这里建议给出直接的提示，而不是模糊的。例如“对应的角色未找到”。

2023-04-23 07:09 UTC, JohnNiang reviewed
未设置角色的时候 roleNames 为空字符串。创建用户的请求体如下：

```json
{
  "avatar": "",
  "bio": "",
  "displayName": "Demo",
  "email": "demo@demo.com",
  "name": "demo",
  "password": "demo",
  "phone": "",
  "roles": [
    ""
  ]
}
```

2023-04-23 08:36 UTC, ruibaby commented
> 未设置角色的时候 roleNames 为空字符串。创建用户的请求体如下：

Fixed

2023-04-24 07:36 UTC, JohnNiang approved these changes
/approve

2023-04-24 07:48 UTC, ruibaby approved these changes
/lgtm

2023-04-24 08:18 UTC, LIlGG approved these changes

2023-04-24 08:19 UTC, merged