fix: plugin startup failed issue on Windows system
halo-dev/halo pull request #3925
Opened 2023-05-10 03:08 UTC by guqing

#### What type of PR is this?
/kind bug
/area core
/milestone 2.6.x

#### What this PR does / why we need it:
修复在 Windows 系统无法启动插件的问题

how to test it?
1. 使用 windows 系统环境测试插件开发模式和生成模式是否正常工作
2. 测试从 2.0.0 版本安装插件然后切换到此 PR 后插件不会出现找不到文件的错误
3. 测试插件安装和升级是否正常

#### Which issue(s) this PR fixes:
Fixes #3906

#### Does this PR introduce a user-facing change?
```release-note
修复在 Windows 系统无法启动插件的问题
```

2023-05-10 11:33 UTC, LIlGG requested changes

2023-05-10 11:33 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +        return Paths.get(processedPathString);
经过测试，这种方案并不可行。会报错
```
java.lang.IllegalArgumentException: character to be escaped is missing
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1019) ~[na:na]
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[na:na]
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[na:na]
	at java.base/java.lang.String.replaceAll(String.java:2940) ~[na:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.toPath(PluginReconciler.java:633) ~[main/:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.buildPluginLocation(PluginReconciler.java:590) ~[main/:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.determinePluginLocation(PluginReconciler.java:754) ~[main/:na]
	at run.halo.app.core.extension.reconciler.PluginReconciler.lambda$ensurePluginLoaded$19(PluginReconciler.java:620) ~[main/:na]
```

不过如果最终结果是返回 Path 而不需要经过 URI 转换的话，可以直接修改为
```suggestion
       return Paths.get(pathString);
```

测试示例代码不再会报错。

2023-05-10 12:26 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +        return Paths.get(processedPathString);
出错的 pathString 值是什么

2023-05-10 12:38 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +        return Paths.get(processedPathString);
在试试

2023-05-10 13:55 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +        return Paths.get(processedPathString);
> 在试试

ok，没有问题。

2023-05-10 13:56 UTC, LIlGG approved these changes

2023-05-10 14:23 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +        if (processedPathString.startsWith("file:")) {
> 这里我有一个疑问：为什么 pathString 会有 `file:` 开头的情况呢？

之前的 `Paths.get(URI.create(pathString).getPath());` 写法就是为了忽略协议，但是我忘了是为什么，所以只能兼容一下了，怕改出问题

2023-05-11 15:52 UTC, JohnNiang requested changes

2023-05-11 15:52 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +            processedPathString = processedPathString.substring(7);
建议用 `org.springframework.util.StringUtils#cleanPath` 替换这里的操作。

2023-05-12 02:26 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +            processedPathString = processedPathString.substring(7);
cleanPath 并不会去除文件协议，所以无法替换这里

2023-05-12 18:33 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
> +            processedPathString = processedPathString.substring(7);
这里无需去除文件协议。我这里实测可以正常转换为 Path，并正常运行插件。

2023-05-15 03:43 UTC, JohnNiang approved these changes
/lgtm

2023-05-15 03:44 UTC, merged

2023-05-15 07:46 UTC, ruibaby commented
/cherry-pick release-2.5