feat: add the ability to install themes remotely via URI
halo-dev/halo pull request #3939
Opened 2023-05-12 08:59 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.6.x
/kind api-change

#### What this PR does / why we need it:
支持通过 URL 远程安装和升级主题

how to test it?
1. 测试主题安装
```shell
curl -u admin:admin -X POST http://localhost:8090/apis/api.console.halo.run/v1alpha1/themes/-/install-from-uri --data '{
  "uri": "https://halo.run/apis/api.store.halo.run/v1alpha1/applications/app-eiTyL/releases/app-release-QSyjc/download/app-release-QSyjc-JOSOB"
}'
```
2. 测试主题升级
```shell
curl -u admin:admin -X POST http://localhost:8090/apis/api.console.halo.run/v1alpha1/themes/guqing-higan/upgrade-from-uri --data '{
  "uri": "https://halo.run/apis/api.store.halo.run/v1alpha1/applications/app-eiTyL/releases/app-release-QSyjc/download/app-release-QSyjc-JOSOB"
}'
```
#### Which issue(s) this PR fixes:

Fixes #2219

#### Does this PR introduce a user-facing change?
```release-note
支持通过 URL 远程安装和升级主题
```

2023-05-15 06:03 UTC, ruibaby requested changes

2023-05-15 06:03 UTC, ruibaby commented on application/src/main/java/run/halo/app/infra/exception/ThemeAlreadyExistsException.java
> +    public static final String PLUGIN_ALREADY_EXISTS_TYPE =
```suggestion
    public static final String THEME_ALREADY_EXISTS_TYPE =
```

2023-05-15 06:03 UTC, ruibaby commented on application/src/main/java/run/halo/app/infra/exception/ThemeAlreadyExistsException.java
> +        setType(URI.create(PLUGIN_ALREADY_EXISTS_TYPE));
```suggestion
        setType(URI.create(THEME_ALREADY_EXISTS_TYPE));
```

2023-05-15 06:20 UTC, ruibaby reviewed
/lgtm

2023-05-15 06:40 UTC, guqing commented on application/src/main/java/run/halo/app/infra/exception/ThemeAlreadyExistsException.java
> +        setType(URI.create(PLUGIN_ALREADY_EXISTS_TYPE));
good catch🫡

2023-05-16 10:12 UTC, ruibaby approved these changes
/approve

2023-05-17 09:25 UTC, ruibaby commented
cc @halo-dev/sig-halo

2023-05-17 15:35 UTC, JohnNiang commented on application/src/main/java/run/halo/app/infra/ZipStreamFetcher.java
> +    Mono<InputStream> fetch(URI uri);
这里推荐返回 Flux<DataBuffer>。

2023-05-17 15:35 UTC, JohnNiang commented on application/src/main/java/run/halo/app/infra/ZipStreamFetcher.java
> +public interface ZipStreamFetcher {
从这个方法的功能来看，似乎和 ZIP 没有关系。从 URI 中获取的数据似乎也不是 ZIP InputStream。

2023-05-19 02:10 UTC, JohnNiang approved these changes
/lgtm

2023-05-19 02:10 UTC, merged

2023-06-23 16:49 UTC, StrawHat179 commented
![image](https://github.com/halo-dev/halo/assets/104472839/f404cc3b-e82b-48ce-a82f-afe1d67e7384)
远程安装主题报错，

2023-06-23 16:50 UTC, StrawHat179 commented
![image](https://github.com/halo-dev/halo/assets/104472839/a18ff3ec-404f-40e2-b292-37fb6cd7b6d4)
远程安装主题报错