feat: add the ability to install plugins remotely via URI
halo-dev/halo pull request #3963
Opened 2023-05-17 09:49 UTC by guqing

#### What type of PR is this?
/kind feature
/area core
/area console
/milestone 2.6.x
/kind api-change

#### What this PR does / why we need it:
支持通过 URI 远程安装和升级插件

how to test it?
1. 测试插件安装
```shell
curl -u admin:admin -X POST http://localhost:8090/apis/api.console.halo.run/v1alpha1/plugins/-/install-from-uri --data '{
  "uri": "https://halo.run/apis/api.store.halo.run/v1alpha1/applications/app-KhIVw/releases/app-release-canxF/download/app-release-canxF-znFre"
}'
```
2. 测试主题升级
```shell
curl -u admin:admin -X POST http://localhost:8090/apis/api.console.halo.run/v1alpha1/plugins/PluginFeed/upgrade-from-uri --data '{
  "uri": "https://halo.run/apis/api.store.halo.run/v1alpha1/applications/app-KhIVw/releases/app-release-canxF/download/app-release-canxF-znFre"
}'
```
#### Which issue(s) this PR fixes:
Fixes #2292

#### Does this PR introduce a user-facing change?
```release-note
支持通过 URI 远程安装和升级插件
```

2023-05-19 04:21 UTC, guqing commented
/unhold

2023-05-19 04:53 UTC, ruibaby approved these changes
/approve

2023-05-25 13:27 UTC, JohnNiang requested changes

2023-05-25 13:27 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
> +            .doOnError(throwable -> {
这里建议用 `reactor.core.publisher.Mono#onErrorMap(java.util.function.Function<? super java.lang.Throwable,? extends java.lang.Throwable>)`。

2023-05-25 14:22 UTC, JohnNiang requested changes

2023-05-25 14:22 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
> +        });
这里涉及到阻塞操作（文件复制），建议使用 subscribeOn。

需要注意的是：主题安装那边可能也有类似的问题。

2023-05-26 03:16 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
> +        });
good catch, For more details, refer to https://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking
<img width="1183" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/a960f8d7-c6d0-48fc-969f-c27cf4018116">

2023-05-26 14:24 UTC, JohnNiang approved these changes
/approve

2023-05-26 14:51 UTC, ruibaby approved these changes
/lgtm

2023-05-26 14:54 UTC, merged