feat: supports redirecting to a specified page after successful login
halo-dev/halo pull request #3984
Opened 2023-05-23 04:16 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/area console
/milestone 2.6.x

#### What this PR does / why we need it:
登录成功后支持跳转到指定页面

登录 API `POST /login` 支持携带查询参数 `redirect_uri` 跳转到同源 URI
 
#### Which issue(s) this PR fixes:

Fixes #3982

#### Does this PR introduce a user-facing change?

```release-note
登录成功后支持跳转到指定页面
```

2023-05-25 14:56 UTC, JohnNiang requested changes

2023-05-25 14:56 UTC, JohnNiang commented on application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
> +                .switchIfEmpty(redirectToOriginalUrl(webFilterExchange));
这个 switchIfEmpty 应该移动到 flatMap 上方。可参考修改前的代码。

如果上方的 flatMap 返回了 Mono.empty() 则会导致跳转，这不是期望的行为。

2023-05-26 02:54 UTC, guqing commented
/hold
这个 PR 好像用不上了，Console 端自己跳转页面了 #3989， 因此先搁置吧

2023-06-21 03:44 UTC, guqing commented
已在 Console 端实现了跳转页面了 https://github.com/halo-dev/halo/pull/3989， 因此我将关闭此 PR

2023-06-21 03:44 UTC, closed without merging