refactor: content page meta tags now override global injected
halo-dev/halo pull request #4069
Opened 2023-06-13 04:51 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.7.x

#### What this PR does / why we need it:
修复文章页 HTML Meta 标签重复问题

see #4049 for more details.

#### Which issue(s) this PR fixes:

Fixes #4049

#### Does this PR introduce a user-facing change?

```release-note
修复文章页 HTML Meta 标签重复问题
```

2023-06-14 04:23 UTC, ruibaby commented
/cherry-pick release-2.6

2023-06-14 04:25 UTC, ruibaby reviewed
/lgtm

2023-06-26 15:01 UTC, LIlGG commented
/lgtm

![image](https://github.com/halo-dev/halo/assets/31335418/1e268bf4-7ffa-40ce-acae-22b452ef1fd9)

2023-06-28 08:54 UTC, JohnNiang requested changes

2023-06-28 08:54 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
> +            .doOnNext(htmlMetas -> {
推荐单独写一个 TemplateHeadProcessor 来处理重复的 meta。

2023-06-28 08:54 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        model.add(closeHeadTag);
可直接调用 org.thymeleaf.model.IModel#addModel 方法。

2023-06-28 13:58 UTC, guqing commented on application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
> +            .doOnNext(htmlMetas -> {
ok

2023-06-28 13:58 UTC, guqing commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        model.add(closeHeadTag);
done

2023-06-28 13:59 UTC, guqing commented
建议在全局注入添加几行 meta 测试
<img width="852" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/647108ae-2fe8-44f0-a9f5-b549fe5d597a">

/cc @halo-dev/sig-halo

2023-06-28 14:54 UTC, merged