WIP:refactor:add support for user avatar upload
halo-dev/halo pull request #4253
Opened 2023-07-18 09:32 UTC by LIlGG

#### What type of PR is this?

/kind improvement
/area console
/area core

#### What this PR does / why we need it:

此 PR 对用户头像上传的方式进行了重构，移除了原有的头像链接及上传至附件库的方案。

Core: 
新增了 `/apis/api.console.halo.run/v1alpha1/users/-/avatar` 的 `POST` 以及 `DELETE` 接口，用来上传用户的头像及删除当前用户的头像。

Console:
新增对用户头像进行裁剪的功能，并调用上传接口保存当前用户头像。

#### Which issue(s) this PR fixes:

Fixes #2688 

#### Special notes for your reviewer:

1. 测试上传、删除头像接口是否能够正常执行。
2. 查看当前用户的头像是否能够设置成功。
3. 查看附件库中，当前用户的头像文件是否为 0 或 1 个。

#### Does this PR introduce a user-facing change?

```release-note
支持用户头像裁剪、上传。
```

2023-07-19 13:04 UTC, ruibaby commented
本地尝试了一下，有几个建议：

1. cropperjs 似乎有点大，建议将组件异步加载。
2. 裁剪区域期望添加放大和缩小图片的按钮。
3. 预览区域建议添加多个尺寸的预览图，包括纯圆形。
4. 裁剪弹窗建议支持直接换图片。

2023-07-20 07:17 UTC, LIlGG commented
/retitle refactor:add support for user avatar upload

2023-07-20 07:35 UTC, LIlGG commented
/hold 缺少修改其他用户头像的方式

2023-07-20 08:26 UTC, JohnNiang requested changes
- [ ] 用户头像的文件名建议用 UUID 替代。
- [ ] 删除头像时建议增加确认步骤。
- [ ] 期望拥有用户管理权限的用户能够操作其他用户头像。

2023-07-20 10:17 UTC, LIlGG commented
> * [x]  用户头像的文件名建议用 UUID 替代。
> * [x]  删除头像时建议增加确认步骤。
> * [x]  期望拥有用户管理权限的用户能够操作其他用户头像。

已对功能进行补充，并且完善了移动端样式。

2023-07-20 10:20 UTC, LIlGG commented
/unhold

2023-07-21 08:03 UTC, ruibaby requested changes

2023-07-21 08:03 UTC, ruibaby commented on application/src/main/resources/extensions/system-setting.yaml
> +        - $formkit: number
我建议先在内部规定一个上传大小即可，这个配置可能很少会用到，我认为不是很有必要。

2023-07-21 08:31 UTC, ruibaby requested changes

2023-07-21 08:31 UTC, ruibaby commented on console/src/modules/system/users/layouts/UserProfileLayout.vue
> +                      {{ $t("core.user.detail.avatar.upload.button") }}
可以直接用 `core.common.button.upload`

2023-07-21 08:48 UTC, LIlGG commented on console/src/modules/system/users/layouts/UserProfileLayout.vue
> +                      {{ $t("core.user.detail.avatar.upload.button") }}
已改为 `core.common.button.upload`

2023-07-21 08:49 UTC, LIlGG commented on application/src/main/resources/extensions/system-setting.yaml
> +        - $formkit: number
用户端确实不怎么能用到这个配置，已经移除此配置。
头像附件存储策略已改名为 头像存储位置

2023-07-21 09:57 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +                if (totalSize + byteCount > DEFAULT_AVATAR_FILE_SIZE * 1024 * 1024) {
已修改

2023-07-21 10:11 UTC, JohnNiang reviewed
Hi @LIlGG , PTAL

2023-07-21 10:11 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +    private Mono<Void> checkAvatar(AvatarUploadRequest uploadRequest) {
这里的 checkAvatar 的逻辑会造成前后两次读取文件内容。我这里给出一个可行的方案作为参考：

```java
    private Mono<Attachment> uploadAvatar(AvatarUploadRequest uploadRequest) {
        return environmentFetcher.fetch(SystemSetting.User.GROUP, SystemSetting.User.class)
            .switchIfEmpty(
                Mono.error(new IllegalStateException("User setting is not configured"))
            )
            .flatMap(userSetting -> (Mono.defer(
                    () -> {
                        String avatarPolicy = userSetting.getAvatarPolicy();
                        if (StringUtils.isBlank(avatarPolicy)) {
                            avatarPolicy = DEFAULT_USER_AVATAR_ATTACHMENT_POLICY_NAME;
                        }
                        FilePart filePart = uploadRequest.getFile();
                        var ext = Files.getFileExtension(filePart.filename());
                        return attachmentService.upload(avatarPolicy,
                            USER_AVATAR_GROUP_NAME,
                            UUID.randomUUID() + "." + ext,
                            maxSizeCheck(filePart.content()),
                            filePart.headers().getContentType()
                        );
                    })
                )
            );
    }

    private Flux<DataBuffer> maxSizeCheck(Flux<DataBuffer> content) {
        var lenRef = new AtomicInteger(0);
        return content.doOnNext(dataBuffer -> {
            int len = lenRef.accumulateAndGet(dataBuffer.readableByteCount(), Integer::sum);
            if (len > MAX_AVATAR_FILE_SIZE.toBytes()) {
                throw new ServerWebInputException("The avatar file needs to be smaller than "
                    + MAX_AVATAR_FILE_SIZE.toKilobytes() + " KB.");
            }
        });
    }
```

2023-07-24 02:16 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
> +    private Mono<Void> checkAvatar(AvatarUploadRequest uploadRequest) {
已经更改为上述方案，非常好用。

2023-07-24 07:39 UTC, JohnNiang approved these changes
/approve

It works very well.

<img width="507" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/c869395e-600d-49e7-bf65-855afb204738">

2023-07-24 07:44 UTC, ruibaby reviewed
/lgtm

2023-07-24 08:04 UTC, guqing reviewed
/lgtm

2023-07-24 08:05 UTC, ruibaby approved these changes

2023-07-24 08:08 UTC, merged