fix: add random uuid to resolve the issue of id conflicts
halo-dev/halo pull request #4371
Opened 2023-08-03 07:42 UTC by LIlGG

#### What type of PR is this?

/kind bug
/area console

#### What this PR does / why we need it:

为 AnnotationsForm 的 formkit 表单 id 增加 uuid 前缀，防止由于一个页面具有多个 AnnotationsForm 时编号互相冲突。

#### Which issue(s) this PR fixes:

Fixes #4368 

#### Special notes for your reviewer:

检查使用 AnnotationsForm 的界面，例如文章、页面设置的元数据处没有出现问题即可。

#### Does this PR introduce a user-facing change?
```release-note
None
```

2023-08-03 07:47 UTC, ruibaby requested changes

2023-08-03 07:47 UTC, ruibaby commented on console/src/components/form/AnnotationsForm.vue
> +const uuid = ref();
```suggestion
const uuid = randomUUID();
```

2023-08-03 07:48 UTC, ruibaby commented on console/src/components/form/AnnotationsForm.vue
> +const uuid = ref();
直接在组件初始化的时候调佣 randomUUID 就行了，没有必要使用 ref

2023-08-03 08:08 UTC, ruibaby reviewed
/lgtm

2023-08-04 03:00 UTC, guqing reviewed
/lgtm

2023-08-04 03:00 UTC, ruibaby approved these changes
/lgtm

2023-08-04 03:11 UTC, merged