Add Spanish (ES) locale
halo-dev/halo pull request #4460
Opened 2023-08-23 02:19 UTC by yosoyjaff

#### What type of PR is this?

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
```

2023-08-23 02:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=4460) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=4460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=4460) it.</sub>

2023-08-24 13:07 UTC, ruibaby requested changes
Thanks for your contribution, here are some of the problems I found.

BTW, If you use vscode, [this plugin](https://marketplace.visualstudio.com/items?itemName=Lokalise.i18n-ally) may help you

<img width="532" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/ba4c882f-6dd8-432e-9839-a326c772fe1a">

2023-09-01 02:38 UTC, JohnNiang reviewed
/lgtm

2023-09-01 02:40 UTC, ruibaby approved these changes
/approve

2023-09-01 02:48 UTC, merged