Prompt when links have duplicate names
halo-dev/halo pull request #4488
Opened 2023-08-25 09:39 UTC by GodlessLiu

#### What type of PR is this?
/kind improvement
/kind console

#### What this PR does / why we need it:
为一个菜单添加一个已经存在的链接时，添加提示信息
#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/4485

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
为一个菜单添加一个已经存在的自定义链接时，显示提示信息
```

2023-08-25 14:47 UTC, JohnNiang reviewed
I got the following errors in browser console after updating any menu:

```js
vue.global.f0e8f02d.js:1516 [Vue warn]: Invalid prop: type check failed for prop "parentMenuItem". Expected Object, got Undefined  
  at <MenuItemEditingModal visible=false onUpdate:visible=fn menu-item=undefined  ... > 
  at <Menus onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView key=1 > 
  at <BasicLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <App>

vue.global.f0e8f02d.js:1516 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Menus onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView key=1 > 
  at <BasicLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {__v_skip: true} > > 
  at <RouterView> 
  at <App>

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (vue.global.f0e8f02d.js:2459:29)
    at updateComponent (vue.global.f0e8f02d.js:7032:11)
    at processComponent (vue.global.f0e8f02d.js:6980:9)
    at patch (vue.global.f0e8f02d.js:6455:13)
    at patchBlockChildren (vue.global.f0e8f02d.js:6842:9)
    at processFragment (vue.global.f0e8f02d.js:6930:11)
    at patch (vue.global.f0e8f02d.js:6429:11)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.global.f0e8f02d.js:7177:11)
    at ReactiveEffect.run (vue.global.f0e8f02d.js:497:21)
    at instance.update (vue.global.f0e8f02d.js:7218:53)
```

2023-08-25 15:08 UTC, GodlessLiu commented
hi, @JohnNiang, 能否给我录个视频，因为在我的windows电脑上显示一切正常

2023-08-25 15:44 UTC, LIlGG requested changes

2023-08-25 15:44 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuEditingModal.vue
> +);
```suggestion

```

未修改父组件传递的属性时，无需创建副本

2023-08-25 15:44 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuEditingModal.vue
> +);
```suggestion
const warning = computed(() => {
  for (const menu of props.menus as Menu[]) {
    if (menu.spec.displayName === formState.value.spec.displayName) {
      return true;
    }
  }
  return false;
});
```
直接使用计算属性即可

2023-08-25 15:44 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuItemEditingModal.vue
> +import type { MenuTreeItem } from "../utils";
同上，无需修改位置。

2023-08-25 15:44 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuItemEditingModal.vue
> +);
```suggestion

```
无需新增副本

2023-08-25 15:44 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuItemEditingModal.vue
> +);
这里应该也可以使用计算属性进行处理。

2023-08-28 04:10 UTC, LIlGG commented on console/src/modules/interface/menus/components/MenuItemEditingModal.vue
> +    menuTreeItems?: MenuTreeItem[];
这里传入原始类型可能更好处理一些，而不是去处理树状结构。

https://github.com/halo-dev/halo/blob/e149d369f400b009f14c6e4a6aaa1634411ee85f/console/src/modules/interface/menus/Menus.vue#L62-L64

2023-09-08 08:15 UTC, ruibaby requested changes

2023-09-08 08:15 UTC, ruibaby commented on console/src/modules/interface/menus/Menus.vue
> +const menuOriginItems = ref<MenuItem[]>();
下面已有 menuItems，不需要新建一个变量。

2023-10-11 10:32 UTC, ruibaby commented
感谢 @GodlessLiu 的贡献，考虑之后感觉这个修改不是特别有必要。重复的名称和链接在逻辑上并不会有任何错误，所以我将关闭此 PR。

/close

2023-10-11 10:32 UTC, closed without merging