listen  command+s/ctrl+s  to save post
halo-dev/halo pull request #4510
Opened 2023-08-29 06:07 UTC by GodlessLiu

#### What type of PR is this?
/area editor
/area console

#### What this PR does / why we need it:
1. mac: 在编辑器中添加command+s保存文章
2. windows: 在编辑器中添加ctrl+s保存文章
#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/4340

#### Does this PR introduce a user-facing change?

```release-note
1. mac: 在编辑器中添加command+s保存文章
2. windows: 在编辑器中添加ctrl+s保存文章
```

2023-08-31 03:13 UTC, ruibaby reviewed
SinglePageEditor 应该也需要支持，所以建议封装一个通用的方法。

2023-08-31 03:26 UTC, LIlGG requested changes
需要在组件销毁时，取消注册 `handleSaveKeybinding` 事件，否则退出页面后事件仍旧存在。
或者仅对当前组件绑定 keydown 事件。

2023-08-31 03:27 UTC, ruibaby commented
> 

 似乎可以交给 useEventListener 来处理：https://vueuse.org/core/useEventListener/#useeventlistener

2023-08-31 06:27 UTC, ruibaby reviewed
/lgtm

2023-08-31 10:41 UTC, JohnNiang commented on console/src/composables/use-save-keybinding.ts
> +        nextTick();
`await nextTick()` or `nextTick(() -> debouncedFn())`?

2023-08-31 14:33 UTC, ruibaby reviewed
/approve

2023-09-01 02:28 UTC, LIlGG approved these changes
/lgtm

2023-09-01 02:30 UTC, merged