[WIP] feat: add the notification mechanism implementation
halo-dev/halo pull request #4527
Opened 2023-08-31 04:43 UTC by guqing

#### What type of PR is this?
/kind feature
/milestone 2.10.x
/area core

#### What this PR does / why we need it:
新增消息和通知机制的实现

#### Which issue(s) this PR fixes:
Fixes #4045

#### Does this PR introduce a user-facing change?
```release-note
新增消息和通知机制的实现
```

2023-09-20 04:38 UTC, guqing commented
/ping @halo-dev/sig-halo

2023-09-24 12:57 UTC, ruibaby requested changes

2023-09-24 12:57 UTC, ruibaby commented on application/src/main/resources/extensions/notification-templates.yaml
> +          <p class="content" th:text="${content}"></p>
邮件正文内容建议使用 pre 标签。

<img width="1048" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/0e81b160-a6c0-4abf-ab97-6e1ac9754d07">
<img width="1137" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/2e974206-7a91-4741-8e2c-346086d2470c">

2023-09-24 12:57 UTC, ruibaby commented on application/src/main/resources/extensions/notification-templates.yaml
> +          <p class="content" th:text="${content}"></p>
```suggestion
          <pre class="content" th:text="${content}"></pre>
```

2023-09-24 12:57 UTC, ruibaby commented on application/src/main/resources/extensions/notification-templates.yaml
> +          <p class="content" th:text="${content}"></p>
```suggestion
          <pre class="content" th:text="${content}"></pre>
```

2023-09-24 12:57 UTC, ruibaby commented on application/src/main/resources/extensions/notification-templates.yaml
> +          <p class="content" th:text="${content}"></p>
```suggestion
          <pre class="content" th:text="${content}"></pre>
```

2023-09-24 12:57 UTC, ruibaby commented on application/src/main/resources/extensions/notification.yaml
> +  description: "如果有其他用户回复了你的帖子或者留言，你将会收到一条通知，告诉你有人回复了你。"
```suggestion
  description: "如果有其他用户回复了你的评论，你将会收到一条通知，告诉你有人回复了你。"
```

2023-09-24 13:26 UTC, guqing commented on application/src/main/resources/extensions/notification.yaml
> +        - $formkit: appendFooter
默认追加不行，如果别人自定义了模板会和别人的样式不同

2023-09-28 13:30 UTC, ruibaby approved these changes
/approve

2023-09-28 13:31 UTC, JohnNiang approved these changes
/lgtm

2023-09-28 13:32 UTC, merged