fix: not using the default template when the custom template does not exist
halo-dev/halo pull request #4618
Opened 2023-09-18 03:51 UTC by guqing

#### What type of PR is this?
/kind bug
/area core
/milestone 2.10.x

#### What this PR does / why we need it:
修复文章自定义模板不存在时没有使用默认模板的问题

see #4617 for more details.

#### Which issue(s) this PR fixes:
Fixes #4617

#### Does this PR introduce a user-facing change?
```release-note
修复文章自定义模板不存在时没有使用默认模板的问题
```

2023-09-18 03:52 UTC, guqing commented
/cherry-pick release-2.9

2023-09-18 07:58 UTC, ruibaby reviewed
/lgtm

2023-09-22 07:46 UTC, JohnNiang requested changes

2023-09-22 07:46 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/router/ViewNameResolver.java
> +            return name;
这里建议直接返回 null，而不是 name。

2023-09-22 08:55 UTC, JohnNiang approved these changes
/lgtm

2023-09-22 09:18 UTC, JohnNiang commented on application/src/test/java/run/halo/app/theme/router/ViewNameResolverTest.java
> -        assertThat(viewNameResolver.computeResourceName(null)).isNull();
这里建议 assertThrow，而不是直接干掉。

2023-09-22 09:24 UTC, guqing commented on application/src/test/java/run/halo/app/theme/router/ViewNameResolverTest.java
> -        assertThat(viewNameResolver.computeResourceName(null)).isNull();
> 这里建议 assertThrow，而不是直接干掉。

ok

2023-09-22 09:24 UTC, JohnNiang approved these changes
/lgtm

2023-09-22 09:43 UTC, merged