refactor: use new api to change plugin status
halo-dev/halo pull request #4747
Opened 2023-10-18 07:41 UTC by ruibaby

#### What type of PR is this?

/area console
/kind improvement

#### What this PR does / why we need it:

适配 https://github.com/halo-dev/halo/pull/4745 ，使用新的接口启动/停止插件。

#### Which issue(s) this PR fixes:

Fixes #4744 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
None
```

2023-10-23 08:50 UTC, guqing reviewed
/lgtm

2023-10-26 02:37 UTC, JohnNiang requested changes

2023-10-26 02:37 UTC, JohnNiang commented on console/packages/api-client/src/models/plugin-motion-status-request.ts
> +export interface PluginMotionStatusRequest {
PluginMotionStatusRequest 在后端似乎已经不存在了。

2023-10-26 02:42 UTC, JohnNiang approved these changes
/lgtm

2023-10-26 02:56 UTC, merged