feat: add tabbar component horizontal-scroll-indicator
halo-dev/halo pull request #4979
Opened 2023-12-03 04:53 UTC by AeroWang

#### What type of PR is this?

/area console
/kind improvement

#### What this PR does / why we need it:

在 Tabbar 组件内容可滚动时，添加内容超出时的水平方向滚动指示器；解决由  #4582 指出的体验问题

#### Which issue(s) this PR fixes:

Fixes #4582

#### Special notes for your reviewer:

注意观察各处使用 Tabbar 组件且内容可滚动时的情况（浏览器宽度变化也可生效）

#### Does this PR introduce a user-facing change?

```release-note
添加 Tabbar 组件内容超出时的水平方向滚动指示器
```

2023-12-03 04:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=4979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=4979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=4979) it.</sub>

2023-12-06 03:02 UTC, ruibaby requested changes

2023-12-06 03:13 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +    pb-1.5;
有道理，但我现在无法调试，晚上才能调试。pb-1.5 -> pb-1.25 或者 pb-1 应该就可以了

2023-12-08 15:21 UTC, ruibaby reviewed
当前的更改似乎有一些功能问题。

1. 首次加载不会显示指示器，需要滚动之后才能显示。
2. 点击指示器可能无法滚动。
3. 滚动期间，指示器显示的时机似乎也有点问题。

视频：


https://github.com/halo-dev/halo/assets/21301288/edaf123b-b8c5-414a-baf7-2d830c03b27a

2023-12-09 10:58 UTC, AeroWang commented
现在我本地是这样的。

视频

https://github.com/halo-dev/halo/assets/44799877/b19f1401-bc5a-4db3-8487-9b9257e1ce21

2023-12-09 11:41 UTC, ruibaby commented
> @ruibaby 很奇怪哦，是我调试的方法有问题吗？packages/components 目录内 pnpm dev，console 目录下 pnpm dev，每次我本地会出现各种问题，然后调通后，推送，下次再启动就又出现问题了

现在 components 库已经支持了 storybook，你可以在 components 目录直接用 pnpm storybook 启动，调试起来会方便很多。

2023-12-10 03:03 UTC, LIlGG requested changes
感谢 @AeroWang 提出的 PR，我发现代码中有以下几处可能需要修正的位置。

2023-12-10 03:03 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +) {
index 与 prev 在下方的逻辑似乎并不重叠，因此这个方法可以拆分成两个，分别根据 index 或者 prev。

2023-12-10 03:03 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +// 保存每项 tab 宽度
```suggestion

```

移除无用的注释，用更加清晰易懂的变量名或者完整的英文 doc 代替。

2023-12-10 03:03 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +
```suggestion
const itemWidthArr = computed(() => {
  const itemWidthArr: number[] = [];
  if (!tabItemRefs.value) return itemWidthArr;
  for (const item of tabItemRefs.value) {
    itemWidthArr.push(item.offsetWidth);
  }
  return itemWidthArr;
});
```

items 在初始化之后数量不会发生变化，因此不需要监听 items 的数量。可以按照上述使用 `computed` 获取或者其他方式获取一次即可。

2023-12-10 03:03 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +// 以单标签距离滚动
```suggestion

```
同上，移除无用的注释。

2023-12-10 03:03 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +// NOTE: throttle ?
```suggestion

```
注释需要修正，确保注释与功能用途一致。

2023-12-10 03:10 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +// NOTE: throttle ?
ok，我在改一下

2023-12-10 03:13 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +
这里不太对，异步请求回来的 items 会有变化吧，试试 Hao 这个主题的 Tabbar

2023-12-10 03:39 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +
> 这里不太对，异步请求回来的 items 会有变化吧，试试 Hao 这个主题的 Tabbar

items 只有在切换主题或者重载主题配置时计算。

https://github.com/halo-dev/halo/blob/8b405faa5790304f39e9a1d3455f25ce6c9b6ddf/console/console-src/modules/interface/themes/layouts/ThemeLayout.vue#L96-L110

不过对于组件而言，监听 items 倒是没有问题的。不过在此场景下，我建议使用 `computed` 来计算 tabItemRefs 性能更好一些。或者只单独 watch tabItemRefs 而无需关心 items 。

2023-12-10 05:53 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +
computed 不行，初始箭头状态拿不到。改为单独 watch tabItemRefs

2023-12-10 09:07 UTC, LIlGG requested changes

2023-12-10 09:07 UTC, LIlGG commented on console/packages/components/src/components/tabs/Tabbar.vue
> +    w-20
![image](https://github.com/halo-dev/halo/assets/31335418/09c6ed2e-9400-4e93-96ef-f7679fc3a6ac)

这块移动上去点击没有任何反应，因此我建议将箭头的 `width` 设置小一点。或者为 indicator 设置 ` pointer-events: none`，让其可以点击到下面的 tab。

2023-12-10 09:17 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +  }
会被执行的，当弹窗里面有 tabbar 的时候，更新之前的宽度（数组中全为 0）

2023-12-10 09:40 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +        lastItemWidth + itemWidthArr.value[itemWidthArr.value.length - 2];
确实，修改为了
```js
    if (hiddenNum === itemWidthArr.value.length - 1) {
      scrollByX =
        lastItemWidth + itemWidthArr.value[itemWidthArr.value.length - 1];
    }
```

2023-12-10 09:44 UTC, AeroWang commented on console/packages/components/src/components/tabs/Tabbar.vue
> +  }
这块是要考虑，在我还没有点击出现弹窗时，其中的 tabbar 已经在挂载在 dom 中了，只是没渲染，初始元素宽度为 0；

所以这块再点击的时候更新一下保存的 tabItem 宽度集合；

突然想到这块判断只用判断第一项是否为 0 即可

2023-12-10 09:45 UTC, LIlGG commented
对于弹窗类型的，似乎显示有些问题。

![tabbar](https://github.com/halo-dev/halo/assets/31335418/bafdf1f8-450f-46c1-9a6e-e074d6317f68)

2023-12-10 10:02 UTC, AeroWang commented
> 对于弹窗类型的，似乎显示有些问题。

监听宽度大约有 1px 的误差抖动，已修复

2023-12-19 08:22 UTC, AeroWang commented
这个 PR 是还有什么问题吗？

2023-12-21 03:29 UTC, ruibaby reviewed
/approve

2023-12-21 03:30 UTC, ruibaby approved these changes

2023-12-21 06:43 UTC, LIlGG approved these changes
/lgtm

2023-12-21 06:44 UTC, merged

2023-12-21 06:46 UTC, JohnNiang commented
/meow

2023-12-21 06:48 UTC, AirboZH commented
/joke