fix: editor's image cannot be resized proportionally
halo-dev/halo pull request #4993
Opened 2023-12-04 14:28 UTC by pillar-cat

#### What type of PR is this?

/kind bug
/area editor

#### What this PR does / why we need it:
修复#4985 中调整图片大小时的高度变化bug
#### Which issue(s) this PR fixes:

Fixes #4985 

#### Special notes for your reviewer:
似乎是因为横纵比aspectRatio在调整大小的doDrag函数中被动态的更新数值，导致依赖aspectRatio来计算的高度也会出现问题。直接把aspectRatio移动到函数外，只在挂载后更新一次值即可解决。

#### Does this PR introduce a user-facing change?

```release-note
这会修复当前console的editor中图片比例拉伸的bug
```

2023-12-04 15:50 UTC, pillar-cat commented
/kind bug
/area editor

2023-12-05 03:28 UTC, LIlGG requested changes
hi， @pillar-cat ，感谢修复此 BUG，不过经过我测试，按照上述修改后会引入新的 BUG。

对于已经保存或者异步加载的图片，在页面刷新时无法获取到其 clientWidth 与 clientHeight，进而会导致纵横比计算为 `NAN`。或许可以使用 img 的 load 事件，在此事件触发时再计算图片的纵横比。

2023-12-05 03:29 UTC, pillar-cat commented
> hi， @pillar-cat ，感谢修复此 BUG，不过经过我测试，按照上述修改后会引入新的 BUG。
> 
> 对于已经保存或者异步加载的图片，在页面刷新时无法获取到其 clientWidth 与 clientHeight，进而会导致纵横比计算为 `NAN`。或许可以使用 img 的 load 事件，在此事件触发时再计算图片的纵横比。

好的我看看

2023-12-06 06:40 UTC, ruibaby approved these changes
/approve

2023-12-06 06:42 UTC, merged