feat: add getParentByName method to CategoryFinder interface
halo-dev/halo pull request #5002
Opened 2023-12-06 04:10 UTC by Roozenlz

#### What type of PR is this?

/kind feature
/kind api-change
#### What this PR does / why we need it:
add getParentByName method to CategoryFinder interface

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
${categoryFinder.getParentByName(anyChild.metadata.name)}
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

2023-12-07 09:17 UTC, JohnNiang commented
/milestone 2.12.x

2023-12-09 15:08 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +            .map(CategoryVo::from).single();
这里建议先获取第一个，再执行 map 操作。示例如下：

```java
findFirst().map(CategoryVo::from)
```

2023-12-09 15:21 UTC, Roozenlz commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +            .map(CategoryVo::from).single();
![image](https://github.com/halo-dev/halo/assets/93673944/b68ff228-056f-488f-bee2-ec4694b327ee)
没有找到相关方法

2023-12-09 15:27 UTC, Roozenlz commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +            .map(CategoryVo::from).single();
![image](https://github.com/halo-dev/halo/assets/93673944/0282fe99-cc2f-4d97-9a07-7c0c2c2696af)
找到了这个方法

2023-12-09 16:03 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +            .map(CategoryVo::from).single();
不好意思，这里我提供了错误的方法。正确的应该是

```java
.next().map(CategoryVo::from);
```

2023-12-11 08:59 UTC, JohnNiang requested changes

2023-12-11 08:59 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +                category -> category.getSpec().getChildren().contains(name),
这里可能需要考虑 children 为 null 的情况。

2023-12-14 04:21 UTC, Roozenlz commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +                category -> category.getSpec().getChildren().contains(name),
已更改

2023-12-18 03:56 UTC, JohnNiang requested changes

2023-12-18 03:56 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +                    if (StringUtils.isBlank(name)) {
如果确实需要判断 name 是否为空，也建议在 list 方法之前进行判断。例如：

```java
if (StringUtils.isBlank(name)) {
    return Mono.empty();
}

2023-12-18 03:56 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
> +                    if (spec == null) {
这里的 spec 字段在 Category schema 中是必须设置的，也可以考虑不用判断。

2023-12-18 05:09 UTC, JohnNiang approved these changes
/approve
/ping @halo-dev/sig-halo

2023-12-18 05:13 UTC, ruibaby approved these changes
/lgtm

2023-12-18 05:22 UTC, merged