fix: Backspace does not work properly behind list
halo-dev/halo pull request #5102
Opened 2023-12-22 07:32 UTC by AirboZH

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
增加 `@tiptap/extension-list-keymap` 扩展，优化列表的键盘操作

#### Which issue(s) this PR fixes:

Fixes #5065

#### Special notes for your reviewer:
测试方法：
1. 测试无序列表中和无序列表后对于回车键 `Enter` 和退格键 `backspace` 的支持是否符合预期
2. 测试有序列表中和有序列表后对于回车键 `Enter` 和退格键 `backspace` 的支持是否符合预期
![2023-12-22](https://github.com/halo-dev/halo/assets/50261327/ebdc1364-bfd6-4e2f-acf0-444a03f40299)

#### Does this PR introduce a user-facing change?

```release-note
修复无法删除有序/无序列表后空行的问题
```

2023-12-22 07:49 UTC, LIlGG requested changes
hi， @AirboZH ，感谢提交的 PR。
经过测试，我发现此提交会对其他快捷键产生冲突。例如：

输入：
```
1. 123
2. 123
```

之后，按 `Mod + a` 进行全选，然后按删除键进行删除，此时只会删除 list item 的最后一个 item。
这应该是删除键与快捷键冲突导致，删除键遇到 item 的 li 标签后，将其还原为了普通文本就停止继续操作了。

2023-12-22 08:36 UTC, AirboZH commented
> 经过测试，我发现此提交会对其他快捷键产生冲突。

🤨确实是我自测的时候没测到这个问题。

这是一个已知的问题，并且也有其他tiptap下游软件收到影响。
https://github.com/ueberdosis/tiptap/issues/4395
但是这其中的PR和Issue好像很久都没有人处理了。

我们可以等待上游处理。

同时，我也在看看有没有机会在 `list-keymap extension` 的基础上处理一下全选删除这个操作。

2023-12-22 09:49 UTC, LIlGG commented
> 同时，我也在看看有没有机会在 `list-keymap extension` 的基础上处理一下全选删除这个操作。

tiptap 在写这个扩展的时候，将工具类 [list-keymap](https://github.com/ueberdosis/tiptap/blob/develop/packages/extension-list-keymap/src/list-keymap.ts) 也导出了，那么只需要在 Halo 中重构扩展逻辑即可。

可以提供一种思路，例如在 `Backspace` 操作执行其余操作之前，先校验 `selection` 是否完全包含了当前 node 列表，如果包含，则执行 delete node 即可。

2023-12-25 04:29 UTC, LIlGG commented
似乎还是有问题。当不是全选时，将会出现与之前同样的问题。

![屏幕录制2023-12-25 12 26 22](https://github.com/halo-dev/halo/assets/31335418/62da2600-f04d-4dc6-8468-965ec4668eeb)

2023-12-29 09:19 UTC, LIlGG approved these changes
/lgtm

nice，它可以正常工作，很完美。

2024-01-02 03:45 UTC, ruibaby approved these changes
/lgtm

2024-01-02 03:46 UTC, merged

2024-01-02 09:18 UTC, JohnNiang commented
/milestone 2.12.x