WIP: feat: refactor editor image block upload logic
halo-dev/halo pull request #5159
Opened 2024-01-09 08:47 UTC by LIlGG

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

重构编辑器图片块上传逻辑，增加选择文件上传、上传进度条、取消、重试等机制。

#### How to test it?

直接拖动、复制或选择文件上传，查看是否显示上传进度条，取消、重试功能是否正常

#### Which issue(s) this PR fixes:

Fixes #5122 

#### Does this PR introduce a user-facing change?
```release-note
重构编辑器图片块上传逻辑，增加选择文件上传、上传进度条、取消、重试等机制。
```

2024-01-10 04:58 UTC, ruibaby commented
/area editor
/milestone 2.12.x

2024-01-11 08:02 UTC, ruibaby commented
测试之后发现几个问题：

1. 点击整个卡片也可以调出上传弹框。
    
    <img width="728" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/eb14b08f-345c-4afc-99dd-ed5b2e1728a6">

    原因可能是因为卡片外层使用了 label 标签。

2. 从附件库选择可以选择所有类型文件，建议仅可选择图片类型。
3. 建议支持替换图片，点击替换图片按钮后，显示初始卡片，可以选择重新上传或者从附件库选择。如果用户有换图片的需求，这将减少很多操作步骤。

2024-01-11 08:26 UTC, ruibaby requested changes

2024-01-11 08:26 UTC, ruibaby commented on console/packages/editor/src/components/index.ts
> +export { default as MdiDeleteForeverOutline } from "./icon/MdiDeleteForeverOutline.vue";
不建议从编辑器导出 Icon。

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/composables/use-attachment.ts
> +import type { AttachmentLike } from "packages/shared/dist";
```suggestion
import type { AttachmentLike } from "@halo-dev/console-shared";
```

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/extensions/image/index.ts
> +import type { Attachment } from "packages/api-client/dist";
```suggestion
import type { Attachment } from "@halo-dev/api-client";
```

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/extensions/image/index.ts
> +import type { ExtensionOptions } from "packages/editor/dist/types";
```suggestion
import type { ExtensionOptions } from "@halo-dev/richtext-editor";
```

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/utils/attachment.ts
> +import type { AttachmentLike } from "packages/shared/dist";
```suggestion
import type { AttachmentLike } from "@halo-dev/console-shared";
```

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/utils/upload.ts
> +import type { Attachment } from "packages/api-client/dist";
```suggestion
import type { Attachment } from "@halo-dev/api-client";
```

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/extensions/image/ImageView.vue
> +                    />
i18n

2024-01-11 08:26 UTC, ruibaby commented on console/src/components/editor/extensions/image/ImageView.vue
> +        src: getAttachmentUrl(attachment),
从附件库选择，需要考虑设置 alt

2024-01-11 09:31 UTC, JohnNiang reviewed
上传图片后一直显示上传中，实际上图片已经正常上传至附件库中了。

![image](https://github.com/halo-dev/halo/assets/16865714/de96cca4-63df-4cc8-839a-6cccdf38621e)

我的环境：Windows11，Edge。

2024-01-11 15:25 UTC, LIlGG commented
> 上传图片后一直显示上传中，实际上图片已经正常上传至附件库中了。
> 我的环境：Windows11，Edge。

我在 Windows 11 下使用开发环境运行此 PR，并且使用 Edge `120.0.2210.121 (正式版本) (64 位)` 进行图片上传测试，并没有能够成功复现。

在你的环境下，该现象是偶现还是必现？或者是否还有什么其他我遗漏的操作？

2024-01-12 09:13 UTC, guqing reviewed
出现点击附件库没有反应的情况，好像是删除其中的框会复现
<img width="1604" alt="image" src="https://github.com/halo-dev/halo/assets/38999863/1d8cb6c1-63e4-4f12-8a07-aa87d5752485">

2024-01-12 09:21 UTC, guqing commented
请看 vcr

https://github.com/halo-dev/halo/assets/38999863/fc6d4c5e-e1f6-4c90-bfd4-135c4485d9d4

展示了两个问题：
1. 删除空白的附件占位符会错误的将正在上传的删除掉(或是被 cancel 掉不确定)
2. 导致其他占位符点击附件库没有反应

2024-01-15 09:59 UTC, LIlGG commented
> 1. 删除空白的附件占位符会错误的将正在上传的删除掉(或是被 cancel 掉不确定)
> 2. 导致其他占位符点击附件库没有反应

这是由于删除了 node 之后，再次设置此 attr 导致的报错。已修复

2024-01-17 02:22 UTC, ruibaby commented
<img width="1086" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/3d2ef3bf-f1e8-444a-a5a6-7526862476b3">

这个替换图片的图标给人一种重试的感觉。建议将重试按钮放置在任意一个角落即可，鼠标放上去也不需要大范围的效果。

或者放置在 Bubble Menu。

2024-01-19 07:46 UTC, ruibaby approved these changes
/approve

2024-01-19 08:35 UTC, JohnNiang commented
> > 上传图片后一直显示上传中，实际上图片已经正常上传至附件库中了。
> > 我的环境：Windows11，Edge。
> 
> 我在 Windows 11 下使用开发环境运行此 PR，并且使用 Edge `120.0.2210.121 (正式版本) (64 位)` 进行图片上传测试，并没有能够成功复现。
> 
> 在你的环境下，该现象是偶现还是必现？或者是否还有什么其他我遗漏的操作？

无论是在 Windows、Linux 还是在 macOS build console 之后必定复现该问题。

2024-01-19 08:36 UTC, guqing commented
/hold

2024-01-19 09:19 UTC, guqing commented
/unhold
/lgtm

2024-01-19 09:29 UTC, JohnNiang approved these changes
/approve

2024-01-19 09:35 UTC, JohnNiang commented
/lgtm

2024-01-19 09:39 UTC, merged