pref: resolve horizontal scrollbar display issue in table
halo-dev/halo pull request #5191
Opened 2024-01-15 09:24 UTC by LIlGG

#### What type of PR is this?

/kind improvement

#### What this PR does / why we need it:

为表格重写 `scrollbar` 的样式。只有当鼠标移动至表格时，才会显示其滚动条。

#### How to test it?

将鼠标移动至表格，查看是否具有滚动条。

修改系统设置，例如 mac 系统设置 -> 外观 -> 显示滚动条。 查看行为是否一致。

#### Which issue(s) this PR fixes:

Fixes #5182 

#### Does this PR introduce a user-facing change?
```release-note
优化富文本编辑器中表格组件滚动条的显示逻辑
```

2024-01-16 03:02 UTC, ruibaby commented
当前的改动在不同浏览器会有不同的表现。

### Safari

始终不会显示滚动条。

https://github.com/halo-dev/halo/assets/21301288/8f67347f-e0fb-49c3-9992-eafdcd5d86fd

### Firefox

鼠标移动上去不会显示滚动条，选中之后会显示。

https://github.com/halo-dev/halo/assets/21301288/e91309aa-8279-4141-94d2-b8d0b6dd40de

### Chrome

可以符合 PR 的描述，但显示滚动条时，会导致其他内容下移。

https://github.com/halo-dev/halo/assets/21301288/c15f43f1-7f46-4f7c-9415-26406a7d369c

2024-01-16 03:11 UTC, ruibaby commented
综上，我不建议对滚动条做改动。建议如果表格溢出的话，在右侧显示阴影提示用户有溢出。并且在鼠标滚轮滚动的时候支持横向滚动。参考：https://github.com/halo-dev/halo/pull/4453

2024-01-16 03:28 UTC, LIlGG commented
> 当前的改动在不同浏览器会有不同的表现。

这是由于代码中使用了 [::-webkit-scrollbar](https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar) 

此层叠样式确实在不同浏览器下会有不同的表现，并且不支持 `Firefox`。

此方法兼容性确实比较差。

> 建议如果表格溢出的话，在右侧显示阴影提示用户有溢出。并且在鼠标滚轮滚动的时候支持横向滚动

我将尝试使用此方式来进行修改。

2024-01-16 03:33 UTC, LIlGG commented
/hold

2024-01-23 06:28 UTC, LIlGG commented
/unhold

已经使用 `如果表格溢出，则在侧边显示阴影提示用户有溢出。并且在鼠标滚轮滚动的时候支持横向滚动` 的方式重写优化。

2024-01-23 08:10 UTC, guqing commented
> /unhold
> 
> 已经使用 `如果表格溢出，则在侧边显示阴影提示用户有溢出。并且在鼠标滚轮滚动的时候支持横向滚动` 的方式重写优化。

单独启动编辑器的项目发现确实可行了，但是在 halo 这边没有生效

2024-01-23 08:15 UTC, guqing commented
> > /unhold
> > 已经使用 `如果表格溢出，则在侧边显示阴影提示用户有溢出。并且在鼠标滚轮滚动的时候支持横向滚动` 的方式重写优化。
> 
> 单独启动编辑器的项目发现确实可行了，但是在 halo 这边没有生效

sorry 这是我的问题，使用的 build 版本配置忘记改回去了所以没生效

2024-01-23 08:15 UTC, guqing reviewed
/lgtm

经测试未发现问题

2024-01-24 02:30 UTC, JohnNiang requested changes

2024-01-24 03:22 UTC, ruibaby reviewed
/lgtm

<img width="1092" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/6bfbee67-45a8-4676-908f-486be5eae194">

2024-01-25 03:04 UTC, JohnNiang approved these changes

2024-01-25 03:05 UTC, merged