feat: provide find and replace functionality for the default rich text editor
halo-dev/halo pull request #5206
Opened 2024-01-19 03:45 UTC by LIlGG

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

为默认富文本编辑器添加查找与搜索的功能扩展。

快捷键：

当焦点处于编辑器中时，可以使用 `Mod+f` 来唤起查找与搜索框，或者点击顶部工具栏来打开。
当焦点处于查找与搜索框时，按下 `Ecs` 可进行关闭。

<img width="1920" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/03a54bb8-2cc4-4cb0-9a18-fd0e9aede564">

#### How to test it?

测试查找与搜索功能是否正常

#### Which issue(s) this PR fixes:

Fixes #5195 

#### Does this PR introduce a user-facing change?
```release-note
为默认富文本编辑器添加查找与搜索的功能扩展。
```

2024-01-19 03:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=5206) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=5206) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: LIlGG<br/>:x: takagi<br/><hr/>**takagi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=5206) it.</sub>

2024-01-19 03:46 UTC, LIlGG commented
/area console
/area editor
/milestone 2.12.x

2024-01-19 03:54 UTC, ruibaby commented
<img width="1420" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/47cfc652-cc30-4a53-803a-04f58c117464">

红框中的搜索高亮似乎有问题。

2024-01-19 06:15 UTC, LIlGG commented
> 红框中的搜索高亮似乎有问题。

已解决。

2024-01-19 06:22 UTC, ruibaby commented
<img width="563" alt="图片" src="https://github.com/halo-dev/halo/assets/21301288/0a014d76-6499-47dd-9e02-134baeea1f25">

当输入框文字过长，会有显示问题。

2024-01-19 06:46 UTC, LIlGG commented
> 当输入框文字过长，会有显示问题。

已解决

2024-01-22 04:06 UTC, ruibaby requested changes

2024-01-22 04:06 UTC, ruibaby commented on console/packages/editor/src/extensions/search-and-replace/SearchAndReplace.vue
> +        })
建议改为：

```ts
if(val !== oldVal) {
        updateSearchReplace({
          setReplaceTerm: val,
        })
}
```

2024-01-22 04:06 UTC, ruibaby commented on console/packages/editor/src/extensions/search-and-replace/SearchAndReplace.vue
> +        })
同上

2024-01-22 04:06 UTC, ruibaby commented on console/packages/editor/src/extensions/search-and-replace/SearchAndReplace.vue
> +        })
同上

2024-01-24 03:17 UTC, ruibaby reviewed
/lgtm

2024-01-24 04:33 UTC, guqing approved these changes

2024-01-24 06:42 UTC, JohnNiang approved these changes
/approve

2024-01-24 07:05 UTC, ruibaby approved these changes
/approve

2024-01-24 07:07 UTC, merged