feat: add support for force verify email during user registration
halo-dev/halo pull request #5320
Opened 2024-02-04 00:06 UTC by mashirot

#### What type of PR is this?

/kind feature
/kind improvement
/kind api-change

#### What this PR does / why we need it:
增加对用户注册时必须验证邮箱的支持

#### Which issue(s) this PR fixes:

Fixes #5016

#### Special notes for your reviewer:
`regRequireVerifyEmail` 为 `false` 时与现在的注册行为一致
为 `true` 时注册页显示验证码校验相关，注册成功后 `UserSpec.emailVerified` 即为 `true`
没有判断邮件通知是否开启，与现有的邮箱验证一致，如未开启则收不到邮件

#### Does this PR introduce a user-facing change?

```release-note
增加对用户注册时必须验证邮箱的支持
```

2024-02-04 00:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=5320) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=5320) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=5320) it.</sub>

2024-02-04 02:45 UTC, ruibaby reviewed
Hi @mashirot ，感谢贡献，以下是我的一些建议：

2024-02-04 02:45 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +    .signUpCondition()
这个方法的出处是？ 似乎没有生成 api-client。

2024-02-04 02:45 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +    .signUpCondition()
cc @halo-dev/sig-halo 

`regRequireVerifyEmail` 和 `allowedEmailProvider` 使用单独的接口提供符合当前的逻辑吗？

以前类似于这样的数据是放置在 `/actuator/globalinfo`，比如：https://ryanc.cc/actuator/globalinfo

2024-02-04 02:45 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +      ["matches", new RegExp(signUpCond.allowedEmailProvider)],
`matches` 建议单独提供验证错误的信息，参考：https://github.com/halo-dev/halo/blob/b4e196372d5a0253a6abed976fac5791b2d83cf7/console/src/components/signup/SignupForm.vue#L105

2024-02-04 02:45 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +    return await apiClient.common.user.sendRegisterVerifyEmail({
同上，这个方法应该需要生成 api-client。

```
api-client:gen
```

2024-02-04 02:45 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +          "core.uc_profile.email_verify_modal.operations.send_code.toast_email_empty"
建议用和注册一样的前缀新建 key，而不是复用 UC 里面的邮件验证相关的 key，如果一定要复用的话，建议重构这些 key 的结构，比如 `core.common.toast.email_empty`

2024-02-04 02:46 UTC, ruibaby requested changes
Hi @mashirot ，感谢贡献，以下是我的一些建议：

2024-02-04 03:59 UTC, mashirot commented on console/src/components/signup/SignupForm.vue
> +    .signUpCondition()
我的想法是这两个属性只有`用户注册`这个场景才会用到，因此才单独提供了接口

我认为把`regRequireVerifyEmail`放在`globalinfo`里获取是合理的，但是`allowedEmailProvider`放在里面就有点怪，因为不知道用户会写多长的正则，可能让这个请求携带太多的无用信息

2024-02-07 03:09 UTC, JohnNiang commented
Hi @mashirot ，似乎出现编译错误了，详细错误请看 <https://github.com/halo-dev/halo/actions/runs/7798998882/job/21271216034?pr=5320>。

2024-02-07 04:01 UTC, mashirot commented
> Hi @mashirot ，似乎出现编译错误了，详细错误请看 https://github.com/halo-dev/halo/actions/runs/7798998882/job/21271216034?pr=5320。

signup的入参有修改，原来的test不满足，已经改好了

2024-02-07 07:55 UTC, JohnNiang commented
Hi @mashirot ，你可以在本地执行 `./gradlew build` 来验证代码格式，单元测试，编译错误。

2024-02-07 08:27 UTC, ruibaby commented on console/src/components/signup/SignupForm.vue
> +    .signUpCondition()
cc @halo-dev/sig-halo 目前这样做 OK 吗？

感觉针对登录和注册的页面，最终通过 https://github.com/halo-dev/halo/issues/5214 解决才是最好的方案。

2024-02-07 08:28 UTC, ruibaby requested changes

2024-02-07 08:28 UTC, ruibaby commented on ui/src/locales/en.yaml
> +        placeholder: Verification code
似乎不完整

<img width="570" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/a66f81b4-9f4a-4e46-b808-88562e19405c">

2024-02-07 09:07 UTC, mashirot commented on console/src/components/signup/SignupForm.vue
> +    .signUpCondition()
没@出来，赞同通过 #5214 解决

2024-02-07 09:31 UTC, JohnNiang requested changes

2024-02-07 09:31 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/service/impl/EmailVerificationServiceImpl.java
> +            .retryWhen(Retry.backoff(8, Duration.ofMillis(100))
这里似乎永远都不会 retry。建议：

```java
return sendVerificationNotification(email, email);
```

2024-02-07 09:31 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +                                signUpRequest.verifyCode).block();
在 Reactive 中调用 block 应该是无法正常运行的。

2024-02-07 09:31 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +                            throw new ServerWebInputException("Require verify code");
在 flatmap 中抛异常不是一个好的做法，建议：

```java
return Mono.error(new ServerWebInputException("Require verify code"));
```

2024-02-07 09:31 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +                            throw new ServerWebInputException("Wrong verify code");
同上。

2024-02-07 11:56 UTC, mashirot commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +                                signUpRequest.verifyCode).block();
（其实能运行，我理解是这块变成阻塞的了

2024-02-20 03:14 UTC, JohnNiang commented
/ping @halo-dev/sig-halo

2024-02-20 03:37 UTC, guqing requested changes

2024-02-20 03:37 UTC, guqing commented on api/src/main/java/run/halo/app/infra/SystemSetting.java
> +        Boolean regRequireVerifyEmail;
regRequireVerifyEmail 这个变量名感觉不是很好理解，我推荐使用 mustVerifyEmailOnRegister 或者 mustVerifyEmailAtRegistration

2024-02-20 03:37 UTC, guqing commented on api/src/main/java/run/halo/app/infra/SystemSetting.java
> +        String allowedEmailProvider;
这个 allowedEmailProvider 不建议在这个 PR 中处理，这属于另外的功能如提供一个设置用于限制邮箱服务商，你可以另外提一个 issue 然后在讨论如何做这个限制，而且这个功能目前要求用户填写正则也不友好

2024-02-21 08:22 UTC, guqing commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +            .flatMap(signUpRequest -> environmentFetcher.fetch(SystemSetting.User.GROUP,
这里这样写是否会更好一些
```suggestion
            return request.bodyToMono(SignUpRequest.class)
            .doOnNext(signUpRequest -> signUpRequest.user().getSpec().setEmailVerified(false))
            .flatMap(signUpRequest -> environmentFetcher.fetch(SystemSetting.User.GROUP,
                    SystemSetting.User.class)
                .map(user -> BooleanUtils.isTrue(user.getMustVerifyEmailOnRegistration()))
                .flatMap(mustVerifyEmailOnRegistration -> {
                    if (!mustVerifyEmailOnRegistration) {
                        return Mono.just(signUpRequest);
                    }
                    if (!StringUtils.isNumeric(signUpRequest.verifyCode)) {
                        return Mono.error(new EmailVerificationFailed());
                    }
                    return emailVerificationService.verifyRegisterVerificationCode(
                            signUpRequest.user().getSpec().getEmail(),
                            signUpRequest.verifyCode)
                        .flatMap(verified -> {
                            if (BooleanUtils.isNotTrue(verified)) {
                                return Mono.error(new EmailVerificationFailed());
                            }
                            signUpRequest.user().getSpec().setEmailVerified(true);
                            return Mono.just(signUpRequest);
                        });
                })
            )
```

2024-02-21 08:22 UTC, guqing commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +        return request.bodyToMono(RegisterVerifyEmailRequest.class)
这样是否会更好一些

```suggestion
        return request.bodyToMono(RegisterVerifyEmailRequest.class)
            .switchIfEmpty(Mono.error(
                () -> new ServerWebInputException("Required request body is missing."))
            )
            .map(emailReq -> {
                var email = emailReq.email();
                if (ValidationUtils.isValidEmail(email)) {
                    throw new ServerWebInputException("Invalid email address.");
                }
                return email;
            })
            .flatMap(email -> environmentFetcher.fetch(SystemSetting.User.GROUP,
                    SystemSetting.User.class)
                .map(config -> BooleanUtils.isTrue(config.getMustVerifyEmailOnRegistration()))
                .doOnNext(mustVerifyEmailOnRegistration -> {
                    if (!mustVerifyEmailOnRegistration) {
                        throw new AccessDeniedException("Email verification is not required.");
                    }
                })
                .transformDeferred(sendEmailVerificationCodeRateLimiter(email))
                .flatMap(s -> emailVerificationService.sendRegisterVerificationCode(email)
                    .onErrorMap(RequestNotPermitted.class, RateLimitExceededException::new))
                .onErrorMap(RequestNotPermitted.class, RateLimitExceededException::new)
            )
            .then(ServerResponse.ok().build());
```

2024-02-21 08:40 UTC, mashirot commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +            .flatMap(signUpRequest -> environmentFetcher.fetch(SystemSetting.User.GROUP,
我对webflex不是很熟悉，有一个疑问，修改后的186行 如果user为null，会不会抛NPE，还是说defaultIfEmpty会catch并使用默认值

2024-02-21 09:52 UTC, guqing commented on application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
> +    private <T> RateLimiterOperator<T> sendEmailVerificationCodeRateLimiter(String email) {
建议将这个方法名称改为 sendRegisterEmailVerificationCodeRateLimiter

2024-02-21 10:05 UTC, guqing approved these changes
Thank you and congrats🎉 for opening this amazing pull request.

2024-02-21 10:07 UTC, guqing commented
By the way, @JohnNiang @ruibaby 由于有了注册需验证邮箱的选项，是否在后续将注册的 rate limit 调大或者根据这个设置来改变，目前是默认一小时只能注册一个用户

2024-02-22 09:11 UTC, ruibaby approved these changes
/lgtm

2024-02-22 09:16 UTC, ruibaby commented
Hi @JohnNiang ，needs a approval

2024-02-22 09:42 UTC, JohnNiang approved these changes

2024-02-22 09:43 UTC, JohnNiang commented
Hi @mashirot , thank you for your contribution!

2024-02-22 09:44 UTC, merged