fix: failure in data query due to reconciler triggered by uncommitted transaction
halo-dev/halo pull request #5323
Opened 2024-02-04 09:07 UTC by guqing

#### What type of PR is this?
/kind bugfix
/milestone 2.12.x
/area core

#### What this PR does / why we need it:
修复事务未提交便触发控制器执行可能导致数据状态不正确的问题

**how to test it?**
1. 测试如 #5315 的问题是否还存在
2. 测试添加重名自定义模型对象会抛出异常且数据被回滚

#### Which issue(s) this PR fixes:
Fixes #5315

#### Does this PR introduce a user-facing change?
```release-note
修复事务未提交便触发控制器执行可能导致数据状态不正确的问题
```

2024-02-04 09:08 UTC, guqing commented
/milestone 2.13.x
/cherry-pick release-2.12

2024-02-04 09:08 UTC, guqing commented
/kind bug

2024-02-05 02:14 UTC, JohnNiang requested changes

2024-02-05 02:14 UTC, JohnNiang commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                })
建议恢复这几行修改。

2024-02-05 02:14 UTC, JohnNiang commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                    System.out.println(e);
建议移除无用的输出。

2024-02-05 02:14 UTC, JohnNiang commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                })
建议恢复这几行修改。

2024-02-05 02:26 UTC, guqing commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                })
已处理 [`d7a976d`](https://github.com/halo-dev/halo/pull/5323/commits/d7a976d76e84a4f914594883d7fd08761b14c87b)

2024-02-05 02:26 UTC, guqing commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                    System.out.println(e);
已处理 [`d7a976d`](https://github.com/halo-dev/halo/pull/5323/commits/d7a976d76e84a4f914594883d7fd08761b14c87b)

2024-02-05 02:27 UTC, guqing commented on application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
> +                })
已处理 [`d7a976d`](https://github.com/halo-dev/halo/pull/5323/commits/d7a976d76e84a4f914594883d7fd08761b14c87b)

2024-02-05 02:39 UTC, JohnNiang requested changes

2024-02-05 02:39 UTC, JohnNiang commented on application/src/main/java/run/halo/app/config/HaloConfiguration.java
> +    TransactionalOperator transactionTemplate(ReactiveTransactionManager transactionManager) {
建议不要把 TransactionalOperator 声明成一个 Singletone bean。哪里需要使用，直接在构造函数创建即可。因为不同的地方所需要的 TransactionalOperator 定义不同。例如：有些地方可能需要设置 `readOnly = true | false`。

可参考：[Spring Framework 官方文档中示例](https://docs.spring.io/spring-framework/reference/data-access/transaction/programmatic.html#tx-prog-operator)。

2024-02-05 03:02 UTC, guqing commented on application/src/main/java/run/halo/app/config/HaloConfiguration.java
> +    TransactionalOperator transactionTemplate(ReactiveTransactionManager transactionManager) {
已修改 [commit#7ecd23a2](https://github.com/halo-dev/halo/pull/5323/commits/7ecd23a2bb0f4e0a62ecb89fdfe4015ce8645d82)

2024-02-05 03:43 UTC, JohnNiang approved these changes
/approve

2024-02-05 04:05 UTC, ruibaby approved these changes
/lgtm

2024-02-05 04:09 UTC, merged