fix: resolve the issue of text editing not being effective before the table
halo-dev/halo pull request #5365
Opened 2024-02-18 09:30 UTC by LIlGG

#### What type of PR is this?

/kind bug
/area editor
/area console

#### What this PR does / why we need it:

在 #5191 中对表格新增了如果可以左右滚动时，则显示阴影的特性。而根据 `prosemirror` 的数据流处理策略，在 `decorations` 中，state 是 new EditorState，但通过 `this.editor.view` 获取到的 view 为 old EditorView，进而导致使用了最新的坐标，并且使用其坐标通过旧版本的 view 中获取 DOM 而产生的错误。

当前临时处理为限制了仅当内容文本不发生改变时去获取 DOM。

#### How to test it?

在默认富文本编辑器中新建一个表格。在表格前使用拼音输入文本，查看此文本能否被输入。

#### Which issue(s) this PR fixes:

Fixes #5352

#### Does this PR introduce a user-facing change?
```release-note
解决表格前字符无法被编辑的问题。
```

2024-02-19 07:14 UTC, LIlGG commented
/cherry-pick release-2.12

2024-02-19 09:59 UTC, guqing requested changes

2024-02-19 09:59 UTC, guqing commented on ui/packages/editor/src/extensions/table/index.ts
> +                  const tableNodeDOM = nodeDOM || domAtPos;
这里在视图中更改视图的操作是否应该使用状态去更改视图，这违反了编辑器使用状态驱动视图的设计，我认为应该：
 1. state 中定义一个对象来记录表格是否需要阴影
 2. 监听视图更改之后检测是否需要阴影去更改对应的状态视图，当阴影的状态没有发生变化时则不触发视图事务的变更以避免无限更新视图的问题
 3. 在装饰器中根据状态来变更视图如添加阴影样式

2024-02-20 04:04 UTC, LIlGG commented on ui/packages/editor/src/extensions/table/index.ts
> +                  const tableNodeDOM = nodeDOM || domAtPos;
> 这里在视图中更改视图的操作是否应该使用状态去更改视图，这违反了编辑器使用状态驱动视图的设计，我认为应该：

这里并不是在视图中更改视图，而是在未应用视图的情况下去获取视图，这会导致获取到的视图与即将改变的视图不是同一个导致的问题。

在视图中再次执行事务，会导致一系列的问题。在编辑器中，需要由视图上的事件来触发事务，例如键盘输入事件，移入移出事件，而直接在视图中手动触发事务会导致事件不匹配进而报错。此种方式会带来更多不可控的问题，因此也不是很建议在视图中再次触发事务。

或许在 NodeView 中处理此逻辑是比较合理的，但 NodeView 也有两个缺点，初始化时无法获取到当前 node 是否可以具有滚动阴影。并且在未获取到焦点时，滚动表格也无法生效。

2024-02-20 04:46 UTC, LIlGG commented on ui/packages/editor/src/extensions/table/index.ts
> +                  const tableNodeDOM = nodeDOM || domAtPos;
重新使用 `NodeView` 实现了表格阴影，并且解决了上述所存在的问题。

2024-02-20 09:06 UTC, JohnNiang approved these changes
It works very well.

/approve

2024-02-20 15:33 UTC, JohnNiang commented
/ping @halo-dev/sig-halo

2024-02-21 02:19 UTC, ruibaby approved these changes
/lgtm

2024-02-21 02:42 UTC, guqing approved these changes

2024-02-21 02:44 UTC, merged