WIP: feat: add verification function to the notification settings for the mailbox
halo-dev/halo pull request #5464
Opened 2024-03-07 07:43 UTC by LIlGG

#### What type of PR is this?

/kind feature
/area ui
/area core
/milestone 2.14.x

#### What this PR does / why we need it:

为邮件的 `通知设置` 添加验证的功能。

同时为 formkit 增加了一个新的组件 (verifyForm)，用于支持验证，它的定义方式如下：
```
- $formkit: verifyForm
  if: "$enable"
  actions: "http://localhost:8090/verify/user"
  label: 用户验证
  children:
    - $formkit: text
      label: "用户名"
      name: username
      validation: required
    - $formkit: password
      label: "密码"
      name: password
      validation: required
```

verifyForm 支持 `actions` 属性，当前端数据验证通过时，会将其下所包含的子节点数据发送至 actions 所代表的接口上。
按上述示例，则验证数据会提交至 `http://localhost:8090/verify/user` 进行验证。验证的数据为 `{name: xxx, password: xxx}

#### How to test it?

测试邮箱中的 `通知设置` 新增的验证按钮是否可以正常验证邮箱。

#### Which issue(s) this PR fixes:

Fixes #4714 

#### Does this PR introduce a user-facing change?
```release-note
在邮件通知设置中增加了发送测试的功能。
```

2024-03-07 07:49 UTC, ruibaby commented
hi @longjuan ，有时间可以尝试一下基于此 PR 为 S3 的配置表单添加一个验证。

2024-03-07 07:51 UTC, ruibaby commented
hi @LIlGG，在合并此 PR 前，建议同时提交对应文档的修改 PR。

https://docs.halo.run/developer-guide/form-schema

2024-03-07 08:06 UTC, LIlGG commented
hi, @guqing ，目前还缺少验证邮箱是否联通的后端接口，有时间的话帮忙补充一下。

2024-03-07 09:47 UTC, guqing commented
> hi, @guqing ，目前还缺少验证邮箱是否联通的后端接口，有时间的话帮忙补充一下。

已补充

2024-03-08 14:51 UTC, longjuan commented
> 有时间可以尝试一下基于此 PR 为 S3 插件的配置表单添加一个验证。

https://github.com/longjuan/halo-plugin-s3os/commit/e9bba381b369df8c8276c92994d765db336d3e66
发现一个问题，保存后的配置再次编辑时会空白，创建配置时请求data的displayName为空
![image](https://github.com/halo-dev/halo/assets/28662535/6ab512ec-0087-4d3f-87a0-a5a89b28b30d)
![image](https://github.com/halo-dev/halo/assets/28662535/da00128a-0272-42b0-9426-04a85ef6e1c3)

2024-03-08 14:54 UTC, longjuan commented on application/src/main/resources/extensions/role-template-notification.yaml
> +    verbs: [ "default-email-notifier" ]
呃，verbs好像错了？

2024-03-11 02:59 UTC, guqing commented on application/src/main/resources/extensions/role-template-notification.yaml
> +    verbs: [ "default-email-notifier" ]
good catch 这里不是 verbs 应该是 resourceNames

2024-03-11 08:12 UTC, LIlGG commented
>  发现一个问题，保存后的配置再次编辑时会空白，创建配置时请求data的displayName为空

已进行修复，你可以强制拉取一下最新的代码再进行测试。
另外希望能够测试一下是否能够兼容旧数据，例如先在旧版本上填写配置，然后在适配 `verifyForm` 之后看看回显是否正常。

2024-03-11 08:28 UTC, longjuan commented
有个建议：
希望在验证按钮附近提供一个未验证或通过的图标/tag，顶部弹窗有时候注意不到。
当验证后配置又有改变就重新置为未验证。

2024-03-12 12:29 UTC, longjuan commented
> 不过可以考虑单轮配置阶段增加图标，例如在验证完成之后，加一个验证通过的图标。在修改配置之后，恢复初始状态。

就是这种效果，之前我的bitwarden横幅挡着都看不到提示。

2024-03-12 12:29 UTC, longjuan commented
> 已修复

没问题了

2024-03-14 08:12 UTC, ruibaby commented
这个新的 FormKit input 如果是基于 form 类型进行改造，那么需要尽可能和原生的 form 区分开，如图：

<img width="1653" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/5bb01f43-f827-4537-8db1-42459e8364b7">

1. 样式问题
3. verifyForm 的 class 建议为 `formkit-verify-form`

如果不进行一定的区分，后续更改 form 的表现也会影响到 verifyForm。

2024-03-15 02:54 UTC, LIlGG commented
@longjuan verifyForm 已经改名为 verificationForm 。因此需要将 s3 配置表单的 `- $formkit: verifyForm` 改为  `- $formkit: verificationForm`

2024-03-15 16:19 UTC, JohnNiang commented on application/src/main/java/run/halo/app/notification/endpoint/EmailConfigValidationEndpoint.java
> +            .doOnNext(email -> {
推荐用 filter + switchIfEmpty，不建议在 doOnNext 中抛出异常。

2024-03-17 08:40 UTC, longjuan commented
> verifyForm 已经改名为 verificationForm 。因此需要将 s3 配置表单的 `- $formkit: verifyForm` 改为 `- $formkit: verificationForm`

正常

2024-03-18 04:59 UTC, guqing commented on application/src/main/java/run/halo/app/notification/endpoint/EmailConfigValidationEndpoint.java
> +            .doOnNext(email -> {
Done [commit#5464](https://github.com/halo-dev/halo/pull/5464/commits/5ed45ffc2ca9aab7707337ac69e235dbd8024dd7)

2024-03-20 07:47 UTC, ruibaby requested changes

2024-03-20 07:47 UTC, ruibaby commented on ui/src/formkit/inputs/verify-form/index.ts
> +  props: ["actions", "label", "buttonAttrs"],
在原生 form 表单中，接口属性名为 action，既然这个组件叫做 ValidationForm，我们是否要和 form 保持一致？将验证接口地址的属性命名为 action？

<img width="475" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/ec13890d-4030-49c9-915c-b09b2cd64575">

2024-03-20 10:41 UTC, JohnNiang reviewed
IMO，支持验证表单和邮箱验证测试应该是两个功能，如果能够拆分一下提交会不会更好呢？

2024-03-20 11:26 UTC, LIlGG commented
> IMO，支持验证表单和邮箱验证测试应该是两个功能，如果能够拆分一下提交会不会更好呢？

我认为虽然是可以进行拆分，但此 PR 主要还是用于添加邮箱验证测试这个业务功能，而验证表单是为了满足此业务而产生的组。例如在写文章列表的同时抽象出一个用于展示列表的公共组件，本质上是同一件事情。

2024-03-21 12:36 UTC, ruibaby reviewed
/lgtm

2024-03-25 04:42 UTC, guqing reviewed
/lgtm

2024-03-26 07:58 UTC, ruibaby approved these changes
/lgtm

2024-03-26 08:00 UTC, merged