WIP: feat: add a title input box in the editor
halo-dev/halo pull request #5465
Opened 2024-03-07 09:40 UTC by ruibaby

#### What type of PR is this?

/area editor
/area ui
/kind feature

#### What this PR does / why we need it:

为默认编辑器添加标题输入框。

<img width="1665" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/df903e02-76b0-45fe-89d9-6ac81af8f041">

#### Which issue(s) this PR fixes:

Fixes #5427 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
为默认编辑器添加标题输入框。
```

2024-03-11 07:28 UTC, ruibaby commented
插件扩展的文档已添加在：https://github.com/halo-dev/docs/pull/325

2024-03-11 09:04 UTC, LIlGG requested changes
无法对已经具有标题的文章、页面修改标题。

2024-03-11 09:08 UTC, LIlGG commented
<img width="1919" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/26c4ce74-65ab-4c0b-89dc-15f209353417">

搜索和替换功能会被标题挤下去。实际上应该在顶部工具栏下方。

2024-03-12 03:04 UTC, ruibaby commented
> 无法对已经具有标题的文章、页面修改标题。

已修复。

2024-03-14 07:18 UTC, LIlGG commented
新建一个新文章，编写标题，保存之后会变为默认的 `未命名文章`。 console 与 uc 均有此问题。

2024-03-14 08:29 UTC, ruibaby commented
> 新建一个新文章，编写标题，保存之后会变为默认的 `未命名文章`。 console 与 uc 均有此问题。

已修复。

2024-03-15 03:26 UTC, JohnNiang reviewed
新建文章后输入标题，点击右上角发布按钮，标题未同步修改。

<img width="1396" alt="image" src="https://github.com/halo-dev/halo/assets/16865714/8914b9af-ba1d-4718-80a4-3526b8aa16f7">

2024-03-17 02:51 UTC, ruibaby commented
> 新建文章后输入标题，点击右上角发布按钮，标题未同步修改。
> 

已修复。

2024-03-17 03:33 UTC, JohnNiang approved these changes
/lgtm

2024-03-17 12:17 UTC, guqing reviewed
/lgtm

2024-03-18 03:06 UTC, LIlGG commented
直接保存时会报错误。正常操作应该是显示一个 `未命名文章` 之类的标题。

<img width="897" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/14424b7b-b8c5-4af8-9435-a3ff66a32fa7">

2024-03-18 03:35 UTC, ruibaby commented
> 直接保存时会报错误。正常操作应该是显示一个 未命名文章 之类的标题。

@LIlGG 已修复。

2024-03-18 04:37 UTC, LIlGG approved these changes
/lgtm

2024-03-18 04:38 UTC, merged