feat: comments from users with comment management permission could exempt from review
halo-dev/halo pull request #5529
Opened 2024-03-19 15:10 UTC by mashirot

#### What type of PR is this?

/area comment
/area ui
/kind improvement

#### What this PR does / why we need it:

> 开启了新评论审核设置,如果是在文章页面登录超级管理员账号进行评论,仍然需要在后台进行审核

#### Which issue(s) this PR fixes:

Fixes #5468 

#### Does this PR introduce a user-facing change?

```release-note
新增评论设置，允许有评论管理权限的用户发布的评论无需审核
```

2024-03-20 02:50 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +    @SuppressWarnings({"checkstyle:WhitespaceAfter", "checkstyle:Indentation"})
建议移除这行修改,并最新 halo 的 checkstyle 修改代码以符合规范

2024-03-20 04:10 UTC, mashirot commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +    @SuppressWarnings({"checkstyle:WhitespaceAfter", "checkstyle:Indentation"})
a small mistake

2024-03-21 03:21 UTC, mashirot commented
/area core
/remove-area ui

2024-03-21 03:42 UTC, guqing requested changes

2024-03-21 03:42 UTC, guqing commented on api/src/main/java/run/halo/app/infra/SystemSetting.java
> +        Boolean autoApproveAdminComment;
可以直接去掉这个设置项,默认有评论管理权限的可以不需要审核即可

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                                roleService.contains(roles, Set.of("role-template-manage-comments"))
建议将这个评论管理的名称字符串放到全局并声明为 static final

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                                    .subscribe();
不要在响应式中写 subscribe,应该使用 flatmap 来返回

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                                    .map(o -> o.getAuthority().substring(5))
使用 run.halo.app.security.authorization.AuthorityUtils.authoritiesToRoles 方法来从 authentication.getAuthorities() 得到角色名称集合

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
> +                                        if (commentSetting.getAutoApproveAdminComment()) {
同评论,被移除设置后即可不需要这行判断

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
> +                                                .map(o -> o.getAuthority().substring(5))
同评论

2024-03-21 03:42 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
> +                                                .subscribe();
同评论

2024-03-21 03:42 UTC, guqing commented on application/src/main/resources/extensions/system-setting.yaml
> +        - $formkit: checkbox
移除此设置项

2024-03-21 03:42 UTC, guqing commented on application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
> +        commentSetting.setAutoApproveAdminComment(false);
移除改动

2024-03-21 03:58 UTC, mashirot commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                                    .map(o -> o.getAuthority().substring(5))
请看这个[commit](https://github.com/halo-dev/halo/pull/5529/commits/20153ee3ccfe18217326072afd3295074add8f7f)
是否除了常量和工具类的使用，其余均符合要求

2024-03-21 04:03 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                                    .map(o -> o.getAuthority().substring(5))
> 请看这个[commit](https://github.com/halo-dev/halo/pull/5529/commits/20153ee3ccfe18217326072afd3295074add8f7f) 是否除了常量和工具类的使用，其余均符合要求

目前来看是这样的,等你修改过后我会进行功能测试看是否符合预期

2024-03-21 06:34 UTC, JohnNiang commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                            var authentication = securityContext.getAuthentication();
突然想到这里获取的是当前访问的 Principal 的权限（例如通过 PAT 请求），可能获取不到评论管理权限，即使 ta 拥有这个权限。这是符合预期的么？ @halo-dev/sig-halo

2024-03-21 10:13 UTC, guqing commented on application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
> +                            var authentication = securityContext.getAuthentication();
> 突然想到这里获取的是当前访问的 Principal 的权限（例如通过 PAT 请求），可能获取不到评论管理权限，即使 ta 拥有这个权限。这是符合预期的么？ @halo-dev/sig-halo

我认为没有问题,这里的 authorities 只是这个用户所拥有的**角色**而不是权限(角色模板),具体的权限应该通过角色去得到

2024-03-21 15:04 UTC, JohnNiang approved these changes
/approve

2024-03-21 15:57 UTC, ruibaby approved these changes
/lgtm

2024-03-22 02:45 UTC, guqing approved these changes

2024-03-22 02:46 UTC, merged