Added new sorting rules for posts on the console, sorted by visit count and comment count
halo-dev/halo pull request #5614
Opened 2024-03-29 08:53 UTC by ZJamss

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Added new sorting rules for posts on the console, sorted by visit count and comment count
#### Which issue(s) this PR fixes:

Fixes #3216 

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
Yes

```release-note
Added sorting options forMost Visit and Most Comment.
```

2024-03-29 08:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=5614) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=5614) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=5614) it.</sub>

2024-03-29 09:49 UTC, guqing requested changes

2024-03-29 09:49 UTC, guqing commented on application/src/main/java/run/halo/app/extension/index/IndexBuilderImpl.java
> +            extensionRecord.accept(indexVisitor);
Hi @ZJamss 非常感谢你参与贡献，但是希望实现此功能时不要干预索引的构建，索引算是一个非常底层的操作不应该直接 hook 到这个过程中来实现业务逻辑，这不符合 halo 的设计理念，你可以充分利用现有机制如实现一个 Reconciler 来 watch Counter 资源并发出事件由对应的 Handler 监听并处理

2024-03-29 10:38 UTC, ZJamss commented on application/src/main/java/run/halo/app/extension/index/IndexBuilderImpl.java
> +            extensionRecord.accept(indexVisitor);
这对我很有帮助，我会尝试的

2024-03-30 07:53 UTC, ZJamss commented on application/src/main/java/run/halo/app/extension/index/IndexBuilderImpl.java
> +            extensionRecord.accept(indexVisitor);
```java
    @Override
    public Result reconcile(Request request) {
        client.fetch(Counter.class, request.name())
            .ifPresentOrElse(counter -> {
                // update/create counter
            }, () -> {
                // delete counter
            });
        return Result.doNotRetry();
    }

```
我有一个想法，使用一个ConcurrentSkipListSet来保存counter变化的request，每分钟获取所有的request更新索引，在这期间内，如果有新的更新或创建请求就加入或者覆盖，如果有删除请求就立即执行，同时删除set中的元素，这样可行吗

2024-04-01 10:34 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void handleSetRequest() {
Hi @ZJamss ,既然此 reconciler 已经监听了 Counter 的改动，那么这里的定时任务还需要吗，只要 Counter 变更就会触发，我感觉这里貌似是多余的

2024-04-01 10:35 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +            set.add(getPostName(name));
这里建议判断一下这个 counter 是否属于文章的 Counter 而不是其他的什么在处理，如果不是就跳过

2024-04-01 10:36 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    private final Set<String> set;
不再需要全局的 Set 来记录文章数量，可以在 reconcile 方法中直接处理

2024-04-01 10:37 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void handleSetRequest() {
在回收站删除文章的时候会删除所有的评论，短时间会造成大量的request，用set去重处理就只用处理一次了

2024-04-01 10:39 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void preBuildCounterIndexes() {
不要在其他地方去干扰索引的构建，索引只应该被声明，会被自动处理，并且这里貌似也不需要为 Counter 建立索引的必要

2024-04-01 10:45 UTC, guqing commented on api/src/main/java/run/halo/app/core/extension/content/Post.java
> +    public static final String COUNTER_VISIT_ANNO = "counter.visit";
建议名称叫做：content.halo.run/counter，或者 content.halo.run/stats,然后值是一个 json, 这样数据会集中一些

2024-04-01 10:47 UTC, guqing commented on application/src/main/java/run/halo/app/event/post/PostChangeEvent.java
> +public class PostChangeEvent extends ApplicationEvent implements PostEvent {
由于是直接写了一个 PostCounterReconciler 然后在 reconcile 方法中更新的文章，那么感觉就不需要这个事件了

2024-04-01 10:48 UTC, ZJamss commented on application/src/main/java/run/halo/app/event/post/PostChangeEvent.java
> +public class PostChangeEvent extends ApplicationEvent implements PostEvent {
> 于是直接写了一个 PostCounterReconciler 然后在 reconcile 方法中更新

控制台点进文章的时候会更新文章内容，然后会重构索引，以至于对应文章的counter索引消失了，所以写了一个事件提醒重构一下索引

2024-04-01 10:50 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void preBuildCounterIndexes() {
> 不要在其他地方去干扰索引的构建，索引只应该被声明，会被自动处理，并且这里貌似也没有为 Counter 建立索引的必要

不预构建一下counter索引的话，启动之后没有对应索引评论量这些是没法排序的，有其他思路解决吗

2024-04-01 10:50 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +        client.fetch(Post.class, postName)
由于设计准则不建议在监听了如 Counter 的资源中去修改其他资源如文章，所以这里检测到文章的 counter 数量变更之后最好是发出一个如 PostCounterChangedEvent 然后参考 https://github.com/halo-dev/halo/blob/35cc323585ce8078249db1635d192f8ab31c4063/application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java#L42 来处理文章的更新

2024-04-01 10:52 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void preBuildCounterIndexes() {
> > 不要在其他地方去干扰索引的构建，索引只应该被声明，会被自动处理，并且这里貌似也没有为 Counter 建立索引的必要
> 
> 不预构建一下counter索引的话，启动之后没有对应索引评论量这些是没法排序的，有其他思路解决吗

将这个 Reconciler 的 setupWith 方法中的 syncAllOnStart 设置为 true 就会在每次启动的时候查询 Counter 然后一个个执行这个 Reconciler 得到处理

2024-04-01 10:55 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void handleSetRequest() {
> 在回收站删除文章的时候会删除所有的评论，短时间会造成大量的request，用set去重处理就只用处理一次了

Counter 更新到数据库应该不是实时的，会延迟同步到数据库中，比如连续访问文章很多次并不是每次访问都会更新数据，因此不必担心

2024-04-01 10:58 UTC, guqing commented on application/src/main/java/run/halo/app/event/post/PostChangeEvent.java
> +public class PostChangeEvent extends ApplicationEvent implements PostEvent {
> > 于是直接写了一个 PostCounterReconciler 然后在 reconcile 方法中更新
> 
> 控制台点进文章的时候会更新文章内容，然后会重构索引，以至于对应文章的counter索引消失了，所以写了一个事件提醒重构一下索引

只需要在 https://github.com/halo-dev/halo/blob/ae274db893e8c359bf04b8e2762e391f26f376f0/application/src/main/java/run/halo/app/infra/SchemeInitializer.java#L103 中添加相关的索引即可，应该是不可能会消失的吧否则文章的其他索引都无法工作，除非是手动将对应的 annotations 删除，但目前可以不考虑被用户手动删除的情况

2024-04-01 11:03 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void handleSetRequest() {
> > 在回收站删除文章的时候会删除所有的评论，短时间会造成大量的request，用set去重处理就只用处理一次了
> 
> Counter 更新到数据库应该不是实时的，会延迟同步到数据库中，比如连续访问文章很多次并不是每次访问都会更新访问量数据，因此不必担心

好的，之前测试过可能是看错了😂

2024-04-01 11:03 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +    public void preBuildCounterIndexes() {
> > > 不要在其他地方去干扰索引的构建，索引只应该被声明，会被自动处理，并且这里貌似也没有为 Counter 建立索引的必要
> > 
> > 
> > 不预构建一下counter索引的话，启动之后没有对应索引评论量这些是没法排序的，有其他思路解决吗
> 
> 好的

2024-04-01 11:06 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +        client.fetch(Post.class, postName)
> 由于设计准则不建议在监听了如 Counter 的资源中去修改其他资源如文章，所以这里检测到文章的 counter 数量变更之后最好是发出一个如 PostCounterChangedEvent 然后参考
> 
> https://github.com/halo-dev/halo/blob/35cc323585ce8078249db1635d192f8ab31c4063/application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java#L42
> 
> 来处理文章的更新

没有修改文章信息呀，只是查询出文章的数据，添加上新的counter方便重构新的索引，没有回刷进数据库的呀

2024-04-01 11:13 UTC, ZJamss commented on application/src/main/java/run/halo/app/event/post/PostChangeEvent.java
> +public class PostChangeEvent extends ApplicationEvent implements PostEvent {
> > > 于是直接写了一个 PostCounterReconciler 然后在 reconcile 方法中更新
> > 
> > 
> > 控制台点进文章的时候会更新文章内容，然后会重构索引，以至于对应文章的counter索引消失了，所以写了一个事件提醒重构一下索引
> 
> 只需要在
> 
> https://github.com/halo-dev/halo/blob/ae274db893e8c359bf04b8e2762e391f26f376f0/application/src/main/java/run/halo/app/infra/SchemeInitializer.java#L103
> 
> 中添加相关的索引即可，应该是不可能会消失的吧否则文章的其他索引都无法工作，除非是手动将对应的 annotations 删除，但目前可以不考虑被用户手动删除的情况

已经注册了的，我是将counter的数据放进了post的annotations中去构建索引，但post只是数据库查询返回的局部变量，离开函数作用域就会销毁，所以更新之后的post的annotations中不会有数据的，是我遗漏了一些特性吗，望指点

2024-04-01 13:18 UTC, ZJamss commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +        client.fetch(Post.class, postName)
> 由于设计准则不建议在监听了如 Counter 的资源中去修改其他资源如文章，所以这里检测到文章的 counter 数量变更之后最好是发出一个如 PostCounterChangedEvent 然后参考
> 
> https://github.com/halo-dev/halo/blob/35cc323585ce8078249db1635d192f8ab31c4063/application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java#L42
> 
> 来处理文章的更新

意识是PostCounterReconciler只负责监视资源并转发事件，处理事件的逻辑比如重构索引在一个新的PostEventCounterReconciler里进行是吗

2024-04-02 03:42 UTC, guqing commented
Hi @ZJamss , 我这提供一个实现思路你参考一下吧 https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits

2024-04-02 04:03 UTC, ZJamss commented
> Hi @ZJamss , 我这提供一个实现思路你参考一下吧 https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits

好的，再次感谢，那我也是继续重构代码重新提交commit to review吗

2024-04-02 04:04 UTC, guqing commented
> > Hi @ZJamss , 我这提供一个实现思路你参考一下吧 [main...guqing:halo:feature/sortby-visits](https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits)
> 
> 好的，再次感谢，那我也是继续重构代码重新提交commit to review吗

是的，由于此 issue 是你在解决，所以你继续提交即可, 我给出的解决方式只是参考

2024-04-02 04:06 UTC, ZJamss commented
> > > Hi @ZJamss , 我这提供一个实现思路你参考一下吧 [main...guqing:halo:feature/sortby-visits](https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits)
> > 
> > 好的，再次感谢，那我也是继续重构代码重新提交commit to review吗
> 
> 是的，由于此 issue 是你在解决，所以你继续提交即可, 我给出的解决方式只是参考

好的

2024-04-03 01:03 UTC, ZJamss commented
> > > Hi @ZJamss , 我这提供一个实现思路你参考一下吧 [main...guqing:halo:feature/sortby-visits](https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits)
> > 
> > 
> > 好的，再次感谢，那我也是继续重构代码重新提交commit to review吗
> 
> 是的，由于此 issue 是你在解决，所以你继续提交即可, 我给出的解决方式只是参考

重新review一下吧

2024-04-04 14:29 UTC, ZJamss commented
> > > Hi @ZJamss , 我这提供一个实现思路你参考一下吧 [main...guqing:halo:feature/sortby-visits](https://github.com/halo-dev/halo/compare/main...guqing:halo:feature/sortby-visits)
> > 
> > 
> > 好的，再次感谢，那我也是继续重构代码重新提交commit to review吗
> 
> 是的，由于此 issue 是你在解决，所以你继续提交即可, 我给出的解决方式只是参考

Hello，@guqing，请问有时间review一下吗，我好像不能re-request review了

2024-04-04 14:39 UTC, guqing requested changes

2024-04-04 14:39 UTC, guqing commented on api/src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
> +    public ControllerBuilder queue(RequestQueue<Request> queue) {
Hi @ZJamss 建议移除对这个类的所有改动

2024-04-04 14:39 UTC, guqing commented on application/src/main/java/run/halo/app/content/Stats.java
> +}
文件末尾应该有一个空行

2024-04-04 14:39 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
> +}
文件末尾应该有一个空行

2024-04-04 14:39 UTC, guqing commented on application/src/main/java/run/halo/app/event/post/PostStatsChangedEvent.java
> +}
文件末尾建议有一个空行

2024-04-04 14:39 UTC, guqing commented on application/src/main/java/run/halo/app/infra/SchemeInitializer.java
> +}
文件末尾应该有一个空行

2024-04-04 14:39 UTC, guqing commented on application/src/main/java/run/halo/app/metrics/PostStatsUpdater.java
> +}
文件末尾应该有一个空行

2024-04-04 14:41 UTC, guqing commented
Hi @ZJamss 感谢你的付出，等解决之后我们，请等待我们测试之后的反馈，如果没有问题将会进入合并流程

2024-04-04 15:41 UTC, guqing commented on api/src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
> +
这里还有一行改动没有撤回呢

2024-04-04 15:51 UTC, ZJamss commented on api/src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
> +
疏忽了😶‍

2024-04-08 08:39 UTC, guqing commented
/milestone 2.15.x
/area core
/area console

2024-04-11 08:54 UTC, JohnNiang approved these changes
It works very well!

Thanks for your first contribution!

/approve

/ping @halo-dev/sig-halo

2024-04-11 10:06 UTC, LIlGG reviewed
/lgtm

2024-04-11 10:08 UTC, guqing approved these changes
/approve

Congrats on merging your pull request! 🎉🎉🎉 Thank you for your efforts

2024-04-11 10:10 UTC, merged

2024-04-11 10:25 UTC, ZJamss commented
🎉🎉🎉