feat: add gravatar url into annotation of spec of comment for anonymous
halo-dev/halo pull request #5642
Opened 2024-04-03 19:55 UTC by mashirot

/kind feature
/area core

#### What this PR does / why we need it:

see https://github.com/halo-dev/plugin-comment-widget/issues/97

#### Which issue(s) this PR fixes:

#5641 

```release-note
匿名评论头像使用Gravatar源
```

2024-04-04 01:14 UTC, ruibaby requested changes
感谢 @mashirot 参与贡献~

我这里有一些改进建议。

2024-04-04 01:14 UTC, ruibaby commented on application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
> +                    .put(Comment.CommentOwner.AVATAR_ANNO, "https://gravatar.com/avatar/"
不建议在 Halo 这边将 Gravatar 地址写死，更推荐只生成 hash 字符串，然后交给评论组件的前端做拼接，这样做有几个好处：

1. 可以在评论组件的设置中添加一些开启选项，比如 **是否开启 Gravatar**、**Gravatar 应用策略（为所有用户应用，仅为匿名用户应用、仅为没有设置头像的用户应用等）**。
2. 在评论组件的设置中可以添加 Gravatar 源的设置选项，Gravatar 的官方源在某些地区并不能很好的访问，如果能让使用者自己设置，那么就可以设置类似于 https://public.webp.se/ 的服务。
3. 未来可能不仅只有 Gravatar，比如 https://github.com/halo-dev/halo/issues/5610#issuecomment-2024523297

2024-04-04 07:56 UTC, mashirot commented on application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
> +                    .put(Comment.CommentOwner.AVATAR_ANNO, "https://gravatar.com/avatar/"
`评论组件的设置`目前是否没有

2024-04-08 03:25 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
> +        String emailHash = null;
这里推荐以下写法：

```java
        commentVo.getSpec().setIpAddress("");
        var specOwner = commentVo.getSpec().getOwner();
        specOwner.setName("");

        var email = owner.getEmail();
        if (StringUtils.hasText(email)) {
            var emailHash = DigestUtils.md5DigestAsHex(email.getBytes(StandardCharsets.UTF_8));
            var annotations = specOwner.getAnnotations();
            if (annotations == null) {
                annotations = new HashMap<>();
                specOwner.setAnnotations(annotations);
            }
            annotations.put(Comment.CommentOwner.EMAIL_HASH_ANNO, emailHash);
        }
        if (specOwner.getAnnotations() != null) {
            specOwner.getAnnotations().remove("Email");
        }
        return Mono.just(commentVo);
```

2024-04-08 07:44 UTC, JohnNiang reviewed
/approve

Thank you for your contribution!

2024-04-08 08:02 UTC, guqing reviewed
/lgtm

2024-04-08 08:14 UTC, merged