fix: the details of the attachment may be empty
halo-dev/halo pull request #5695
Opened 2024-04-12 04:11 UTC by LIlGG

#### What type of PR is this?

/kind bug
/area ui
/milestone 2.15.x

#### What this PR does / why we need it:

修复由于 modal 延迟 200ms 所导致的数据可能为空的问题。

See #5078 

#### How to test it?

反复点击并关闭附件库详情弹窗，查看是否会有空数据的问题

#### Which issue(s) this PR fixes:

Fixes #5689 

#### Does this PR introduce a user-facing change?
```release-note
修复附件详情弹窗可能无法显示数据的问题
```

2024-04-12 04:13 UTC, ruibaby requested changes

2024-04-12 04:13 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
> -const onVisibleChange = (visible: boolean) => {
这个方法已经删除，但下面的关闭弹窗的点击事件还是这个方法，需要同时修改。

2024-04-12 04:24 UTC, ruibaby reviewed
/lgtm

2024-04-12 09:05 UTC, guqing approved these changes
/approve

2024-04-12 09:44 UTC, ruibaby approved these changes
/lgtm

2024-04-12 09:46 UTC, merged

2024-04-23 06:39 UTC, JohnNiang commented
/cherrypick release-2.14