feat: add import and export theme configuration
halo-dev/halo pull request #6071
Opened 2024-06-12 04:15 UTC by LIlGG

#### What type of PR is this?

/kind feature
/area ui
/milestone 2.17.x

#### What this PR does / why we need it:

为主题增加导入及导出配置的功能。

<img width="1666" alt="image" src="https://github.com/halo-dev/halo/assets/31335418/3574b33e-0293-427c-9036-5d82948aa7f2">

#### How to test it?

测试主题导入及导出功能是否正常可用。
测试当前主题下的不同版本导入导出后数据是否正常。
测试在当前主题下使用其他主题导出的配置是否会报错。

#### Which issue(s) this PR fixes:

Fixes #1073 

#### Does this PR introduce a user-facing change?
```release-note
为单个主题配置增加导入与导出的功能。
```

2024-06-17 13:51 UTC, ruibaby requested changes

2024-06-17 13:51 UTC, ruibaby commented on ui/console-src/modules/interface/themes/ThemeDetail.vue
> +};
是否可以将这些导入导出配置的逻辑移动到 https://github.com/halo-dev/halo/blob/main/ui/console-src/modules/interface/themes/composables/use-theme.ts

2024-06-17 14:21 UTC, LIlGG commented on ui/console-src/modules/interface/themes/ThemeDetail.vue
> +};
之前确实考虑过。但又考虑到这些功能除了 upload 之外与 Vue 没有太大相关性，所以没移动至 use-theme，倒像是一个工具包。

2024-06-17 14:27 UTC, ruibaby commented on ui/console-src/modules/interface/themes/ThemeDetail.vue
> +};
可以考虑将导入导出的逻辑放在新的 useThemeConfigFile 之类的方法，主要考虑到这段逻辑放在 SFC 太长。

2024-06-17 14:28 UTC, ruibaby commented on ui/console-src/modules/interface/themes/ThemeDetail.vue
> +};
```ts
const { handleExportThemeConfig, handleImportThemeConfigByFile } = useThemeConfigFile(selectedTheme)
```

2024-06-19 10:43 UTC, ruibaby approved these changes
/lgtm

2024-06-19 10:55 UTC, merged