chore: share device  and rememberMe services with plugins
halo-dev/halo pull request #6176
Opened 2024-06-27 08:53 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.17.x

#### What this PR does / why we need it:
将 RememberMeServices 和 DeviceService Bean 共享给插件使用

#### Does this PR introduce a user-facing change?
```release-note
None
```

2024-06-27 09:44 UTC, ruibaby reviewed
/lgtm

2024-06-27 10:17 UTC, JohnNiang requested changes
`RememberMeServices` 和 `DeviceService` 接口需要放到 api module 下面才能够被插件正确使用。

另外，如果只是针对登录的场景，看能否只提供一个接口专门用户登录成功之后的处理呢。在 Core 和插件中直接调用该接口实现登录成功后的逻辑。

2024-07-01 04:47 UTC, guqing commented
see also https://github.com/halo-sigs/plugin-oauth2/pull/48

2024-07-01 06:28 UTC, ruibaby reviewed
/lgtm

2024-07-01 06:48 UTC, JohnNiang approved these changes
/approve

2024-07-01 06:49 UTC, merged