feat: video attachments add cover
halo-dev/halo pull request #6265
Opened 2024-07-03 17:45 UTC by LonelySnowman

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

附件页面视频文件展示封面

#### Which issue(s) this PR fixes:

Fixes https://github.com/halo-dev/halo/issues/5945

#### Special notes for your reviewer:

![image](https://github.com/halo-dev/halo/assets/111493458/772aa224-fb56-445d-8da5-be5a67be2fa4)

#### Does this PR introduce a user-facing change?

```release-note
附件页面视频文件展示封面
```

2024-07-04 05:14 UTC, LonelySnowman commented
可以重新跑下 e2e-test 嘛，我看了下我这边的改动应该不会影响到 http://halo:8090/apis/api.console.halo.run/v1alpha1/users/vuVGTj/password 报错的这个接口。

2024-07-09 09:39 UTC, ruibaby requested changes
感谢参与贡献，以下是一些改进建议。

2024-07-09 09:39 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/AttachmentList.vue
> +                        :src="attachment.status?.permalink"
建议和图片保持一致，添加 `object-cover group-hover:opacity-75` 类。

这样可以让封面铺满，比如：

<img width="1656" alt="image" src="https://github.com/halo-dev/halo/assets/21301288/38efc328-4f29-412b-bfbc-f61ef60e15bc">

2024-07-10 02:12 UTC, ruibaby approved these changes
/lgtm

Thanks

2024-07-10 02:13 UTC, merged