feat: API to save external links as attachments
halo-dev/halo pull request #6364
Opened 2024-07-24 08:07 UTC by LIlGG

#### What type of PR is this?

/kind api-change
/kind feature
/area core

#### What this PR does / why we need it:

增加将第三方资源转存为附件资源的接口。

`/apis/api.console.halo.run/v1alpha1/attachments/external-transfer`

其中参数为

```json
{
  "externalUrl": "string",
  "filename"?: "string",
  "groupName"?: "string",
  "policyName": "string"
}
```

#### How to test it?

测试能否将第三方接口的资源保存至附件中。
测试各类附件，例如图片、视频、文本等。

#### Does this PR introduce a user-facing change?
```release-note
增加通过链接转存第三方资源至附件库的接口
```

2024-07-25 04:35 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            .POST("/attachments/external-transfer", contentType(MediaType.APPLICATION_JSON),
```suggestion
            .POST("/attachments/-/upload-from-url", contentType(MediaType.APPLICATION_JSON),
```

2024-07-25 05:06 UTC, guqing requested changes

2024-07-25 05:06 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
> +        return contentMono.flatMap(
建议增加对文件大小的限制，同时需要考虑请求中途被取消的情况（如上传时间长用户手动取消）这里的 upload 我不确定在这种情况下是什么行为

2024-07-25 05:06 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
> +                mediaTypeRef.set(contentType);
校验 mediaType 只允许图片和视频

2024-07-25 05:06 UTC, guqing commented on application/src/main/java/run/halo/app/infra/ReactiveUrlDataBufferFetcher.java
> +    Mono<ResponseEntity<Void>> getHEAD(URI uri);
```suggestion
    Mono<ResponseEntity<Void>> head(URI uri);
```

2024-07-25 05:07 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            .POST("/attachments/external-transfer", contentType(MediaType.APPLICATION_JSON),
同时这里应该需要定义一个 rules 在附件相关的角色模板中，否则此 API 只能允许超级管理员调用

2024-07-25 06:47 UTC, JohnNiang commented
Hi @LIlGG ，我已经创建了新的 PR 专门用来修改 API 文档的版本，这样可以避免当前 PR 产生一些无关的修改。

See https://github.com/halo-dev/halo/pull/6378 for more.

待该 PR 合并后，你可以通过重新生成 API 文档和 api-client 来解决冲突。

```bash
./gradlew generateOpenApiDocs
make -C ui api-client-gen
```

2024-07-25 06:57 UTC, LIlGG commented
> Hi @LIlGG ，我已经创建了新的 PR 专门用来修改 API 文档的版本，这样可以避免当前 PR 产生一些无关的修改。

了解了，等此 PR 合并之后我会重新生成一次 OpenAPI。

2024-07-25 07:14 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            .POST("/attachments/external-transfer", contentType(MediaType.APPLICATION_JSON),
不太理解这里添加一个 `-` 的作用是什么。直接改名为 `upload-from-url` 是否更恰当?

```suggestion
            .POST("/attachments/upload-from-url", contentType(MediaType.APPLICATION_JSON),
```

2024-07-25 07:20 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            if (Objects.isNull(externalUrl) || !PathUtils.isAbsoluteUri(externalUrl.toString())) {
> if (!StringUtils.hasText(url)) {

这里的 url 是 `URL` 类型的，应该不能使用 `!StringUtils.hasText(url)` 方法。我换成了 `Objects.isNull(url)`

2024-07-25 07:20 UTC, JohnNiang commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            .POST("/attachments/external-transfer", contentType(MediaType.APPLICATION_JSON),
因为我们的 URL 要符合 Resource 规范才能正确配置权限。这里 external-transfer，一是无法正常配置权限，二是占用了一个名称为 metadata.name 为 external-transfer 的附件。

2024-07-25 07:35 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
> +                new ServerWebInputException(
我看了一下，目前使用 `ServerWebInputException` 的地方基本都没有实现国际化处理。我的建议是在后续统一对所有使用 `ServerWebInputException` 的地方做国际化。

这里目前可以由前端调用的地方来处理，例如在编辑器中的图片转存失败等等，由各个业务处理。

2024-07-25 07:46 UTC, LIlGG commented on application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
> +            .POST("/attachments/external-transfer", contentType(MediaType.APPLICATION_JSON),
> 因为我们的 URL 要符合 Resource 规范才能正确配置权限。这里 external-transfer，一是无法正常配置权限，二是占用了一个名称为 metadata.name 为 external-transfer 的附件。

了解了。那我这边改一下。

2024-07-25 08:05 UTC, LIlGG commented
/hold 目前接口还需要有很多需要考虑设计的地方，比如

- 安全性，对于第三方资源的类型进行限制。
- 文件大小，对于文件的大小进行限制。
- 需要对个人中心提供单独的接口。

因此暂时先停止合并，等待其配套工作完成之后再做此功能。

2024-07-29 12:37 UTC, JohnNiang commented
Hi @LIlGG ，请先解决一下冲突。

2024-08-19 03:36 UTC, LIlGG commented
/unhold

对于文件安全性和大小的限制，在 PR #6390 中已经实现。

2024-08-20 09:50 UTC, guqing requested changes

2024-08-20 09:50 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
> +        if (!FileNameUtils.hasFileExtension(fileName)) {
如果这里没有逻辑建议先将判断去掉，有 TODO 即可

2024-08-20 09:50 UTC, guqing commented on application/src/main/resources/extensions/role-template-attachment.yaml
> +      "/apis/api.console.halo.run/v1alpha1/attachments/-/upload-from-url"
角色模板这里配置的不对，根据你的规则 upload-from-url 是资源型的 url

2024-08-20 09:51 UTC, guqing commented on application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
> +        // TODO validate url
这里的 TODO 建议明确一下，是校验 URL 的什么，比如是校验是否为站内地址

2024-08-23 02:54 UTC, guqing commented
测试失败了需要修复一下

2024-08-26 03:07 UTC, JohnNiang reviewed
/ping @halo-dev/sig-halo 
/approve

2024-08-26 06:25 UTC, ruibaby approved these changes
/lgtm

2024-08-26 06:30 UTC, guqing approved these changes

2024-08-26 06:31 UTC, merged