feat: add file size and type restriction for local file uploads
halo-dev/halo pull request #6390
Opened 2024-07-26 09:42 UTC by guqing

#### What type of PR is this?
/kind feature
/area core

#### What this PR does / why we need it:
本次 PR 为本地附件存储策略增加了对上传单文件大小和文件类型限制的功能，具体包括：

1. 单文件大小限制：
实现了对单个文件上传大小的验证功能，确保上传文件不超过设定的最大值。
2. 文件类型限制：
添加了文件类型限制功能，使用 Apache Tika 读取上传文件的 magic numbers 得到文件 mime type 并根据用户配置来决定是否允许上传

#### Which issue(s) this PR fixes:
Fixes #6385

#### Does this PR introduce a user-facing change?
```release-note
为本地附件存储策略增加了对上传单文件大小和文件类型限制的功能
```

2024-07-26 09:51 UTC, LIlGG commented on application/src/main/resources/extensions/attachment-local-policy.yaml
> +              value: ARCHIVE
这里可以使用 `multiple` 来支持多选。

```suggestion
        - $formkit: select
          name: allowedFileTypes
          label: 文件类型限制
          help: 限制允许上传的文件类型
          multiple
          options:
            - label: 无限制
              value: ALL
            - label: 图片
              value: IMAGE
            - label: SVG
              value: SVG
            - label: 视频
              value: VIDEO
            - label: 音频
              value: AUDIO
            - label: 文档
              value: DOCUMENT
            - label: 压缩包
              value: ARCHIVE
```

2024-07-31 03:11 UTC, ruibaby requested changes

2024-07-31 03:11 UTC, ruibaby commented on application/src/main/resources/extensions/attachment-local-policy.yaml
> +            matches: "输入格式错误，遵循：整数+大写的单位(KB, MB, GB)"
```suggestion
            matches: "输入格式错误，遵循：整数 + 大写的单位（KB、MB、GB）"
```

2024-07-31 03:11 UTC, ruibaby commented on application/src/main/resources/extensions/attachment-local-policy.yaml
> +          help: "0 表示不限制，示例: 5KB, 10MB, 1GB"
```suggestion
          help: "0 表示不限制，示例: 5KB、10MB、1GB"
```

2024-07-31 09:29 UTC, ruibaby reviewed
/lgtm

2024-08-01 01:56 UTC, ruibaby approved these changes
/approve

2024-08-01 01:58 UTC, merged