refactor: editor code block to be extensible by plugins
halo-dev/halo pull request #6428
Opened 2024-08-01 08:32 UTC by LIlGG

#### What type of PR is this?

/kind improvement
/area editor
/area ui

#### What this PR does / why we need it:

此 PR 重构了默认编辑器中代码块的相关代码，使编辑器能够被插件扩展。这样做的优点是当用户使用例如 [highlightjs](https://github.com/halo-sigs/plugin-highlightjs) 这类的高亮插件时，可以保证在 Console 端选择的语言及主题可以在主题端完美适配。

具体做了以下几处重构：

1. 在默认编辑器的代码块中，不再提供高亮样式，代码块高亮将完全交由插件来适配。（但可以在默认的代码块中自定义输入语言，主题端自行处理）。
2. 为了防止出现重复的插件功能，将会根据插件优先级及加载顺序（后加载优先级高于先加载），对同类型且同名的插件进行过滤，只保留一个。
3. 重构代码块 `Select` 组件，使得选择语言或主题更加方便。
4. 为代码块提供主题的扩展设置项。

建议在此 PR 合并之后，由 Halo 默认提供一个高亮插件作为预设插件，这样可以用于解决原有功能升级之后丢失的问题。

#### How to test it?

测试是否会改变已有代码块的语言等。
测试使用第三方插件之后，是否具有高亮。
设置高亮语言后，保存并刷新，查看高亮语言是否存在。主题同理。
查看主题端是否能够正常渲染。

#### Does this PR introduce a user-facing change?
```release-note
重构默认编辑器代码块使其能够被插件扩展。
```

2024-08-02 03:05 UTC, JohnNiang reviewed
/ping @halo-dev/sig-halo-console

2024-08-05 04:11 UTC, guqing reviewed
/lgtm

2024-08-05 06:29 UTC, ruibaby commented on ui/src/components/editor/DefaultEditor.vue
> +const presetExtension = [
```suggestion
const presetExtensions = [
```

2024-08-05 06:30 UTC, ruibaby commented on ui/src/components/editor/DefaultEditor.vue
> +    extensions: extension,
```suggestion
    extensions,
```

2024-08-05 06:42 UTC, LIlGG commented on ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
>  }>();
可以是可以，但对于 `extension` 这个属性来说，就没有 typescript 的类型提示了。因为在 `NodeViewProps` 中它是无类型的。

2024-08-05 06:44 UTC, ruibaby commented on ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
>  }>();
用类似 Omit 去排除原有的 extension 呢

2024-08-13 06:46 UTC, ruibaby requested changes

2024-08-13 06:46 UTC, ruibaby commented on ui/packages/editor/src/extensions/code-block/code-block.ts
> +  languages: Array<string> | ((state: EditorState) => Array<string>);
观察到目前仅支持 language value，但是不支持让插件提供显示名称，目前是将 language 的首字母大写作为显示名称，这样效果不是太好。

<img width="415" alt="image" src="https://github.com/user-attachments/assets/7b3ee354-e474-47b1-aa04-03ed95a0d8b9">

主流的高亮库应该是可以拿到语言列表的。

2024-08-14 03:03 UTC, LIlGG commented on ui/packages/editor/src/extensions/code-block/code-block.ts
> +  languages: Array<string> | ((state: EditorState) => Array<string>);
还需要高亮插件来适配

2024-08-23 09:26 UTC, guqing commented
有冲突需要解决一下

2024-08-26 02:40 UTC, ruibaby reviewed
/lgtm

2024-08-26 02:43 UTC, guqing reviewed
/lgtm

2024-08-26 02:54 UTC, ruibaby approved these changes
/approve

2024-08-26 02:55 UTC, merged