make comment and reply list item operations extendable
halo-dev/halo pull request #6438
Opened 2024-08-03 17:27 UTC by chengzhongxue

#### What type of PR is this?

/area console
/kind feature
/milestone 2.18.x

#### What this PR does / why we need it:

评论和回复管理列表项的操作按钮支持被插件扩展。
![image](https://github.com/user-attachments/assets/20174eda-ec46-4ab2-b1d9-c27e4aaa6cba)
![image](https://github.com/user-attachments/assets/ac44c221-71f5-4077-8116-a92245c22697)

#### Which issue(s) this PR fixes:

Fixes #6392 

#### Special notes for your reviewer:

需要评论和回复的关于列表的已有功能是否正常。

如果需要测试扩展点是否有效，可以使用此插件测试：[plugin-starter-1.0.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16482348/plugin-starter-1.0.0-SNAPSHOT.jar.zip)

```
export default definePlugin({
  components: {},
  routes: [],
  extensionPoints: {
    "comment:list-item:operation:create": (comment: Ref<ListedComment>) => {
      return [
        {
          priority: 21,
          component: markRaw(VDropdownItem),
          label: "测试评论菜单",
          visible: true,
          permissions: [],
          action: () => {
            console.log(comment)
          },
        },
      ];
    },
    "reply:list-item:operation:create": (reply: Ref<ListedReply>) => {
      return [
        {
          priority: 11,
          component: markRaw(VDropdownItem),
          label: "测试回复菜单",
          visible: true,
          permissions: [],
          action: () => {
            console.log(reply)
          },
        },
      ];
    },
  },
});
```

#### Does this PR introduce a user-facing change?

```
Console 评论和回复管理列表项的操作按钮支持被插件扩展。
```

2024-08-03 17:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/halo-dev/halo?pullRequest=6438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=6438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=6438) it.</sub>

2024-08-05 02:56 UTC, ruibaby requested changes

2024-08-05 02:56 UTC, ruibaby commented on ui/console-src/modules/contents/comments/components/CommentListItem.vue
> +import {useOperationItemExtensionPoint} from "@console/composables/use-operation-extension-points";
这里的格式化似乎有问题，建议执行一遍 `pnpm prettier`。

2024-08-05 02:56 UTC, ruibaby commented
> [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/halo-dev/halo?pullRequest=6438) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/halo-dev/halo?pullRequest=6438) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/halo-dev/halo?pullRequest=6438) it.

@chengzhongxue 感谢参与贡献，在合并之前需要先签署一下我们的 CLA。

2024-08-05 03:00 UTC, chengzhongxue commented on ui/console-src/modules/contents/comments/components/CommentListItem.vue
> +import {useOperationItemExtensionPoint} from "@console/composables/use-operation-extension-points";
好的，我看看

2024-08-05 03:02 UTC, ruibaby commented on ui/console-src/modules/contents/comments/components/CommentListItem.vue
> +import {useOperationItemExtensionPoint} from "@console/composables/use-operation-extension-points";
修改之后直接在当前分支推送 commit 就行了，不需要重新提交 PR。

2024-08-05 03:35 UTC, ruibaby reviewed
/lgtm

感谢贡献，这个改动需要更新一下开发者文档。

https://github.com/halo-dev/docs

2024-08-05 03:39 UTC, chengzhongxue commented
> /lgtm
> 
> 感谢贡献，这个改动需要更新一下开发者文档。
> 
> https://github.com/halo-dev/docs

好的

2024-08-05 06:55 UTC, ruibaby approved these changes

2024-08-05 06:56 UTC, merged