feat: add config option to allow disabling Basic authentication
halo-dev/halo pull request #6689
Opened 2024-09-23 08:24 UTC by guqing

#### What type of PR is this?
/milestone 2.20.x
/area core
/kind improvement

#### What this PR does / why we need it:
允许通过 `halo.security.disableBasicAuth=true` 配置来禁用 Basic Auth 认证

#### Which issue(s) this PR fixes:
Fixes #5408

#### Does this PR introduce a user-facing change?
```release-note
允许通过 `halo.security.disableBasicAuth=true` 配置来禁用 Basic Auth 认证
```

2024-09-28 10:36 UTC, JohnNiang requested changes

2024-09-28 10:36 UTC, JohnNiang commented on application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
> +    private boolean disableBasicAuth = false;
```java
 @Data
    public static class BasicAuthOptions {

        /**
         * Whether basic authentication is disabled.
         */
        private boolean disabled = true;
    }
```

推荐使用这种方式来控制。另外默认情况下，我们禁用 Basic Auth，可以在 application-dev.yaml 中配置 `halo.security.basic-auth.disabled=false` 以保证开发环境下可以正常使用 Basic Auth 认证方式。

2024-09-29 02:53 UTC, guqing commented on application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
> +    private boolean disableBasicAuth = false;
如果将默认行为改了,属于破坏性更新,可能会导致以前没有 pat 之前的一些工具或插件的  API 调用受到影响,是否允许这种破坏性更新

2024-09-29 10:14 UTC, guqing commented on application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
> +    private boolean disableBasicAuth = false;
Done

2024-09-29 10:15 UTC, ruibaby reviewed
/lgtm

2024-09-29 10:17 UTC, guqing commented
⚠️ 此 PR 属于破坏性更新，生产环境下默认禁用了 Basic Auth

2024-09-30 03:58 UTC, JohnNiang approved these changes
/approve

2024-09-30 03:59 UTC, merged