refactor: head and footer tag injection to skip error pages
halo-dev/halo pull request #6709
Opened 2024-09-26 09:51 UTC by guqing

#### What type of PR is this?
/kind improvement
/area core
/milestone 2.20.x

#### What this PR does / why we need it:
模板 head 和 footer 标签注入功能忽略错误页面避免当扩展发生错误时导致错误页面无法显示

#### Which issue(s) this PR fixes:
Fixes #6500

#### Does this PR introduce a user-facing change?
```release-note
模板 head 和 footer 标签注入功能忽略错误页面避免当扩展发生错误时导致错误页面无法显示
```

2024-09-27 03:22 UTC, ruibaby reviewed
/lgtm

2024-09-27 06:00 UTC, JohnNiang reviewed
Issue 描述的问题是：当因为 TemplateFooterElementTagProcessor 或者 GlobaleadInjectionProcessor 发生错误时，才忽略这些错误直接渲染。而不是发生错误渲染错误页面的时候就忽略这两个 Processor 了。

2024-09-27 06:07 UTC, guqing commented
> Issue 描述的问题是：当因为 TemplateFooterElementTagProcessor 或者 GlobaleadInjectionProcessor 发生错误时，才忽略这些错误直接渲染。而不是发生错误渲染错误页面的时候就忽略这两个 Processor 了。

错误页面本身也就不需要注入,况且如果只是 GlobaleadInjectionProcessor  发生错误时如果要忽略那应该是扩展自己通过 onErrorResume 忽略,而不是由 GlobaleadInjectionProcessor 来忽略错误

2024-10-07 09:20 UTC, JohnNiang requested changes

2024-10-07 09:20 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        var error = context.getVariable(ProblemDetailErrorAttributes.ERROR_INTERNAL_ATTRIBUTE);
推荐使用 `org.springframework.boot.web.reactive.error.ErrorAttributes#getError` 判断是否有错误。

2024-10-08 02:29 UTC, guqing commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        var error = context.getVariable(ProblemDetailErrorAttributes.ERROR_INTERNAL_ATTRIBUTE);
> 推荐使用 `org.springframework.boot.web.reactive.error.ErrorAttributes#getError` 判断是否有错误。

它的参数需要的是一个 ServerRequest 而在 processor 中只能得到 thymeleaf 包装的 
<img width="445" alt="image" src="https://github.com/user-attachments/assets/62722d5f-59e4-4b35-b61c-7c386fa533bd">

同时 getError 的实现如下
```java
public Throwable getError(ServerRequest request) {
        Optional<Object> error = request.attribute(ERROR_INTERNAL_ATTRIBUTE);
        return (Throwable)error.orElseThrow(() -> {
            return new IllegalStateException("Missing exception attribute in ServerWebExchange");
        });
    }
```
ERROR_INTERNAL_ATTRIBUTE 来自 DefaultErrorAttributes 但是为私有，而我们写的 ProblemDetailErrorAttributes 继承自 DefaultErrorAttributes 完全可以像它一样加一个属性用

2024-10-09 01:56 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        var error = context.getVariable(ProblemDetailErrorAttributes.ERROR_INTERNAL_ATTRIBUTE);
你可能没有理解我的意思。我们可以直接注入 ErrorAttributes bean 或者直接获取到 ApplicationContext 再获取这个 bean，接着再调用 ErrorAttributes#getError 方法。

2024-10-09 04:18 UTC, guqing commented on application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
> +        var error = context.getVariable(ProblemDetailErrorAttributes.ERROR_INTERNAL_ATTRIBUTE);
考虑到可能还需要排除登录、注册等页面的代码注入而不仅仅是错误页面，因此我将改为模板匹配的方式处理

2024-10-10 04:55 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/PageInjectionExcluderImpl.java
> +        "password-reset",
密码重置模板已经重新放置到了 `password-reset/` 目录下了。

所以这里可能需要在 regexPatterns 中添加 `password-reset/.*`

2024-10-10 04:55 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/PageInjectionExcluderImpl.java
> +        "password-reset-link"
最新版中已经没有这个模板了。

2024-10-10 05:19 UTC, guqing commented on application/src/main/java/run/halo/app/theme/PageInjectionExcluderImpl.java
> +        "password-reset-link"
Done

2024-10-10 06:23 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/PageInjectionExcluderImpl.java
> +public class PageInjectionExcluderImpl implements PageInjectionExcluder {
感觉这里没有必要声明成一个 Bean，直接在 InjectionExcluderProcessor 中 new 一个 PageInjectionExcluderImpl 即可。

2024-10-10 07:26 UTC, guqing commented on application/src/main/java/run/halo/app/theme/PageInjectionExcluderImpl.java
> +public class PageInjectionExcluderImpl implements PageInjectionExcluder {
目前来说直接 new 也是可以的

2024-10-10 08:20 UTC, JohnNiang commented on application/src/main/java/run/halo/app/theme/dialect/InjectionExcluderProcessor.java
> +            Pattern.compile("login_.*")
这个规则似乎可以删除掉。目前不会**直接**渲染以 `login_` 开头的模板。一般都是通过 fragment 的方式引用，因为我们是在 TemplateBoundariesProcessor 中进行判断的，所以模板名不会包含这些 fragment template。

```suggestion
            Pattern.compile("password-reset/.*")
```

2024-10-10 09:34 UTC, guqing commented on application/src/main/java/run/halo/app/theme/dialect/InjectionExcluderProcessor.java
> +            Pattern.compile("login_.*")
Ok

2024-10-10 09:35 UTC, JohnNiang approved these changes
/lgtm

2024-10-10 09:45 UTC, merged