Feature/avoid auplicate grouping or strategies
halo-dev/halo pull request #6959
Opened 2024-10-28 07:10 UTC by LEIYOUSU

/kind improvement
Fixes #6946
```None
```

2024-10-28 11:33 UTC, ruibaby requested changes
感谢参与贡献，以下是 Review 的改进建议，请有时间看看。

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
> +    const existingGroupsResponse =
```ts
const { data: groups } = await coreApiClient.storage.group.listGroup();

const hasDisplayNameDuplicate  = groups.items.some((group) => group.spec.displayName === formState.value.spec.displayName
```

这样可能更好。

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
> +      alert("该分组名称已存在，请重新创建!");
需要完善 i18n，https://github.com/halo-dev/halo/tree/main/ui/src/locales

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
> +      alert("该分组名称已存在，请重新创建!");
此外，不建议用 alert，Halo 的 `@halo-dev/components` 包有 Toast。

示例：

```release-note
Toast.error("该分组名称已存在，请重新创建")
```

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
> +const { data: policies } = useQuery({
可以直接用 https://github.com/halo-dev/halo/blob/25086ee3e63f0c8b6ed380140a068c44404ef2b2/ui/console-src/modules/contents/attachments/composables/use-attachment-policy.ts#L18

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
> +    const nameExists = policies.value?.items.some(
```suggestion
    const hasDisplayNameDuplicate = policies.value?.items.some(
```

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
> +      alert("该存储策略名称已存在，请重新创建!");
同上

2024-10-28 11:33 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
> +        <AttachmentPolicyBadge @click="handleOpenCreateNewGroupModal">
这里的改动是因为什么？

2024-10-28 11:39 UTC, LEIYOUSU commented on ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
> +        <AttachmentPolicyBadge @click="handleOpenCreateNewGroupModal">
> 这里的改动是因为什么？

因为AttachmentGroupBadge的样式右上角是存在三个点(点击之后是重命名和删除)，这里只是新建按钮，然后我后面看见的时候发现它的样式多了三个点，后来改成了AttachmentPolicyBadge ，就好了。其余问题我会尽快修改的，谢谢指导!

2024-10-28 11:46 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
> +        <AttachmentPolicyBadge @click="handleOpenCreateNewGroupModal">
还是建议用 AttachmentGroupBadge，因为这里和 Policy 无关，隐藏操作按钮可以参考：https://github.com/halo-dev/halo/blob/25086ee3e63f0c8b6ed380140a068c44404ef2b2/ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue#L102

加上 `:features="{ actions: false }"` 即可。

2024-10-29 07:21 UTC, ruibaby commented
Hi @LEIYOUSU，感谢参与贡献，有一点非代码层面的建议：

1. PR 描述尽可能按照模板的格式，可以看看我帮你修改的。
2. 已解决的 Change Request 可以点击一下 `Resolve conversation` 按钮，并请求指定的人重新 Review。

2024-10-29 07:28 UTC, ruibaby requested changes

2024-10-29 07:28 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
> +    const { data: groups } = await coreApiClient.storage.group.listGroup();
这里似乎有一个隐藏的问题，如果在这里判断，那么在编辑分组的时候会把自身判断进去，会导致编辑分组的时候必须改名，所以这里建议仅在创建的时候判断。

2024-10-29 07:28 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
> +    const { data: policies } = await coreApiClient.storage.policy.listPolicy();
同上。

2024-10-29 07:29 UTC, ruibaby commented
我优化了一下 i18n，请看 <https://github.com/halo-dev/halo/pull/6959/commits/8dda8cd84423e0b1b735ca27623362f10120b5ae>，提交新的改动时，记得 pull 一下。

2024-10-29 07:32 UTC, LEIYOUSU commented
感谢你的耐心指导和建议，我会尽快解决一下

2024-10-29 12:10 UTC, ruibaby commented
@LEIYOUSU 不用关闭 PR 重新提交的，直接继续推送到这个分支即可。

2024-10-30 02:42 UTC, ruibaby requested changes

2024-10-30 02:42 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
> +    isNew: false,
好像不需要用一个属性标记，可以通过是否传入了 props.group 判断，其实在 handleSave 函数中已经有这样的判断了。

https://github.com/halo-dev/halo/blob/fdc90aff5c6c8855bb46e21f146ed9c9247c36c8/ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue#L52-L55

2024-10-30 02:42 UTC, ruibaby commented on ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
> +    isNew?: boolean;
同上

2024-10-30 03:25 UTC, ruibaby approved these changes
/lgtm

2024-10-30 03:27 UTC, guqing approved these changes

2024-10-30 03:30 UTC, merged