change-user-role-and-delete
halo-dev/halo pull request #6963
Opened 2024-10-29 02:19 UTC by LEIYOUSU

/kind improvement
Fixes #6944
```NONE
```

2024-10-29 07:32 UTC, ruibaby requested changes

2024-10-29 07:32 UTC, ruibaby commented on ui/src/locales/zh-CN.yaml
> +        grant_permission:
建议完善一下 en.yaml、zh-TW.yaml，目前我们还没有在线的翻译平台，所以只能尽可能完善一下。

2024-10-30 03:12 UTC, ruibaby requested changes

2024-10-30 03:12 UTC, ruibaby commented on ui/src/locales/en.yaml
> +            title: Assign roles
```suggestion
            title: Grant permission
```

2024-10-30 03:33 UTC, ruibaby approved these changes
/lgtm

感谢 @LEIYOUSU 的贡献。

2024-10-30 03:42 UTC, JohnNiang commented
在合并之前需要先解决一下 CI 错误。

2024-10-30 04:17 UTC, ruibaby commented
> 在合并之前需要先解决一下 CI 错误。

Fixed

2024-10-30 04:50 UTC, JohnNiang approved these changes
/lgtm

2024-10-30 04:50 UTC, merged